-- Conteúdo autoral Security+ SY0-701, criado a partir dos materiais fornecidos.
-- Esta migração é idempotente: pode ser executada sem duplicar aulas ou questões.

INSERT INTO `lessons` (`domainId`, `title`, `content`, `order`, `duration`)
SELECT d.`id`, 'Security+ em campo: princípios, controles e mudanças',
  '## Propósito\nEsta aula aplica os conceitos de confidencialidade, integridade, disponibilidade, autenticação, autorização e responsabilização a decisões cotidianas de segurança.\n\n## Cenário\nUma empresa vai liberar acesso remoto a um sistema financeiro. Antes de escolher uma ferramenta, mapeie os ativos, os usuários, as permissões mínimas, os registros necessários e a continuidade do serviço.\n\n## Método prático\n1. Classifique o dado e identifique quem precisa acessá-lo.\n2. Escolha controles preventivos, detectivos e corretivos proporcionais ao risco.\n3. Aplique menor privilégio e segregação de funções.\n4. Registre uma janela de mudança com plano de reversão.\n5. Verifique o resultado e documente as evidências.\n\n## Checklist de estudo\nDiferencie controles técnicos, administrativos, físicos, compensatórios e de dissuasão. Relacione cada controle a um risco concreto, não apenas a uma tecnologia.',
  101, 35
FROM `domains` d
WHERE d.`code` = 'DOM1'
  AND NOT EXISTS (SELECT 1 FROM `lessons` l WHERE l.`domainId` = d.`id` AND l.`title` = 'Security+ em campo: princípios, controles e mudanças');

INSERT INTO `lessons` (`domainId`, `title`, `content`, `order`, `duration`)
SELECT d.`id`, 'Security+ em campo: modelagem de ameaças e mitigação',
  '## Propósito\nTransformar um cenário de negócio em hipóteses verificáveis de ameaça, vulnerabilidade, impacto e tratamento de risco.\n\n## Cenário\nUm portal de fornecedores aceita anexos e usa contas com privilégios elevados para manutenção. Modele caminhos de ataque possíveis, como abuso de credenciais, envio de arquivo malicioso e elevação de privilégio.\n\n## Método prático\n1. Desenhe ativos, interfaces, limites de confiança e fluxos de dados.\n2. Liste ameaças plausíveis e as vulnerabilidades que as viabilizam.\n3. Priorize com probabilidade e impacto, validando a criticidade do ativo.\n4. Selecione mitigação: reduzir, transferir, aceitar ou evitar o risco.\n5. Meça o efeito dos controles e reavalie o risco residual.\n\n## Checklist de estudo\nDiferencie IOC, IOA, vulnerabilidade, exposição, vetor de ataque e exploit. Use linguagem baseada em evidência ao comunicar risco.',
  102, 35
FROM `domains` d
WHERE d.`code` = 'DOM2'
  AND NOT EXISTS (SELECT 1 FROM `lessons` l WHERE l.`domainId` = d.`id` AND l.`title` = 'Security+ em campo: modelagem de ameaças e mitigação');

INSERT INTO `lessons` (`domainId`, `title`, `content`, `order`, `duration`)
SELECT d.`id`, 'Security+ em campo: arquitetura híbrida e Zero Trust',
  '## Propósito\nProjetar controles coerentes para ambientes locais, nuvem, dispositivos móveis e parceiros externos sem confiar implicitamente na localização da rede.\n\n## Cenário\nUma equipe acessa aplicações SaaS, uma API interna e arquivos confidenciais a partir de redes externas. O desenho deve reduzir movimento lateral e validar cada solicitação de acesso.\n\n## Método prático\n1. Identifique identidades humanas, de serviço e de dispositivo.\n2. Verifique explicitamente o contexto de cada acesso.\n3. Aplique acesso de menor privilégio por função, atributo e tempo.\n4. Segmente cargas, redes e dados conforme criticidade.\n5. Centralize telemetria para revisão e resposta.\n\n## Checklist de estudo\nCompare segmentação, microsegmentação, SASE, VPN, ZTNA, MFA resistente a phishing e gestão de configuração segura.',
  103, 35
FROM `domains` d
WHERE d.`code` = 'DOM3'
  AND NOT EXISTS (SELECT 1 FROM `lessons` l WHERE l.`domainId` = d.`id` AND l.`title` = 'Security+ em campo: arquitetura híbrida e Zero Trust');

INSERT INTO `lessons` (`domainId`, `title`, `content`, `order`, `duration`)
SELECT d.`id`, 'Security+ em campo: detecção, resposta e preservação de evidências',
  '## Propósito\nConduzir uma resposta a incidente repetível, preservando evidências e aprendendo com o evento.\n\n## Cenário\nAlertas indicam autenticações incomuns e transferência de arquivos fora do horário normal. A equipe deve investigar sem destruir dados relevantes nem ampliar o impacto.\n\n## Método prático\n1. Valide o alerta com logs, contexto de ativos e linha do tempo.\n2. Classifique a severidade e acione o plano de resposta.\n3. Contenha com mudanças reversíveis e documentadas.\n4. Preserve evidências com cadeia de custódia e registros de quem manipulou cada item.\n5. Erradique a causa, recupere de forma controlada e conduza lições aprendidas.\n\n## Checklist de estudo\nDiferencie playbook, runbook, triagem, contenção, erradicação, recuperação, análise pós-incidente e requisitos de retenção de logs.',
  104, 35
FROM `domains` d
WHERE d.`code` = 'DOM4'
  AND NOT EXISTS (SELECT 1 FROM `lessons` l WHERE l.`domainId` = d.`id` AND l.`title` = 'Security+ em campo: detecção, resposta e preservação de evidências');

INSERT INTO `lessons` (`domainId`, `title`, `content`, `order`, `duration`)
SELECT d.`id`, 'Security+ em campo: governança, risco e conformidade aplicada',
  '## Propósito\nConectar políticas, padrões, riscos de terceiros e métricas de segurança aos objetivos da organização.\n\n## Cenário\nUma organização contrata um fornecedor que processará dados sensíveis. A decisão exige critérios de risco, cláusulas contratuais, responsabilidades, monitoramento e plano de saída.\n\n## Método prático\n1. Defina o requisito de negócio e o proprietário do risco.\n2. Avalie controles, evidências, subcontratados e localização dos dados.\n3. Estabeleça cláusulas de segurança, notificação de incidentes e direito de auditoria.\n4. Monitore indicadores e reavalie mudanças relevantes.\n5. Mantenha plano de continuidade, retenção e descarte seguro.\n\n## Checklist de estudo\nDiferencie política, padrão, procedimento, diretriz, exceção, auditoria, due diligence, risco inerente e residual.',
  105, 35
FROM `domains` d
WHERE d.`code` = 'DOM5'
  AND NOT EXISTS (SELECT 1 FROM `lessons` l WHERE l.`domainId` = d.`id` AND l.`title` = 'Security+ em campo: governança, risco e conformidade aplicada');

INSERT INTO `questions` (`domainId`, `question`, `options`, `correctAnswer`, `explanation`, `difficulty`)
SELECT d.`id`, v.`question`, JSON_ARRAY(v.`optionA`, v.`optionB`, v.`optionC`, v.`optionD`), v.`correctAnswer`, v.`explanation`, v.`difficulty`
FROM `domains` d
JOIN (
  SELECT 'DOM1' AS `domainCode`, 'Uma equipe precisa impedir que um usuário aprove um pagamento que ele próprio cadastrou. Qual princípio deve orientar o controle?' AS `question`, 'Segregação de funções' AS `optionA`, 'Disponibilidade' AS `optionB`, 'Criptografia simétrica' AS `optionC`, 'Aceitação de risco' AS `optionD`, 0 AS `correctAnswer`, 'A segregação de funções reduz a possibilidade de fraude ou erro concentrado em uma única pessoa.' AS `explanation`, 'medium' AS `difficulty`
  UNION ALL SELECT 'DOM1', 'Qual controle é mais adequado para identificar tentativas repetidas de login inválido?', 'Alerta baseado em logs de autenticação', 'Cadeado físico no rack', 'Política de mesa limpa', 'Backup offline', 0, 'Alertas baseados em logs são controles detectivos que ajudam a identificar tentativas anômalas.', 'easy'
  UNION ALL SELECT 'DOM1', 'Antes de uma mudança em produção, qual elemento reduz mais o risco de indisponibilidade prolongada?', 'Plano de reversão testado', 'Senha mais longa', 'Tela de aviso ao usuário', 'Inventário de impressoras', 0, 'Um plano de reversão permite recuperar o serviço de modo controlado caso a mudança falhe.', 'medium'
  UNION ALL SELECT 'DOM1', 'Qual opção melhor representa o princípio do menor privilégio?', 'Conceder apenas o acesso necessário pelo tempo necessário', 'Dar acesso administrativo a todos os analistas', 'Compartilhar uma conta de serviço', 'Desabilitar registros de auditoria', 0, 'Menor privilégio limita permissões ao que é necessário para a atividade legítima.', 'easy'
  UNION ALL SELECT 'DOM1', 'Uma regra exige MFA para acesso administrativo. Essa regra é principalmente um controle:', 'Preventivo', 'Corretivo', 'De recuperação', 'Compensatório por padrão', 0, 'MFA reduz a chance de acesso não autorizado antes que ele ocorra, caracterizando um controle preventivo.', 'medium'
  UNION ALL SELECT 'DOM2', 'Em uma modelagem de ameaças, qual item descreve melhor uma vulnerabilidade?', 'Uma fraqueza que pode ser explorada', 'Um ator que executa um ataque', 'Um registro que indica atividade', 'Uma política aprovada', 0, 'Vulnerabilidade é uma fraqueza em ativo, processo ou controle que pode ser explorada por uma ameaça.', 'easy'
  UNION ALL SELECT 'DOM2', 'Após identificar uma falha em serviço não crítico, a organização documenta a decisão de conviver com ela por 30 dias. Qual tratamento de risco foi escolhido?', 'Aceitar', 'Evitar', 'Transferir', 'Eliminar o ativo', 0, 'Aceitar risco significa reconhecer e documentar o risco residual dentro dos critérios estabelecidos.', 'medium'
  UNION ALL SELECT 'DOM2', 'Qual artefato ajuda mais a representar ativos, fluxos de dados e limites de confiança?', 'Diagrama de fluxo de dados', 'Inventário de licenças', 'Calendário de férias', 'Termo de aceite', 0, 'Diagramas de fluxo de dados evidenciam como dados e componentes atravessam limites de confiança.', 'easy'
  UNION ALL SELECT 'DOM2', 'Qual exemplo é um indicador de ataque (IOA), e não apenas um indicador de comprometimento (IOC)?', 'Execução de comando incomum que tenta enumerar contas', 'Hash de arquivo malicioso já conhecido', 'Endereço IP listado em bloqueio', 'Domínio previamente associado a phishing', 0, 'Um IOA descreve comportamento ou técnica suspeita em andamento; hashes e domínios são exemplos mais comuns de IOC.', 'hard'
  UNION ALL SELECT 'DOM2', 'Qual medida reduz melhor o risco de upload de arquivo malicioso em um portal?', 'Validação de tipo, análise antimalware e isolamento do processamento', 'Aumentar o tamanho máximo do arquivo', 'Ocultar a página de upload', 'Desativar o registro de eventos', 0, 'Controles complementares de validação, análise e isolamento diminuem a exposição do serviço a anexos maliciosos.', 'hard'
  UNION ALL SELECT 'DOM3', 'No modelo Zero Trust, qual afirmação é mais adequada?', 'Cada solicitação deve ser verificada conforme identidade e contexto', 'A rede interna é confiável por definição', 'VPN elimina a necessidade de controles adicionais', 'Segmentação substitui a gestão de identidade', 0, 'Zero Trust evita confiança implícita e verifica explicitamente identidade, dispositivo, contexto e autorização.', 'medium'
  UNION ALL SELECT 'DOM3', 'Qual técnica limita o movimento lateral entre cargas de trabalho?', 'Microsegmentação', 'Balanceamento de carga', 'Compressão de arquivos', 'Redução de resolução de tela', 0, 'Microsegmentação cria controles granulares entre cargas e reduz caminhos desnecessários de comunicação.', 'easy'
  UNION ALL SELECT 'DOM3', 'Uma organização quer conceder acesso temporário a um painel administrativo somente durante um chamado aprovado. Qual prática atende melhor?', 'Acesso just-in-time com aprovação e expiração', 'Conta compartilhada permanente', 'Desativar MFA durante o chamado', 'Permissão administrativa por padrão', 0, 'Acesso just-in-time limita privilégios elevados em duração e contexto, reduzindo exposição.', 'medium'
  UNION ALL SELECT 'DOM3', 'Qual é o principal objetivo de uma baseline de configuração segura?', 'Definir um estado aprovado e comparável para sistemas', 'Substituir todos os testes de segurança', 'Eliminar a necessidade de inventário', 'Desativar atualizações automáticas', 0, 'Baselines definem configurações esperadas e facilitam a identificação de desvios relevantes.', 'medium'
  UNION ALL SELECT 'DOM3', 'Qual controle mais fortalece a autenticação contra phishing em uma aplicação corporativa?', 'MFA resistente a phishing com vínculo criptográfico à origem', 'Perguntas de conhecimento estáticas', 'Reuso de senha complexa', 'Bloqueio de cookies de sessão', 0, 'Métodos resistentes a phishing reduzem o risco de coleta e reutilização de credenciais por páginas falsas.', 'hard'
  UNION ALL SELECT 'DOM4', 'Qual é a primeira ação adequada após receber um alerta de comportamento suspeito?', 'Validar o alerta com contexto e evidências disponíveis', 'Apagar imediatamente todos os logs', 'Desligar todos os sistemas da empresa', 'Publicar um comunicado externo', 0, 'A triagem valida o alerta e reúne contexto antes de decisões de contenção proporcionais.', 'easy'
  UNION ALL SELECT 'DOM4', 'Qual prática preserva melhor a integridade de uma evidência digital?', 'Registrar cadeia de custódia e usar cópia de trabalho', 'Editar o arquivo original para remover dados pessoais', 'Compartilhar a evidência por mensageiro pessoal', 'Desativar o horário sincronizado dos sistemas', 0, 'Cadeia de custódia documenta coleta, acesso e transferência; cópias de trabalho evitam alteração do original.', 'medium'
  UNION ALL SELECT 'DOM4', 'Qual etapa ocorre normalmente após a contenção inicial de um incidente?', 'Erradicação da causa e recuperação controlada', 'Descarte imediato de toda evidência', 'Aceitação automática do risco', 'Desativação definitiva dos registros', 0, 'Após conter o impacto, a equipe trata a causa, recupera o ambiente e confirma a retomada segura.', 'medium'
  UNION ALL SELECT 'DOM4', 'Qual informação é mais útil para correlacionar eventos de segurança de fontes diferentes?', 'Horários sincronizados e identificadores consistentes', 'Cores diferentes nos alertas', 'Tamanho do monitor do analista', 'Nome do fornecedor de internet', 0, 'Sincronização temporal e identificadores consistentes permitem construir uma linha do tempo confiável.', 'easy'
  UNION ALL SELECT 'DOM4', 'Em um playbook de resposta a incidente, qual item deve ser definido antes do evento?', 'Critérios de escalonamento e responsabilidades', 'Conclusão da investigação', 'Data de recuperação final', 'Hash do arquivo desconhecido', 0, 'Playbooks definem previamente responsabilidades, critérios de escalonamento e passos repetíveis para a equipe.', 'medium'
  UNION ALL SELECT 'DOM5', 'Qual documento define o direcionamento geral e obrigatório da organização para segurança?', 'Política', 'Procedimento operacional detalhado', 'Checklist individual', 'Relatório de incidente', 0, 'Políticas estabelecem a intenção e os requisitos de alto nível aprovados pela organização.', 'easy'
  UNION ALL SELECT 'DOM5', 'Antes de contratar um fornecedor que tratará dados sensíveis, qual atividade é mais apropriada?', 'Due diligence de segurança e privacidade', 'Compartilhar credenciais administrativas', 'Dispensar cláusulas contratuais', 'Desativar auditorias', 0, 'Due diligence avalia riscos, controles, responsabilidades e evidências antes da contratação.', 'medium'
  UNION ALL SELECT 'DOM5', 'Qual cláusula contratual apoia mais a resposta a incidente envolvendo terceiro?', 'Prazo de notificação e obrigação de cooperação', 'Uso obrigatório de uma marca de hardware', 'Proibição de todos os logs', 'Ausência de plano de saída', 0, 'Prazos de notificação e cooperação definem expectativas claras para investigação e resposta conjunta.', 'medium'
  UNION ALL SELECT 'DOM5', 'Qual indicador melhor demonstra que um programa de gestão de vulnerabilidades está operando?', 'Percentual de vulnerabilidades críticas tratadas dentro do prazo definido', 'Quantidade de senhas de usuários', 'Número de telas no painel', 'Cor dos relatórios mensais', 0, 'Métricas úteis conectam o desempenho do controle a prazos e criticidade de risco.', 'hard'
  UNION ALL SELECT 'DOM5', 'O que diferencia risco residual de risco inerente?', 'Risco residual permanece após aplicar controles', 'Risco residual existe antes de qualquer controle', 'Risco inerente só envolve terceiros', 'Não há diferença entre os termos', 0, 'Risco inerente é avaliado antes dos controles; o residual é o nível que permanece após seu efeito.', 'medium'
) v ON v.`domainCode` = d.`code`
WHERE NOT EXISTS (
  SELECT 1 FROM `questions` q
  WHERE q.`domainId` = d.`id` AND q.`question` = v.`question`
);
