import { Link } from "wouter";
import { ArrowLeft, BookOpen, CirclePlay, FileText, Headphones, ShieldCheck, Wrench } from "lucide-react";

const standards = [
  { icon: BookOpen, title: "Conteúdo próprio", text: "Aulas, apostilas, roteiros, quizzes, projetos, laboratórios e critérios de certificação são produzidos para a jornada didática da CyberDimension Academy." },
  { icon: CirclePlay, title: "Vídeos externos", text: "Vídeos do YouTube são incorporados como referência complementar. A autoria, a fonte e a licença são exibidas na formação; o vídeo não substitui o material próprio." },
  { icon: Headphones, title: "Audioguias próprios", text: "Audioguias produzidos pela Academia possuem identificação de narração, finalidade e licença de estudo dentro da plataforma." },
  { icon: Headphones, title: "Podcast educacional próprio", text: "O CyberCast Security+ reúne diálogos autorais, áudio publicado pela Academia e transcrições acessíveis para revisão aprofundada dos domínios da certificação." },
  { icon: Wrench, title: "Referências externas", text: "Documentações, artigos, cursos, CTFs e ferramentas podem ser registrados com origem, licença e finalidade pedagógica antes de serem indicados ao aluno." },
];

export default function ContentPolicy() {
  return <div className="min-h-screen space-canvas text-foreground"><div className="pointer-events-none fixed inset-0 space-grid opacity-40" />
    <header className="sticky top-0 z-30 border-b border-white/8 bg-[oklch(0.075_0.025_260/0.84)] backdrop-blur-xl"><div className="container flex min-h-18 items-center justify-between gap-4 py-3"><Link href="/catalog" className="inline-flex items-center gap-2 text-sm font-bold text-neon-cyan"><ArrowLeft className="h-4 w-4" /> Voltar ao catálogo</Link><Link href="/dashboard" className="orbit-button rounded-lg border border-neon-cyan/30 bg-neon-cyan/10 px-4 py-2 text-sm font-bold text-neon-cyan">Meu painel</Link></div></header>
    <main className="relative"><section className="border-b border-white/8 py-16 md:py-22"><div className="container max-w-5xl"><p className="inline-flex items-center gap-2 text-xs font-bold tracking-[0.18em] text-neon-cyan"><FileText className="h-4 w-4" /> TRANSPARÊNCIA EDITORIAL</p><h1 className="mt-5 max-w-4xl font-orbitron text-4xl font-black leading-[1.08] tracking-[-0.04em] sm:text-5xl">Política de conteúdo, fontes e licenças.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">A CyberDimension Academy usa o YouTube e outras referências como apoio. A experiência central continua sendo uma jornada didática própria: trilha, curso, módulo, aula, material, laboratório, quiz, progresso e certificado.</p></div></section>
      <section className="py-12"><div className="container max-w-5xl"><div className="grid gap-5 md:grid-cols-2">{standards.map(({ icon: Icon, title, text }) => <article key={title} className="module-card rounded-2xl p-6"><Icon className="h-6 w-6 text-neon-cyan" /><h2 className="mt-5 font-orbitron text-lg font-bold">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></article>)}</div></div></section>
      <section className="border-y border-neon-green/20 bg-neon-green/[0.04] py-12"><div className="container max-w-5xl"><div className="flex flex-col gap-5 md:flex-row md:items-start"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl border border-neon-green/30 bg-neon-green/10"><ShieldCheck className="h-6 w-6 text-neon-green" /></div><div><h2 className="font-orbitron text-xl font-bold">Como cada fonte é registrada</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Sempre que um conteúdo externo for indicado, a plataforma informa a fonte, a licença ou os termos disponibilizados pelo autor, o modo de uso e seu papel complementar. Um exemplo: <strong className="text-foreground">Fonte: YouTube — Canal identificado na formação. Licença: conforme disponibilizada pelo autor. Uso: vídeo incorporado via YouTube. Conteúdo complementar: material próprio da escola.</strong></p></div></div></div></section>
      <section className="py-14"><div className="container max-w-5xl"><h2 className="font-orbitron text-2xl font-bold">Compromissos da Academia</h2><div className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-white/10 bg-black/15 p-5"><p className="font-bold text-neon-cyan">Clareza</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Distinguir autoria própria e referência externa para que o aluno compreenda o papel de cada recurso.</p></article><article className="rounded-2xl border border-white/10 bg-black/15 p-5"><p className="font-bold text-neon-purple">Uso responsável</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Tratar recursos externos como complemento, respeitando limites de licença, escopo e finalidade educativa.</p></article><article className="rounded-2xl border border-white/10 bg-black/15 p-5"><p className="font-bold text-neon-green">Aprendizagem verificável</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Manter avaliações, laboratórios, progresso e certificados vinculados aos critérios próprios da plataforma.</p></article></div><Link href="/catalog" className="orbit-button mt-8 inline-flex items-center gap-2 rounded-lg border border-neon-cyan/30 bg-neon-cyan/10 px-5 py-3 text-sm font-bold text-neon-cyan">Explorar formações <ArrowLeft className="h-4 w-4 rotate-180" /></Link></div></section>
    </main>
  </div>;
}
