import { useAuth } from "@/_core/hooks/useAuth";
import { EmailAccessForm } from "@/components/EmailAccessForm";
import { Link } from "wouter";
import { ArrowRight, Shield, Sparkles, Zap } from "lucide-react";

export default function Login() {
  const { isAuthenticated, user } = useAuth();

  if (isAuthenticated && user) {
    return <div className="min-h-screen space-canvas text-foreground"><div className="pointer-events-none fixed inset-0 space-grid opacity-50" /><main className="container relative grid min-h-screen place-items-center py-8"><section className="module-card w-full max-w-lg rounded-3xl p-8 text-center md:p-10"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl border border-neon-green/25 bg-neon-green/10"><Shield className="h-8 w-8 text-neon-green" /></span><p className="mt-6 text-xs font-bold tracking-[0.16em] text-neon-green">SESSÃO ATIVA</p><h1 className="mt-3 font-orbitron text-2xl font-bold md:text-3xl">Bem-vindo de volta.</h1><Link href="/dashboard" className="orbit-button mt-7 inline-flex items-center gap-2 rounded-xl bg-neon-cyan px-5 py-3 font-bold text-[oklch(0.1_0.02_260)] hover:opacity-90">Abrir centro de comando <ArrowRight className="h-4 w-4" /></Link></section></main></div>;
  }

  return <div className="min-h-screen space-canvas text-foreground"><div className="pointer-events-none fixed inset-0 space-grid opacity-55" /><header className="relative z-10 border-b border-white/8 bg-[oklch(0.075_0.025_260/0.75)] backdrop-blur-xl"><div className="container flex items-center justify-between py-4"><Link href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-neon-cyan/30 bg-neon-cyan/10"><Shield className="h-4 w-4 text-neon-cyan" /></span><span><span className="block font-orbitron text-xs font-bold tracking-[0.06em]">CYBERDIMENSION</span><span className="mt-0.5 block text-[0.6rem] font-bold tracking-[0.2em] text-neon-cyan">ACADEMY</span></span></Link><Link href="/" className="text-sm font-bold text-muted-foreground hover:text-neon-cyan">Início</Link></div></header><main className="container relative grid min-h-[calc(100vh-4.5rem)] place-items-center py-10"><section className="module-card grid w-full max-w-4xl overflow-hidden rounded-3xl md:grid-cols-[1.05fr_0.95fr]"><div className="border-b border-white/10 bg-gradient-to-br from-neon-cyan/[0.10] via-transparent to-neon-purple/[0.10] p-7 md:border-b-0 md:border-r md:p-10"><p className="inline-flex items-center gap-2 text-xs font-bold tracking-[0.16em] text-neon-cyan"><Sparkles className="h-3.5 w-3.5" /> ENTRADA RÁPIDA</p><h1 className="mt-4 font-orbitron text-3xl font-bold leading-tight md:text-4xl">Entre na sua <span className="text-neon-cyan">estação</span> de estudo.</h1><p className="mt-5 max-w-sm text-sm leading-7 text-muted-foreground">Informe seu e-mail e entre imediatamente. Se esta for sua primeira visita, sua conta é criada na hora. A conta Manus não é necessária.</p></div><div className="p-7 md:p-10"><span className="grid h-12 w-12 place-items-center rounded-xl border border-neon-purple/25 bg-neon-purple/10"><Zap className="h-5 w-5 text-neon-purple" /></span><h2 className="mt-5 font-orbitron text-xl font-bold">Acesso por e-mail</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Sem senha e sem esperar mensagem: digite seu e-mail para continuar.</p><EmailAccessForm /><p className="mt-5 text-center text-sm text-muted-foreground">Primeira vez? <span className="font-bold text-neon-cyan">Use seu e-mail acima.</span></p></div></section></main></div>;
}
