import { useAuth } from "@/_core/hooks/useAuth";
import { useReadingPreferences } from "@/contexts/ReadingPreferencesContext";
import { getReadingPreferenceClasses } from "@/lib/readingPreferences";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, ClipboardCheck, ExternalLink, FlaskConical, FolderCheck, Linkedin, LockKeyhole, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

function shareEvidence(title: string) {
  const url = `${window.location.origin}/portfolio`;
  const shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}&summary=${encodeURIComponent(`Concluí a evidência prática "${title}" na CyberDimension Academy.`)}`;
  window.open(shareUrl, "_blank", "noopener,noreferrer");
}

export default function Portfolio() {
  const { user, isAuthenticated } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/login" });
  const { preferences } = useReadingPreferences();
  const evidenceQuery = trpc.portfolio.labEvidence.useQuery(undefined, { enabled: isAuthenticated });
  const evidence = evidenceQuery.data ?? [];

  if (!isAuthenticated || !user) return null;

  return <div className={`weekly-path-study reading-theme-transition min-h-screen space-canvas text-foreground ${getReadingPreferenceClasses(preferences)}`}>
    <div className="pointer-events-none fixed inset-0 space-grid opacity-55" />
    <header className="sticky top-0 z-30 border-b border-white/8 bg-[oklch(0.075_0.025_260/0.82)] backdrop-blur-xl"><div className="container flex items-center justify-between gap-3 py-3"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-bold text-muted-foreground hover:text-neon-cyan"><ArrowLeft className="h-4 w-4" /> Painel</Link><Link href="/" className="flex items-center gap-2" aria-label="CyberDimension Academy"><span className="grid h-8 w-8 place-items-center rounded-lg border border-neon-cyan/35 bg-neon-cyan/10"><ShieldCheck className="h-4 w-4 text-neon-cyan" /></span><span className="font-orbitron text-xs font-bold sm:text-sm">CYBER<span className="text-neon-purple">DIMENSION</span></span></Link></div></header>
    <main className="container relative py-7 md:py-10">
      <section className="relative overflow-hidden rounded-3xl border border-neon-green/25 bg-[linear-gradient(135deg,oklch(0.12_0.05_260/0.96),oklch(0.09_0.025_270/0.9))] p-6 md:p-9"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-neon-green/14 blur-3xl" /><div className="relative grid gap-7 lg:grid-cols-[1.25fr_0.75fr] lg:items-end"><div><p className="inline-flex items-center gap-2 rounded-full border border-neon-green/30 bg-neon-green/10 px-3 py-1 text-[0.65rem] font-bold tracking-[0.16em] text-neon-green"><FolderCheck className="h-3.5 w-3.5" /> PORTFÓLIO PRÁTICO</p><h1 className="mt-4 font-orbitron text-3xl font-black tracking-[-0.04em] md:text-5xl">Evidências que <span className="text-neon-green">mostram prática.</span></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground md:text-base">Reúna os laboratórios que você concluiu e validou na plataforma. Cada item registra a prática educativa, o contexto e a data de validação — sem expor comandos, respostas ou dados sensíveis.</p></div><aside className="module-card rounded-2xl border border-white/12 p-5"><ClipboardCheck className="h-5 w-5 text-neon-cyan" /><p className="mt-3 font-orbitron text-4xl font-bold">{evidence.length}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">evidências práticas verificadas em seu histórico de aprendizagem.</p></aside></div></section>

      <section className="mt-7 flex items-start gap-3 rounded-2xl border border-white/10 bg-white/[0.035] p-4 text-sm leading-6 text-muted-foreground"><LockKeyhole className="mt-0.5 h-5 w-5 shrink-0 text-neon-cyan" /><p>Seu portfólio é privado por padrão. Ao compartilhar, revise o texto na rede escolhida e publique somente informações que façam sentido para o seu contexto profissional.</p></section>

      {evidenceQuery.isLoading && <section className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 3 }).map((_, index) => <div key={index} className="h-64 animate-pulse rounded-2xl border border-white/8 bg-white/[0.035]" />)}</section>}
      {!evidenceQuery.isLoading && evidence.length === 0 && <section className="mt-8 rounded-3xl border border-dashed border-white/18 bg-white/[0.025] px-6 py-12 text-center"><FlaskConical className="mx-auto h-9 w-9 text-neon-cyan" /><h2 className="mt-5 font-orbitron text-xl font-bold">Seu primeiro projeto começa em um laboratório.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-muted-foreground">Conclua uma missão prática guiada e valide a evidência para que ela apareça aqui. Os laboratórios usam cenários educativos e resultados sintéticos.</p><Link href="/catalog" className="orbit-button mt-6 inline-flex items-center gap-2 rounded-xl bg-neon-cyan px-4 py-3 text-sm font-bold text-[oklch(0.1_0.02_260)]">Explorar laboratórios <ArrowRight className="h-4 w-4" /></Link></section>}
      {evidence.length > 0 && <section className="mt-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[0.16em] text-neon-cyan">EVIDÊNCIAS VALIDADAS</p><h2 className="mt-2 font-orbitron text-2xl font-bold">Seu histórico de prática segura.</h2></div><p className="text-sm text-muted-foreground">Ordenado pela validação mais recente.</p></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{evidence.map((item) => <article key={item.id} className="module-card flex min-h-[290px] flex-col rounded-2xl border border-white/12 p-5"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl border border-neon-green/30 bg-neon-green/10 text-neon-green"><FlaskConical className="h-5 w-5" /></span><span className="rounded-full bg-neon-green/10 px-2.5 py-1 text-[0.65rem] font-bold tracking-[0.12em] text-neon-green">VALIDADO</span></div><p className="mt-5 text-xs font-bold tracking-[0.14em] text-neon-cyan">{item.courseTitle.toUpperCase()}</p><h3 className="mt-2 font-orbitron text-lg font-bold">{item.labTitle}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{item.objective}</p><p className="mt-4 text-xs text-muted-foreground">Validado em {new Date(item.verifiedAt).toLocaleDateString("pt-BR", { day: "2-digit", month: "long", year: "numeric" })}</p><div className="mt-auto flex flex-wrap gap-3 pt-5"><Link href={`/formacao/${item.courseSlug}/estudar`} className="inline-flex items-center gap-1 text-xs font-bold text-neon-cyan hover:underline">Rever formação <ArrowRight className="h-3.5 w-3.5" /></Link><button type="button" onClick={() => shareEvidence(item.labTitle)} className="inline-flex items-center gap-1 text-xs font-bold text-neon-green hover:underline"><Linkedin className="h-3.5 w-3.5" /> Compartilhar</button></div></article>)}</div></section>}
      {evidence.length > 0 && <section className="mt-8 rounded-2xl border border-neon-purple/20 bg-neon-purple/[0.06] p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold tracking-[0.16em] text-neon-purple">PRÓXIMA EVIDÊNCIA</p><h2 className="mt-2 font-orbitron text-lg font-bold">Dê contexto técnico à sua jornada.</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Combine laboratórios concluídos com simulados por especialidade para orientar suas próximas etapas de prática.</p></div><Link href="/simulados" className="orbit-button inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-neon-purple/35 bg-neon-purple/10 px-4 py-3 text-sm font-bold text-neon-purple">Abrir simulados <ExternalLink className="h-4 w-4" /></Link></div></section>}
    </main>
  </div>;
}
