/**
 * Termos de vocabulário técnico em inglês usados nos episódios especiais
 * "English for Cyber Pros" e "English for Network Security".
 * Cada termo pode ser marcado como favorito na transcrição e revisado
 * depois em uma lista pessoal de estudo.
 */

export interface EnglishTerm {
  id: string;
  term: string;
  phonetic: string;
  meaning: string;
  exampleEn: string;
  examplePt: string;
  sourceEpisodes: readonly string[];
}

export const englishVocabulary: readonly EnglishTerm[] = [
  {
    id: "term-phishing",
    term: "phishing",
    phonetic: "FÍ-xing",
    meaning: "Engenharia social que se passa por entidade confiável para roubar dados.",
    exampleEn: "The employee clicked a phishing link and exposed her credentials.",
    examplePt: "A funcionária clicou em um link de phishing e expôs suas credenciais.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-ransomware",
    term: "ransomware",
    phonetic: "RÂN-som-wer",
    meaning: "Malware que criptografa dados e exige resgate para liberá-los.",
    exampleEn: "The ransomware encrypted the file server at two AM.",
    examplePt: "O ransomware criptografou o servidor de arquivos às duas da manhã.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-vulnerability",
    term: "vulnerability",
    phonetic: "vâr-nê-rá-bi-li-ti",
    meaning: "Falha que pode ser explorada para comprometer um sistema.",
    exampleEn: "We patched the critical vulnerability before it was exploited.",
    examplePt: "Corrigimos a vulnerabilidade crítica antes que fosse explorada.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-threat",
    term: "threat",
    phonetic: "thrêt",
    meaning: "Ameaça: agente ou evento com potencial de causar dano.",
    exampleEn: "The IDS detected a threat coming from an external IP.",
    examplePt: "O IDS detectou uma ameaça vindo de um IP externo.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-breach",
    term: "breach",
    phonetic: "bríitch",
    meaning: "Violação: acesso não autorizado a dados ou sistemas.",
    exampleEn: "The company reported a data breach affecting thousands of users.",
    examplePt: "A empresa reportou uma violação de dados que afetou milhares de usuários.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-leaked",
    term: "leaked",
    phonetic: "líikt",
    meaning: "Vazado: informações expostas publicamente sem autorização.",
    exampleEn: "The leaked credentials appeared on a public paste site.",
    examplePt: "As credenciais vazadas apareceram em um site público de pastes.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-mitigation",
    term: "mitigation",
    phonetic: "mi-ti-gêi-xân",
    meaning: "Mitigação: ações que reduzem a probabilidade ou o impacto de um risco.",
    exampleEn: "Network segmentation is a key mitigation against lateral movement.",
    examplePt: "A segmentação de rede é uma mitigação essencial contra o movimento lateral.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-triage",
    term: "triage",
    phonetic: "tri-ÁJ",
    meaning: "Triagem: classificação de alertas por severidade para priorizar ação.",
    exampleEn: "I triage the alerts by severity before escalating them.",
    examplePt: "Eu classifico os alertas por severidade antes de escaloná-los.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-escalate",
    term: "escalate",
    phonetic: "és-ka-leit",
    meaning: "Escalar: levar um incidente a um nível superior de responsabilidade.",
    exampleEn: "Confirmed incidents are escalated to the senior analyst.",
    examplePt: "Incidentes confirmados são escalados para o analista sênior.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-contain",
    term: "contain",
    phonetic: "con-TÊIN",
    meaning: "Conter: limitar o alcance de um incidente antes da erradicação.",
    exampleEn: "We contained the threat by isolating the affected machines.",
    examplePt: "Contivemos a ameaça isolando as máquinas afetadas.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-compromise",
    term: "compromise",
    phonetic: "câm-pro-maiz",
    meaning: "Comprometer: quando um ativo foi invadido ou corrompido.",
    exampleEn: "Two accounts were compromised in the brute force attack.",
    examplePt: "Duas contas foram comprometidas no ataque de força bruta.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-forensic",
    term: "forensic",
    phonetic: "for-RÊN-sic",
    meaning: "Forense: análise de evidências digitais com rigor probatório.",
    exampleEn: "The forensic team preserved the disk image as evidence.",
    examplePt: "A equipe forense preservou a imagem do disco como evidência.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-compliance",
    term: "compliance",
    phonetic: "com-PLÁI-ans",
    meaning: "Conformidade: aderência a normas, políticas e regulamentos.",
    exampleEn: "The audit checked our compliance with the security policy.",
    examplePt: "A auditoria verificou nossa conformidade com a política de segurança.",
    sourceEpisodes: ["ep68-english-for-cyber-pros"],
  },
  {
    id: "term-encrypt",
    term: "encrypt",
    phonetic: "in-CHRÍPT",
    meaning: "Criptografar: transformar dados em formato ilegível sem a chave.",
    exampleEn: "All VPN sessions are encrypted end to end.",
    examplePt: "Todas as sessões de VPN são criptografadas de ponta a ponta.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-inspect",
    term: "inspect",
    phonetic: "in-SPÉCT",
    meaning: "Inspecionar: examinar pacotes ou tráfego em busca de ameaças.",
    exampleEn: "A stateful firewall inspects packets and tracks connections.",
    examplePt: "Um firewall stateful inspeciona pacotes e rastreia as conexões.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-enforce",
    term: "enforce",
    phonetic: "in-FÓRSE",
    meaning: "Fazer cumprir: aplicar políticas de segurança de forma ativa.",
    exampleEn: "Microsegmentation enforces policies between workloads.",
    examplePt: "A microsegmentação faz cumprir as políticas entre workloads.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-segment",
    term: "segment",
    phonetic: "SÉG-ment",
    meaning: "Segmentar: dividir a rede em zonas menores e isoladas.",
    exampleEn: "Network segmentation divides a large network into smaller zones.",
    examplePt: "A segmentação de rede divide uma rede grande em zonas menores.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-lateral-movement",
    term: "lateral movement",
    phonetic: "LÉ-tê-râl MÚV-ment",
    meaning: "Movimento lateral: deslocamento do atacante entre sistemas da rede.",
    exampleEn: "Segmentation limits lateral movement across the network.",
    examplePt: "A segmentação limita o movimento lateral pela rede.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-pivot",
    term: "pivot",
    phonetic: "PÍ-vot",
    meaning: "Pivotar: usar um sistema comprometido para atacar outros.",
    exampleEn: "Without segmentation, an attacker can pivot to the whole network.",
    examplePt: "Sem segmentação, o atacante pode pivotar para toda a rede.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-baseline",
    term: "baseline",
    phonetic: "BÊIS-lein",
    meaning: "Linha de base: comportamento normal de tráfego usado para detectar anomalias.",
    exampleEn: "We compared the traffic against our baseline and found an anomaly.",
    examplePt: "Comparamos o tráfego com a linha de base e encontramos uma anomalia.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-packet-capture",
    term: "packet capture",
    phonetic: "PÉ-ket KÁP-châr",
    meaning: "Captura de pacotes: gravação do tráfego de rede para análise forense.",
    exampleEn: "The packet capture showed the exfiltration attempt.",
    examplePt: "A captura de pacotes mostrou a tentativa de exfiltração.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-rate-limiting",
    term: "rate limiting",
    phonetic: "RÊIT LÍ-mi-ting",
    meaning: "Limite de taxa: controle que bloqueia tráfego acima de um volume definido.",
    exampleEn: "Rate limiting on the edge reduced the DDoS impact.",
    examplePt: "O rate limiting na borda reduziu o impacto do DDoS.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-vpn",
    term: "VPN",
    phonetic: "vi-pi-en",
    meaning: "Rede privada virtual: túnel criptografado sobre rede não confiável.",
    exampleEn: "Remote users connect through an encrypted VPN tunnel.",
    examplePt: "Usuários remotos conectam por um túnel VPN criptografado.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-ddos",
    term: "DDoS mitigation",
    phonetic: "di-di-ÓU-és mi-ti-GÊI-xân",
    meaning: "Mitigação de DDoS: conjunto de ações para absorver ataques de negação de serviço.",
    exampleEn: "We activated DDoS mitigation with our CDN provider.",
    examplePt: "Acionamos a mitigação de DDoS com nosso provedor de CDN.",
    sourceEpisodes: ["ep69-network-security-interview"],
  },
  {
    id: "term-shared-responsibility",
    term: "shared responsibility",
    phonetic: "XÉR-red ri-spôn-sa-BÍ-li-ti",
    meaning: "Responsabilidade compartilhada: o provedor protege a nuvem, o cliente protege o que coloca nela.",
    exampleEn: "The provider handles security of the cloud; we handle security in the cloud.",
    examplePt: "O provedor cuida da segurança da nuvem; nós cuidamos da segurança na nuvem.",
    sourceEpisodes: ["ep70-cloud-security-interview"],
  },
  {
    id: "term-iam",
    term: "IAM",
    phonetic: "ai-ei-ÉM",
    meaning: "Gerenciamento de identidades e acessos: quem pode acessar o quê.",
    exampleEn: "We enforce least privilege through IAM policies.",
    examplePt: "Fazemos cumprir o privilégio mínimo com políticas de IAM.",
    sourceEpisodes: ["ep70-cloud-security-interview"],
  },
  {
    id: "term-kms",
    term: "KMS",
    phonetic: "kei-em-ÉS",
    meaning: "Gerenciamento de chaves de criptografia usadas para proteger dados.",
    exampleEn: "All data at rest is encrypted with KMS keys.",
    examplePt: "Todos os dados em repouso são criptografados com chaves do KMS.",
    sourceEpisodes: ["ep70-cloud-security-interview"],
  },
  {
    id: "term-misconfiguration",
    term: "misconfiguration",
    phonetic: "miç-con-fi-gi-u-RÊI-xân",
    meaning: "Configuração incorreta: principal causa de vazamentos em nuvem.",
    exampleEn: "An S3 bucket misconfiguration exposed customer data.",
    examplePt: "Uma má configuração de bucket S3 expôs dados de clientes.",
    sourceEpisodes: ["ep70-cloud-security-interview"],
  },
  {
    id: "term-containment",
    term: "containment",
    phonetic: "con-TÊIN-ment",
    meaning: "Contenção: primeira resposta para limitar o alcance de um incidente.",
    exampleEn: "Isolation was the fastest containment action for the ransomware.",
    examplePt: "O isolamento foi a ação de contenção mais rápida para o ransomware.",
    sourceEpisodes: ["ep70-cloud-security-interview", "ep71-incident-response-interview"],
  },
  {
    id: "term-eradicate",
    term: "eradicate",
    phonetic: "i-RÉ-di-keit",
    meaning: "Erradicar: eliminar completamente a ameaça do ambiente.",
    exampleEn: "We eradicated the malware after capturing the evidence.",
    examplePt: "Eliminamos o malware depois de capturar as evidências.",
    sourceEpisodes: ["ep71-incident-response-interview"],
  },
  {
    id: "term-chain-of-custody",
    term: "chain of custody",
    phonetic: "TCHÊIN-of-CÂS-to-di",
    meaning: "Cadeia de custódia: registro de quem manuseou cada evidência.",
    exampleEn: "The chain of custody must remain unbroken for the evidence to be valid.",
    examplePt: "A cadeia de custódia deve permanecer intacta para a evidência ser válida.",
    sourceEpisodes: ["ep71-incident-response-interview"],
  },
  {
    id: "term-forensic-image",
    term: "forensic image",
    phonetic: "for-RÊN-sic Í-mêdj",
    meaning: "Imagem forense: cópia bit a bit de um disco preservando evidências.",
    exampleEn: "We created a bit-for-bit forensic image using a write blocker.",
    examplePt: "Criamos uma imagem forense bit a bit usando um bloqueador de escrita.",
    sourceEpisodes: ["ep71-incident-response-interview"],
  },
  {
    id: "term-write-blocker",
    term: "write blocker",
    phonetic: "RÁIT BLÔ-quer",
    meaning: "Bloqueador de escrita: dispositivo que impede alteração da evidência original.",
    exampleEn: "The write blocker guarantees the disk is never modified.",
    examplePt: "O bloqueador de escrita garante que o disco nunca seja modificado.",
    sourceEpisodes: ["ep71-incident-response-interview"],
  },
  {
    id: "term-volatile-memory",
    term: "volatile memory",
    phonetic: "VÔ-la-tail MÉ-mo-ri",
    meaning: "Memória volátil: dados que desaparecem ao desligar a máquina.",
    exampleEn: "Volatile memory is captured first because it disappears at shutdown.",
    examplePt: "A memória volátil é capturada primeiro porque desaparece ao desligar.",
    sourceEpisodes: ["ep71-incident-response-interview"],
  },
  {
    id: "term-persistence",
    term: "persistence",
    phonetic: "pâr-SÍS-tens",
    meaning: "Persistência: capacidade do malware de sobreviver a reinicializações.",
    exampleEn: "The attacker established persistence through a scheduled task.",
    examplePt: "O atacante estabeleceu persistência por meio de uma tarefa agendada.",
    sourceEpisodes: ["ep71-incident-response-interview"],
  },
  {
    id: "term-ioc",
    term: "indicator of compromise",
    phonetic: "ÍN-di-kei-târ of CÂM-pro-maiz",
    meaning: "Indicador de compromisso: evidência técnica de uma invasão (hash, IP, domínio).",
    exampleEn: "The file hash was added to our indicator of compromise list.",
    examplePt: "O hash do arquivo foi adicionado à nossa lista de indicadores de compromisso.",
    sourceEpisodes: ["ep71-incident-response-interview"],
  },
  {
    id: "term-root-cause",
    term: "root cause",
    phonetic: "RÚT CÔZ",
    meaning: "Causa raiz: origem real de um incidente que precisa ser eliminada.",
    exampleEn: "The root cause was an unpatched VPN appliance.",
    examplePt: "A causa raiz era um appliance VPN sem correção de segurança.",
    sourceEpisodes: ["ep71-incident-response-interview"],
  },
  {
    id: "term-reconnaissance",
    term: "reconnaissance",
    phonetic: "ri-CÓ-nei-sans",
    meaning: "Reconhecimento: coleta de informações sobre o alvo antes do teste.",
    exampleEn: "Reconnaissance can be passive or active depending on the footprint left.",
    examplePt: "O reconhecimento pode ser passivo ou ativo, dependendo do rastro deixado.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-enumeration",
    term: "enumeration",
    phonetic: "i-niú-mê-rêi-xân",
    meaning: "Enumeração: extração ativa de informações detalhadas de serviços e hosts.",
    exampleEn: "Service enumeration revealed an outdated SMB version.",
    examplePt: "A enumeração de serviços revelou uma versão antiga do SMB.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-exploit",
    term: "exploit",
    phonetic: "écs-ploit",
    meaning: "Explorar: aproveitar uma vulnerabilidade para ganhar acesso.",
    exampleEn: "We exploited the unauthenticated RCE to reach the internal network.",
    examplePt: "Exploramos o RCE não autenticado para alcançar a rede interna.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-privilege-escalation",
    term: "privilege escalation",
    phonetic: "pri-vi-lij és-ka-lêi-xân",
    meaning: "Escalação de privilégios: subir de acesso de usuário comum para administrativo.",
    exampleEn: "The privilege escalation took us from a low-privileged shell to SYSTEM.",
    examplePt: "A escalação de privilégios nos levou de um shell limitado ao SYSTEM.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-credential-dumping",
    term: "credential dumping",
    phonetic: "cri-DÊN-xial DÂM-ping",
    meaning: "Despejo de credenciais: extração de senhas e hashes da memória ou do disco.",
    exampleEn: "Credential dumping from the SAM database gave us the admin hash.",
    examplePt: "O despejo de credenciais do SAM nos deu o hash do administrador.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-pass-the-hash",
    term: "pass the hash",
    phonetic: "pés-dá-RÃX",
    meaning: "Passar o hash: autenticar usando o hash da senha sem decifrá-la.",
    exampleEn: "We used pass the hash to authenticate to the domain controller.",
    examplePt: "Usamos pass the hash para autenticar no controlador de domínio.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-persistence",
    term: "persistence",
    phonetic: "pâr-SÍS-tens",
    meaning: "Persistência: capacidade do malware de sobreviver a reinicializações.",
    exampleEn: "The attacker established persistence through a scheduled task.",
    examplePt: "O atacante estabeleceu persistência por meio de uma tarefa agendada.",
    sourceEpisodes: ["ep71-incident-response-interview", "ep72-penetration-testing-interview"],
  },
  {
    id: "term-cvss",
    term: "CVSS",
    phonetic: "si-vi-és-ÉS",
    meaning: "Sistema de pontuação de severidade de vulnerabilidades (0 a 10).",
    exampleEn: "The vulnerability scored nine point eight on CVSS.",
    examplePt: "A vulnerabilidade pontuou nove vírgula oito no CVSS.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-remediation",
    term: "remediation",
    phonetic: "ri-mi-di-ÊI-xân",
    meaning: "Remediação: correção definitiva de uma vulnerabilidade ou falha.",
    exampleEn: "We provided mitigation guidance while planning the remediation window.",
    examplePt: "Fornecemos orientação de mitigação enquanto planejávamos a janela de correção.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-proof-of-concept",
    term: "proof of concept",
    phonetic: "prúf-of-CÂN-sept",
    meaning: "Prova de conceito: demonstração prática e segura da exploração de uma falha.",
    exampleEn: "The proof of concept shows the vulnerability without destructive payloads.",
    examplePt: "A prova de conceito demonstra a vulnerabilidade sem payloads destrutivos.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
  {
    id: "term-rules-of-engagement",
    term: "rules of engagement",
    phonetic: "RÚLS-of-in-GÊIJ-ment",
    meaning: "Regras de engajamento: acordo escrito de escopo, métodos e limites do teste.",
    exampleEn: "Rules of engagement are signed before any testing begins.",
    examplePt: "As regras de engajamento são assinadas antes do início de qualquer teste.",
    sourceEpisodes: ["ep72-penetration-testing-interview"],
  },
];

export const getEnglishTerm = (termId: string) => englishVocabulary.find((term) => term.id === termId);

export const getTermsByEpisode = (episodeId: string) =>
  englishVocabulary.filter((term) => term.sourceEpisodes.includes(episodeId));
