import type { PodcastEpisode } from "./podcastEpisodes";
import type { ContentProvenanceItem } from "./contentProvenance";

const fullSeriesProvenance = (id: string, title: string): ContentProvenanceItem => ({
  id: `podcast-${id}`,
  origin: "proprio",
  category: "Podcast educacional próprio",
  title,
  source: "CyberDimension Academy",
  license: "Conteúdo autoral da CyberDimension Academy; uso de estudo dentro da plataforma.",
  usage: "Diálogo autoral em áudio e transcrição acessível de aprofundamento da CompTIA Security+ SY0-701.",
});

export const podcastFullSeriesEpisodes: readonly PodcastEpisode[] = [
  {
    audioUrl: "/manus-storage/ep11-controles-seguranca_04bac2c0.wav",
    id: "ep11-security-controls-deep",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 11,
    title: "Aprofundamento: como escolher, aplicar e avaliar controles",
    description: "Ana e Rafael exploram categorias, tipos e a lógica de seleção e avaliação de controles, incluindo compensatórios, para decisões seguras de prova.",
    duration: "~6 min",

    topics: ["controles preventivos, detetivos e corretivos", "categorias técnica, administrativa e física", "seleção e avaliação de controles", "controle compensatório", "eficácia e limitações"],
    examWeight: "12% do exame",
    provenance: fullSeriesProvenance("ep11-security-controls-deep", "CyberCast 11 — Aprofundamento: como escolher, aplicar e avaliar controles"),
    transcript: [
      { speaker: "Ana", text: "No primeiro domínio, a prova quer que você pense em controle como decisão, não como lista de produtos. Vamos começar pela estrutura: todo controle pertence a uma categoria, que diz como ele atua, e a um tipo, que diz por qual meio ele opera." },
      { speaker: "Rafael", text: "As categorias que estudo são preventiva, detetiva, corretiva, dissuasiva, compensatória e física. Preventiva evita o evento, detetiva o identifica em andamento, corretiva reage para restaurar o estado desejado, dissuasiva desencoraja pelo custo percebido do ataque e compensatória cobre o espaço deixado por outro controle." },
      { speaker: "Ana", text: "E os tipos são técnico, administrativo e físico. O firewall é técnico, a política de acesso é administrativa e o cartão de portaria é físico. A prova mistura os dois eixos: um mesmo recurso pode ser preventivo e técnico, como uma trava de sessão, ou detetivo e administrativo, como uma auditoria de contas." },
      { speaker: "Rafael", text: "Na hora de escolher, eu começo pelo problema. Se a questão pede reduzir a chance de o evento acontecer, o verbo é prevenir. Se pede saber rapidamente que algo ocorreu, o foco é detectar. E se pede voltar ao normal, é corrigir." },
      { speaker: "Ana", text: "Exatamente. E aqui entra a avaliação de eficácia: nenhum controle é perfeito, então a resposta madura sempre considera custo, impacto na operação, manutenibilidade e a ameaça que ele enfrenta. Um controle caro que ninguém opera vira controle fraco na prática." },
      { speaker: "Rafael", text: "E quando o controle ideal não está disponível, como um sistema legado sem MFA, eu seleciono um compensatório que reduza a exposição de outra forma, documentando risco, responsável e prazo de revisão." },
      { speaker: "Ana", text: "Correto. A defesa em profundidade é a soma desses controles que não dependem de uma única linha. Se uma falha, outra segura. Por isso a prova raramente aceita respostas que dependem de uma única tecnologia milagrosa: segurança é arquitetura de camadas." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep12-criptografia-pki_7a794d5d.wav",
    id: "ep12-cryptography-pki-deep",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 12,
    title: "Aprofundamento: criptografia, hashing e o ciclo de vida da PKI",
    description: "Um diálogo técnico sobre proteção de dados, verificação de integridade e a confiança que sustenta certificados, assinaturas e revogação.",
    duration: "~6 min",

    topics: ["criptografia simétrica e assimétrica", "hashing", "assinatura digital", "certificados e autoridade certificadora", "revogação", "gestão de chaves"],
    examWeight: "12% do exame",
    provenance: fullSeriesProvenance("ep12-cryptography-pki-deep", "CyberCast 12 — Aprofundamento: criptografia, hashing e o ciclo de vida da PKI"),
    transcript: [
      { speaker: "Ana", text: "Criptografia protege a confidencialidade, hash protege a integridade e assinatura digital conecta as duas com autenticidade. Essas três frases resolvem metade das questões do tema." },
      { speaker: "Rafael", text: "E a diferença prática entre simétrica e assimétrica: na simétrica, a mesma chave cifra e decifra, então o desafio é distribuir a chave com segurança. Na assimétrica, há um par, a chave privada fica sempre secreta e a pública é compartilhada." },
      { speaker: "Ana", text: "No uso típico da prova, o cenário combina as duas: a assimétrica troca em segurança uma chave simétrica de sessão, que depois protege o volume de dados, por ser mais rápida. É assim que o TLS funciona." },
      { speaker: "Rafael", text: "O hash é outro mecanismo: função unidirecional que gera um resumo fixo do dado. Se o arquivo muda um bit, o hash muda. Por isso ele serve para verificar integridade de downloads, senhas armazenadas e evidências forenses. Mas hash não é criptografia: não protege sigilo." },
      { speaker: "Ana", text: "E a assinatura digital? Descreva o processo." },
      { speaker: "Rafael", text: "O signatário calcula o hash do documento e cifra esse hash com a própria chave privada. Quem recebe verifica com a chave pública: se bater, a mensagem é autêntica, íntegra e tem não repúdio." },
      { speaker: "Ana", text: "Agora a confiança: um certificado digital vincula uma identidade a uma chave pública, e quem emite essa confiança é a autoridade certificadora, com um ciclo de vida completo: emissão, distribuição, uso, renovação, revogação e destruição." },
      { speaker: "Rafael", text: "Se a chave privada é comprometida, o certificado precisa ser revogado, conferindo listas como CRL ou o protocolo OCSP em vez de confiar apenas na data de validade." },
      { speaker: "Ana", text: "Isso. E duas pegadinhas clássicas: a chave privada assina e nunca sai de posse do dono; a chave pública verifica. Se a questão trocar os papéis, está errada. E gestão de chaves, do armazenamento seguro à rotação, é tão importante quanto o algoritmo." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep13-identidade-acesso_f601c4de.wav",
    id: "ep13-identity-access-deep",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 13,
    title: "Aprofundamento: identidade, autenticação e modelos de acesso",
    description: "Ana e Rafael detalham AAA, multifator, SSO, federação e os modelos de controle de acesso que a prova testa com cenários de permissão.",
    duration: "~6 min",

    topics: ["AAA", "autenticação multifator", "SSO e federação", "RBAC, ABAC e MAC", "menor privilégio", "gestão de contas"],
    examWeight: "12% do exame",
    provenance: fullSeriesProvenance("ep13-identity-access-deep", "CyberCast 13 — Aprofundamento: identidade, autenticação e modelos de acesso"),
    transcript: [
      { speaker: "Ana", text: "Identidade é o novo perímetro. Vamos destrinchar o AAA: autenticação prova quem você é, autorização define o que você pode fazer e accounting registra o que você fez. São três verbos distintos que a prova adora confundir." },
      { speaker: "Rafael", text: "Na autenticação, o MFA exige mais de uma categoria de evidência: algo que você sabe, como a senha, algo que você tem, como o autenticador, e algo que você é, como a biometria. Duas senhas não contam como MFA, pois são a mesma categoria." },
      { speaker: "Ana", text: "E quando o usuário acessa muitos sistemas sem redigitar credenciais, é SSO, com um provedor de identidade. Quando a confiança atravessa organizações, com asserções como SAML, chamamos de federação." },
      { speaker: "Rafael", text: "Nos modelos de autorização, RBAC organiza permissões por função, que reflete cargo. ABAC avalia atributos como horário, localização, classificação do dado e postura do dispositivo. E o MAC classifica por sensibilidade: rótulos de segurança decidem, não o usuário." },
      { speaker: "Ana", text: "Qual modelo escolher na prova? Se o enunciado fala de cargo e estrutura hierárquica, RBAC. Se menciona contexto dinâmico e classificação, ABAC. Se menciona sigilo militar ou rótulos obrigatórios, MAC." },
      { speaker: "Rafael", text: "E independente do modelo, a régua é menor privilégio: conceder o mínimo necessário, revisar com frequência, remover acesso de quem saiu e separar funções que, juntas, permitiriam fraude." },
      { speaker: "Ana", text: "Na gestão do ciclo de vida, a prova valoriza processos claros de criação, aprovação, modificação e desativação de contas. Contas órfãs, sem revisão, são uma das brechas mais cobradas. E privilégios administrativos merecem monitoramento reforçado, porque são o alvo preferido de ataques internos e externos." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep14-atores-ameaca_5e0ac46f.wav",
    id: "ep14-threat-actors-tactics",
    domainCode: "DOM2",
    domainTitle: "Threats & Vulnerabilities",
    episodeNumber: 14,
    title: "Aprofundamento: quem ataca, por quê e por quais caminhos",
    description: "Um diálogo sobre atores de ameaça, motivações e vetores de ataque, incluindo a engenharia social como vetor mais cobrado da prova.",
    duration: "~6 min",

    topics: ["atores de ameaça", "motivações", "engenharia social", "phishing", "vetores de rede e físicos", "insider"],
    examWeight: "22% do exame",
    provenance: fullSeriesProvenance("ep14-threat-actors-tactics", "CyberCast 14 — Aprofundamento: quem ataca, por quê e por quais caminhos"),
    transcript: [
      { speaker: "Ana", text: "No domínio dois, a prova pede que você classifique o ator antes de classificar o ataque. Por quê? Porque a motivação explica o método. O ator certo leva à resposta certa." },
      { speaker: "Rafael", text: "Nos meus resumos, os principais atores são: criminosos organizados, motivados por lucro; ativistas, motivados por ideologia; patrocinados por Estados-nação, com recursos e paciência para espionagem; terroristas, buscando dano e caos; e concorrentes ou insiders maliciosos, que já têm acesso interno." },
      { speaker: "Ana", text: "Perceba a diferença de perfil: o criminoso quer retorno rápido, então prefere ransomware e fraude. O Estado-nação quer acesso persistente, então investe em ameaça persistente avançada, a chamada APT. O insider não precisa vencer firewall: ele já está dentro." },
      { speaker: "Rafael", text: "E o vetor mais cobrado é a engenharia social: induzir pessoas a agir contra o próprio interesse. As formas são phishing em massa, spear-phishing direcionado a uma pessoa ou grupo e whaling contra executivos. E ainda vishing por voz e smishing por mensagem." },
      { speaker: "Ana", text: "Qual defesa resolve melhor? Controles técnicos, como filtro de e-mail e MFA resistente a phishing, somados a treinamento contextual. Mas atenção: se a questão pergunta pela causa raiz, a resposta não é culpar a pessoa, e sim reduzir a superfície de indução." },
      { speaker: "Rafael", text: "Os vetores técnicos incluem ataques de rede como varredura e força bruta, exploração de vulnerabilidade, ataques a aplicações como injeção, e vetores físicos como tailgating, shoulder surfing e mídia removível deixada em local acessível." },
      { speaker: "Ana", text: "Excelente. E feche sempre com mitigação proporcional: reconheça o vetor descrito, a motivação provável do ator e a camada de defesa mais adequada. Essa tríade ator, vetor, mitigação é o mapa completo do domínio." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep15-vulnerabilidades_86612229.wav",
    id: "ep15-vulnerabilities-mitigation",
    domainCode: "DOM2",
    domainTitle: "Threats & Vulnerabilities",
    episodeNumber: 15,
    title: "Aprofundamento: vulnerabilidades, indicadores e mitigação prioritizada",
    description: "Ana e Rafael detalham tipos de vulnerabilidade, indicadores de atividade maliciosa e o raciocínio de priorização e mitigação que a prova exige.",
    duration: "~6 min",

    topics: ["tipos de vulnerabilidade", "varredura e exposição", "IOCs e TTPs", "priorização de risco", "mitigação técnica e organizacional", "desenvolvimento seguro"],
    examWeight: "22% do exame",
    provenance: fullSeriesProvenance("ep15-vulnerabilities-mitigation", "CyberCast 15 — Aprofundamento: vulnerabilidades, indicadores e mitigação prioritizada"),
    transcript: [
      { speaker: "Ana", text: "Vulnerabilidade é a falha, exposição é a condição que a torna atingível e ameaça é quem ou o que a explora. Separe os três antes de responder qualquer questão do domínio." },
      { speaker: "Rafael", text: "Nas varreduras, a diferença que mais cai: vulnerabilidade é o defeito corrigível, configuração incorreta é ajuste de parâmetro e exposição é a abertura que permite acesso, como uma porta não necessária aberta para a internet." },
      { speaker: "Ana", text: "E a severidade do scanner não é o risco final. Como você prioriza?" },
      { speaker: "Rafael", text: "Pela combinação de criticidade técnica, valor do ativo afetado, acessibilidade do vetor, evidência de exploração ativa no campo e impacto de negócio. Um crítico em servidor desativado pesa menos que um médio em gateway exposto." },
      { speaker: "Ana", text: "Correto. E a mitigação nem sempre é patch: pode ser compensar com controles, segmentar, monitorar ou aceitar o risco documentado. A prova valoriza a resposta que resolve a causa mais próxima, como parametrizar consulta contra injeção, em vez de mascarar o problema com um filtro na borda." },
      { speaker: "Rafael", text: "Nos indicadores de atividade maliciosa, eu organizo em três grupos: recursos do host, como alta taxa de conexões e processos desconhecidos; recursos de rede, como tráfego em portas incomuns, domínios recém-criados e padrões de DNS suspeitos; e pessoas, como acessos fora do horário e movimentação incomum de dados." },
      { speaker: "Ana", text: "E no desenvolvimento seguro, os princípios que mais aparecem: validação de entrada no servidor, tratamento mínimo de privilégios na aplicação, gestão segura de segredos e o ciclo de correção que inclui revogação de credenciais expostas, não apenas remoção do arquivo." },
      { speaker: "Rafael", text: "Então a fórmula do domínio é: identificar o que existe, avaliar o que importa, escolher a mitigação mais próxima da causa e documentar o que fica aceito." },
      { speaker: "Ana", text: "Perfeito. Guarde essa fórmula e ela transforma enunciados confusos em checklist mental." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep16-arquitetura-rede_4f3dd65f.wav",
    id: "ep16-network-architecture-deep",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 16,
    title: "Aprofundamento: redes corporativas seguras",
    description: "Um diálogo sobre segmentação, zonas de rede, wireless, VPN e controle de acesso à rede como fundamentos de arquitetura defensiva.",
    duration: "~6 min",

    topics: ["segmentação e VLAN", "DMZ e zonas de confiança", "Wi-Fi corporativo", "VPN site-to-site e cliente", "NAC", "SDN"],
    examWeight: "18% do exame",
    provenance: fullSeriesProvenance("ep16-network-architecture-deep", "CyberCast 16 — Aprofundamento: redes corporativas seguras"),
    transcript: [
      { speaker: "Ana", text: "Arquitetura de rede segura começa com um princípio: confiança não deve se espalhar. Segmentação é a ferramenta que materializa isso, dividindo a rede em zonas com regras claras de tráfego." },
      { speaker: "Rafael", text: "Na prática, isso aparece como VLANs lógicas, sub-redes físicas e firewalls entre zonas. A DMZ é a zona clássica: recebe servidores que prestam serviço à internet, como web e e-mail, e nunca deixa conexões da DMZ alcançarem a rede interna, só o contrário, sob regras explícitas." },
      { speaker: "Ana", text: "E quando a prova descreve tráfego que precisa cruzar fronteiras de confiança, a resposta passa por inspeção: firewall tradicional com base em regras, firewall de aplicação com entendimento de protocolo, e IPS para bloquear padrões de ataque reconhecidos." },
      { speaker: "Rafael", text: "No Wi-Fi corporativo, os pontos que caem: WPA3 como padrão atual, EAP para autenticação individual por usuário, segmentação de convidados em rede separada e escondimento de SSID como medida fraca, pois não é controle de segurança real." },
      { speaker: "Ana", text: "Exato. E para acesso remoto, qual a diferença entre as VPNs?" },
      { speaker: "Rafael", text: "Site-to-site conecta duas redes, como matriz e filial, tratando toda a rota como privada. A VPN de cliente dá a uma pessoa acesso aos recursos internos a partir de qualquer localização. Nas duas, o tráfego é criptografado em túnel." },
      { speaker: "Ana", text: "E o NAC, controle de acesso à rede, decide quem pode entrar na rede com base em identidade e postura do dispositivo, verificando patches e antimalware antes de liberar. Juntando tudo, a arquitetura segura é um conjunto de decisões coerentes: zonear, inspecionar, autenticar e monitorar." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep17-nuvem-containers-mobile_9eff1048.wav",
    id: "ep17-cloud-containers-mobile",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 17,
    title: "Aprofundamento: nuvem, containers, mobile e IoT",
    description: "Ana e Rafael detalham responsabilidade compartilhada, identidades em nuvem, segurança de containers e os desafios de mobile e IoT.",
    duration: "~6 min",

    topics: ["responsabilidade compartilhada", "identidade e IAM em nuvem", "segurança de containers", "MDM", "IoT", "defesa em profundidade"],
    examWeight: "18% do exame",
    provenance: fullSeriesProvenance("ep17-cloud-containers-mobile", "CyberCast 17 — Aprofundamento: nuvem, containers, mobile e IoT"),
    transcript: [
      { speaker: "Ana", text: "Nuvem mudou o perímetro. O conceito central é o modelo de responsabilidade compartilhada: o provedor protege a plataforma, o cliente protege o que constrói sobre ela. No IaaS, o cliente leva mais responsabilidade; no SaaS, leva menos. O erro clássico da prova é achar que a segurança da nuvem é só do provedor." },
      { speaker: "Rafael", text: "E a fronteira da identidade segue valendo: IAM em nuvem combina identidade federada, menores privilégios, chaves gerenciadas e trilha de auditoria. Credenciais de console com acesso administrativo total sem MFA é a configuração que mais aparece em incidente." },
      { speaker: "Ana", text: "Containers trouxeram a mesma pergunta de sempre em outra forma: a imagem é segura? O registro é confiável? O orquestrador tem controle de acesso? O ciclo de vida da imagem, da construção à destruição, precisa ser tratado como código que pode conter vulnerabilidade." },
      { speaker: "Rafael", text: "Em mobile corporativo, o MDM controla dispositivos: políticas de senha, criptografia, separação entre dados pessoais e corporativos e remoção remota em caso de perda. E a postura segura assume que o dispositivo pode ser comprometido, então os dados corporativos viajam criptografados e expiram." },
      { speaker: "Ana", text: "IoT é o ponto mais frágil da fronteira: dispositivos baratos, com firmware desatualizado e sem gestão central. A defesa é inventário, segmentação em rede dedicada, troca de credenciais de fábrica e monitoramento do comportamento." },
      { speaker: "Rafael", text: "Repare que os três cenários têm a mesma resposta de fundo: saber o que se possui, decidir quem acessa, isolar o que pode falhar e vigiar o que resta." },
      { speaker: "Ana", text: "Exatamente. Defesa em profundidade não depende da tecnologia da moda: depende de aplicar esses princípios em qualquer ambiente." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep18-monitoramento-siem-soar_658dd369.wav",
    id: "ep18-monitoring-siem-soar",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 18,
    title: "Aprofundamento: monitoramento, SIEM, SOAR e automação",
    description: "Um diálogo sobre coleta de logs, correlação, plataformas de detecção e a automação que responde a incidentes com velocidade e consistência.",
    duration: "~6 min",

    topics: ["coleta e normalização de logs", "SIEM e correlação", "alertas e falsos positivos", "SOAR e playbooks", "automação e orquestração", "baseline"],
    examWeight: "28% do exame",
    provenance: fullSeriesProvenance("ep18-monitoring-siem-soar", "CyberCast 18 — Aprofundamento: monitoramento, SIEM, SOAR e automação"),
    transcript: [
      { speaker: "Ana", text: "Operações de segurança é o maior domínio da prova, com 28%. O ponto de partida é o monitoramento: você só enxerga ameaça do tamanho dos seus logs." },
      { speaker: "Rafael", text: "Então a base é coletar eventos de fontes diversas: firewalls, endpoints, servidores, identidade e aplicações, normalizar em formato comum e manter integridade com registro de horário sincronizado, porque correlação sem relógio certo não funciona." },
      { speaker: "Ana", text: "O SIEM agrega e correlaciona. A força dele está em regras que cruzam eventos fracos e revelam padrão forte: cinco falhas de login seguidas de um sucesso de país incomum é mais que dois alertas isolados. E a disciplina operacional inclui revisar alertas, refinar regras e reduzir falsos positivos." },
      { speaker: "Rafael", text: "Falso positivo em excesso desgasta o analista e faz o real passar despercebido. Por isso a sintonia fina da detecção é trabalho contínuo, não configuração única." },
      { speaker: "Ana", text: "E quando a resposta precisa de velocidade e repetição, entra o SOAR: playbooks que orquestram ações, como isolar host, bloquear indicador e abrir caso, com aprovação humana onde a decisão tem consequência. Automação executa, orquestração coordena, e o analista decide o que exige julgamento." },
      { speaker: "Rafael", text: "A baseline completa o quadro: sem saber o normal, todo alerta vira ruído. Tráfego, logins, processos e uso de dados estabelecidos como referência transformam anomalia em detecção confiável." },
      { speaker: "Ana", text: "Para a prova, monte o caminho: evento, correlação, alerta qualificado, triagem, resposta automatizada ou manual e aprendizado que volta para as regras. É um ciclo, não uma lista." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep19-forense-resposta_6a5ae2af.wav",
    id: "ep19-forensics-incident-response",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 19,
    title: "Aprofundamento: responder a incidentes e preservar evidências",
    description: "Ana e Rafael percorrem as etapas de resposta a incidentes e a disciplina forense que transforma investigação em prova válida.",
    duration: "~6 min",

    topics: ["ciclo de resposta a incidentes", "triagem e escalonamento", "cadeia de custódia", "ordem de volátil da coleta", "análise de evidências", "lições aprendidas"],
    examWeight: "28% do exame",
    provenance: fullSeriesProvenance("ep19-forensics-incident-response", "CyberCast 19 — Aprofundamento: responder a incidentes e preservar evidências"),
    transcript: [
      { speaker: "Ana", text: "O ciclo de resposta a incidentes tem etapas que a prova testa em ordem: preparação, detecção e análise, contenção, erradicação, recuperação e lições aprendidas. Preparação vem antes de tudo: playbook, equipe, ferramentas e comunicação já definidos." },
      { speaker: "Rafael", text: "Na detecção e análise, o primeiro dever é triagem: separar incidente real de falso positivo e escalonar conforme gravidade, acionando quem precisa agir. Conteúdo primeiro, depois escopo: o que aconteceu, onde e até onde se espalhou." },
      { speaker: "Ana", text: "A contenção é a decisão tática: isolar sistemas afetados, bloquear indicadores e preservar o estado. Mas cuidado com a sequência: preservar evidência antes de desligar, porque evidência volátil some na ordem errada de coleta." },
      { speaker: "Rafael", text: "A ordem clássica de volátil: primeiro o conteúdo em execução, como memória e processos ativos, depois conexões de rede, depois configurações e discos, e por fim mídia e backups. E em tudo, cadeia de custódia: registro de quem coletou, quando, como e onde cada evidência ficou." },
      { speaker: "Ana", text: "Sem cadeia de custódia, a evidência perde validade legal e técnica. E na análise, hash das imagens, linha do tempo de eventos e correlação com indicadores conhecidos formam a narrativa do incidente." },
      { speaker: "Rafael", text: "Erradicação remove a causa, recuperação restaura operação verificada e as lições aprendidas transformam o incidente em melhoria: nova regra de detecção, novo controle, novo treinamento." },
      { speaker: "Ana", text: "Na prova, se a questão descreve um incidente em curso, a resposta prioritária quase sempre é conter e preservar. Ação precipitada destrói evidência, e sem evidência não há aprendizado nem responsabilização." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep20-governanca-risco_d7215fc4.wav",
    id: "ep20-governance-risk-compliance",
    domainCode: "DOM5",
    domainTitle: "Program Management",
    episodeNumber: 20,
    title: "Aprofundamento: governança, risco, conformidade e pessoas",
    description: "Um diálogo sobre como a organização governa segurança: políticas, gestão de risco, auditoria, terceiros e o papel das pessoas.",
    duration: "~6 min",

    topics: ["políticas, padrões e procedimentos", "gestão de risco", "auditoria e conformidade", "terceiros", "conscientização e treinamento", "governança"],
    examWeight: "20% do exame",
    provenance: fullSeriesProvenance("ep20-governance-risk-compliance", "CyberCast 20 — Aprofundamento: governança, risco, conformidade e pessoas"),
    transcript: [
      { speaker: "Ana", text: "O último domínio é o que organiza todos os outros: governança define direção, risco define prioridades e conformidade comprova disciplina. Começamos pela hierarquia documental." },
      { speaker: "Rafael", text: "Política é o direcionamento de alto nível, aprovada pela liderança. Padrão é a especificação obrigatória que concretiza a política. Procedimento descreve os passos da execução. E guideline orienta sem obrigar. A prova quer que você distinga os quatro níveis pelo grau de obrigatoriedade." },
      { speaker: "Ana", text: "Gestão de risco usa a mesma lógica: identificar, avaliar probabilidade e impacto, decidir entre mitigar, transferir, aceitar ou evitar, e monitorar. A resposta de prova considera apetite de risco da organização, que define o que ela aceita viver." },
      { speaker: "Rafael", text: "E conformidade é a verificação: auditoria interna avalia de dentro, auditoria externa comprova para terceiros, e regulamentos ou frameworks, como ISO 27001 ou leis de proteção de dados, definem o piso. Conformidade não é o teto: organização madura usa o framework como base e vai além." },
      { speaker: "Ana", text: "O risco de terceiros merece atenção: fornecedores com acesso a dados ou sistemas estendem a superfície da organização. A gestão inclui avaliação prévia, cláusulas contratuais, monitoramento contínuo e plano de saída." },
      { speaker: "Rafael", text: "E as pessoas: conscientização gera compreensão, treinamento gera habilidade e a métrica de programa valida o efeito. Campanhas de phishing simulado, por exemplo, medem evolução real, não apenas presença de curso." },
      { speaker: "Ana", text: "Para fechar o domínio e a prova: governança conecta todos os controles que você estudou. A questão madura sempre pergunta qual direção, qual risco e qual evidência. Quem domina essa pergunta domina o exame." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep21-comparativos-dominio1_6ecb3490.wav",
    id: "ep21-confidencialidade-vs-integridade",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 21,
    title: "Comparativo: confidencialidade, integridade e disponibilidade",
    description: "Ana e Rafael comparam os objetivos da tríade em situações próximas e as soluções que comprovam cada um: hashing, criptografia, assinatura e backup.",
    duration: "~5 min",

    topics: ["CIA na prática", "hashing vs criptografia", "assinatura vs certificado", "backup e disponibilidade", "pegadinhas da tríade"],
    examWeight: "12% do exame",
    provenance: fullSeriesProvenance("ep21-confidencialidade-vs-integridade", "CyberCast 21 — Comparativo: confidencialidade, integridade e disponibilidade"),
    transcript: [
      { speaker: "Ana", text: "Formato comparativo, ideal para fixar o que a prova mais confunde. Primeiro duelo: confidencialidade contra integridade. Qual a diferença em uma frase?" },
      { speaker: "Rafael", text: "Confidencialidade é ninguém indevido ver. Integridade é ninguém indevido alterar. O verbo define: revelar afeta a primeira, modificar afeta a segunda." },
      { speaker: "Ana", text: "E agora hashing contra criptografia. Ambos usam matemática sobre o dado. Onde cada um atua?" },
      { speaker: "Rafael", text: "O hash gera resumo unidirecional: serve para verificar se o dado mudou, nunca para protegê-lo de leitura. A criptografia transforma o dado com chave: protege a leitura, mas por si só não prova que ninguém alterou." },
      { speaker: "Ana", text: "Duelo seguinte: assinatura digital contra certificado digital. Ambos têm chave, ambos têm autoridade. O que separa?" },
      { speaker: "Rafael", text: "A assinatura prova autoria e integridade: cifro o hash com minha chave privada e quem verifica usa a pública. O certificado prova identidade: une uma chave pública a um nome, emitido por autoridade certificadora. Assinatura responde quem fez; certificado responde quem é." },
      { speaker: "Ana", text: "E disponibilidade? Qual o contraste com as duas anteriores?" },
      { speaker: "Rafael", text: "As anteriores protegem o dado parado ou em trânsito; disponibilidade protege o serviço vivo: backup, redundância, balanceamento e recuperação garantem que o sistema exista quando o negócio precisa." },
      { speaker: "Ana", text: "Última pegadinha do episódio: criptografia de ponta a ponta garante confidencialidade no trânsito, mas não prova autenticidade por si só. Se a questão pede origem verificável, a resposta inclui assinatura ou certificado, não apenas cifra." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep22-identidades-comparadas_e918383a.wav",
    id: "ep22-identidades-comparadas",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 22,
    title: "Comparativo: MFA, SSO, federação e modelos de acesso",
    description: "Rafael e Ana desmontam as quatro famílias de decisão de identidade que a prova mais testa: provar, acessar, confiar e autorizar.",
    duration: "~5 min",

    topics: ["MFA", "SSO", "federação", "RBAC vs ABAC vs MAC", "diretório de identidade", "pegadinhas"],
    examWeight: "12% do exame",
    provenance: fullSeriesProvenance("ep22-identidades-comparadas", "CyberCast 22 — Comparativo: MFA, SSO, federação e modelos de acesso"),
    transcript: [
      { speaker: "Ana", text: "Segundo comparativo: as tecnologias de identidade. Primeira pergunta: quando a resposta é MFA e quando é SSO?" },
      { speaker: "Rafael", text: "MFA responde como provar a identidade: mais de uma categoria de evidência. SSO responde como acessar muitos sistemas: um login, várias aplicações. São eixos diferentes: um fortalece a prova, outro simplifica o uso." },
      { speaker: "Ana", text: "E federação? Parece SSO, mas difere em quê?" },
      { speaker: "Rafael", text: "Federation atravessa fronteiras organizacionais: o provedor de identidade de uma organização emite asserções que outra confia. SSO comum fica dentro da mesma organização. A palavra-chave da federação é confiança entre domínios." },
      { speaker: "Ana", text: "Segundo duelo: RBAC, ABAC e MAC. Três respostas de autorização para três sinais no enunciado." },
      { speaker: "Rafael", text: "Se o texto fala em cargo, departamento e papel, é RBAC. Se fala em atributos dinâmicos, horário, localização e classificação de dado, é ABAC. Se fala em rótulos obrigatórios e hierarquia de sensibilidade, é MAC." },
      { speaker: "Ana", text: "E o diretório de identidade, como o Active Directory? Como se posiciona nessa comparação?" },
      { speaker: "Rafael", text: "Diretório é a fonte central de contas e grupos; suporta autenticação e autorização dentro do domínio, e pode se integrar a federação, mas sozinho não é nem MFA nem SSO. É o repositório, não o método." },
      { speaker: "Ana", text: "Fechando com a pegadinha clássica: biometria sozinha é MFA de uma categoria só. MFA exige combinar categorias distintas, por isso a resposta de prova soma senha, token e biometria, nunca repete o mesmo tipo duas vezes." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep23-vetores-comparados_886d6c19.wav",
    id: "ep23-vetores-comparados",
    domainCode: "DOM2",
    domainTitle: "Threats & Vulnerabilities",
    episodeNumber: 23,
    title: "Comparativo: variações de phishing, IOC e TTP, mitigação",
    description: "Ana e Rafael separam as variações de engenharia social, a fronteira entre indicador e comportamento e a diferença entre mitigar e corrigir.",
    duration: "~5 min",

    topics: ["phishing, spear-phishing e whaling", "IOC vs TTP", "mitigação vs correção", "vishing e smishing", "pegadinhas"],
    examWeight: "22% do exame",
    provenance: fullSeriesProvenance("ep23-vetores-comparados", "CyberCast 23 — Comparativo: variações de phishing, IOC e TTP, mitigação"),
    transcript: [
      { speaker: "Ana", text: "Comparativo de vetores: as três variações de phishing que mais confundem. Diferencie em uma frase cada uma." },
      { speaker: "Rafael", text: "Phishing é em massa, sem alvo específico. Spear-phishing mira uma pessoa ou grupo conhecido, usando contexto real para parecer legítimo. Whaling é o spear contra executivo, com linguagem corporativa e urgência de negócio." },
      { speaker: "Ana", text: "E as variações por canal: vishing e smishing?" },
      { speaker: "Rafael", text: "Vishing é por voz, com ligação que induz a entregar dado ou transferir valor. Smishing é por mensagem de texto, com link curto e urgência. O canal muda, o mecanismo de indução é o mesmo." },
      { speaker: "Ana", text: "Segundo duelo: IOC contra TTP. Ambos descrevem o adversário. O que muda?" },
      { speaker: "Rafael", text: "IOC é artefato observável: hash, endereço, domínio, nome de arquivo. Troca com frequência e perde valor rápido. TTP é tática, técnica e procedimento: como o adversário opera. Muda menos e ajuda a antecipar próximos passos." },
      { speaker: "Ana", text: "E mitigação contra correção: a prova usa os dois verbos. Qual a distinção?" },
      { speaker: "Rafael", text: "Mitigação reduz probabilidade ou impacto sem eliminar a causa, como segmentar um sistema vulnerável enquanto não há patch. Correção elimina a causa: o patch, o código corrigido, a credencial revogada e trocada." },
      { speaker: "Ana", text: "Última pegadinha do episódio: treinamentos e avisos reduzem engenharia social, mas sozinhos não são controle completo. Se a alternativa mistura técnica e comportamento, prefira a que reduz a superfície de ataque de forma sistemática." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep24-arquitetura-comparada_da8ac06a.wav",
    id: "ep24-arquitetura-comparada",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 24,
    title: "Comparativo: firewall, WAF e IDS/IPS; VPNs e backups",
    description: "Rafael e Ana comparam as defesas de borda, os tipos de VPN e as famílias de backup que a prova testa em cenários de escolha de controle.",
    duration: "~5 min",

    topics: ["firewall vs WAF vs IDS/IPS", "VPN site-to-site vs cliente", "backup completo, incremental e diferencial", "pegadinhas"],
    examWeight: "18% do exame",
    provenance: fullSeriesProvenance("ep24-arquitetura-comparada", "CyberCast 24 — Comparativo: firewall, WAF e IDS/IPS; VPNs e backups"),
    transcript: [
      { speaker: "Ana", text: "Comparativo de defesas de borda: firewall, WAF e IDS/IPS. O que cada um enxerga?" },
      { speaker: "Rafael", text: "O firewall decide por regras de tráfego: portas, endereços e protocolos permitidos. O WAF entende aplicação web: bloqueia injeção, ataques entre sites e abuso de endpoint HTTP. IDS observa e alerta; IPS observa e bloqueia em linha." },
      { speaker: "Ana", text: "E a pegadinha clássica: qual dos três corrige uma vulnerabilidade de aplicação?" },
      { speaker: "Rafael", text: "Nenhum corrige. Eles mitigam a exploração. A correção vive no código. Se a questão pede solução definitiva, a resposta é corrigir a aplicação, não comprar mais um filtro." },
      { speaker: "Ana", text: "Segundo duelo: site-to-site contra VPN de cliente." },
      { speaker: "Rafael", text: "Site-to-site conecta redes inteiras, tratando a rota entre elas como privada e contínua. Cliente é pontual: uma pessoa acessa recursos internos de qualquer lugar, sob autenticação individual. O sinal de decisão é quem atravessa: rede ou usuário." },
      { speaker: "Ana", text: "Terceiro duelo: as três famílias de backup. Complete, incremental e diferencial. Qual a lógica?" },
      { speaker: "Rafael", text: "Completo copia tudo. Incremental copia só o que mudou desde a última cópia de qualquer tipo, sendo rápido no dia a dia mas mais lento na restauração, que exige cadeia. Diferencial copia o que mudou desde o último completo, equilibrando backup e restauração." },
      { speaker: "Ana", text: "E na prova, a escolha depende do objetivo de recuperação: tempo de restauração curto favorece diferencial, economia de espaço favorece incremental. E a regra dos três, com cópia fora do local e offline, protege contra ransomware." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep25-operacoes-comparadas_9bb8ebbb.wav",
    id: "ep25-operacoes-comparadas",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 25,
    title: "Comparativo: triagem, detecção e escalonamento; RTO e RPO",
    description: "Ana e Rafael comparam etapas de operação e métricas de recuperação que a prova apresenta em cenários de decisão sequencial.",
    duration: "~5 min",

    topics: ["detecção vs triagem vs escalonamento", "RTO vs RPO", "imagem vs cópia", "alerta vs caso", "pegadinhas"],
    examWeight: "28% do exame",
    provenance: fullSeriesProvenance("ep25-operacoes-comparadas", "CyberCast 25 — Comparativo: triagem, detecção e escalonamento; RTO e RPO"),
    transcript: [
      { speaker: "Ana", text: "Comparativo de operações: detecção, triagem e escalonamento. Três verbos sequenciais que a prova testa separados." },
      { speaker: "Rafael", text: "Detecção é o sistema ou pessoa identificar um possível evento. Triagem é classificar o evento: real ou falso positivo, gravidade e urgência. Escalonamento é passar a decisão para quem tem autoridade ou especialidade para agir." },
      { speaker: "Ana", text: "E alerta contra caso? Ambos aparecem em SIEM e SOAR." },
      { speaker: "Rafael", text: "Alerta é o sinal pontual da regra. Caso é a unidade de trabalho da investigação: vários alertas relacionados viram um caso, com registro, atribuição e resolução. Alerta dispara, caso conduz." },
      { speaker: "Ana", text: "Segundo duelo, métricas de recuperação: RTO e RPO. Confundir os dois custa ponto certo." },
      { speaker: "Rafael", text: "RTO é tempo: quanto tempo o serviço pode ficar fora antes do dano inaceitável, definindo a velocidade da restauração. RPO é dado: quanto de informação a organização aceita perder, definindo a frequência do backup. RTO olha para o futuro da operação, RPO olha para o passado dos dados." },
      { speaker: "Ana", text: "E na forense, imagem contra cópia simples?" },
      { speaker: "Rafael", text: "A imagem forense é bit a bit, incluindo espaço não alocado, com hash de verificação que garante integridade da evidência. Cópia comum copia apenas arquivos visíveis e não prova fidelidade. Para evidência, sempre imagem com hash." },
      { speaker: "Ana", text: "Guardando o padrão: cada comparação da prova opõe dois conceitos próximos e a chave está no verbo que os distingue. Verbo errado, resposta errada." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep26-governanca-comparada_7eba8fe3.wav",
    id: "ep26-governanca-comparada",
    domainCode: "DOM5",
    domainTitle: "Program Management",
    episodeNumber: 26,
    title: "Comparativo: política, padrão e procedimento; auditorias e métricas",
    description: "Rafael e Ana comparam os níveis documentais da governança, os tipos de auditoria e as métricas que provam que o programa funciona.",
    duration: "~5 min",

    topics: ["política vs padrão vs procedimento", "auditoria interna vs externa", "KPI vs KRI", "compliance vs maturidade", "pegadinhas"],
    examWeight: "20% do exame",
    provenance: fullSeriesProvenance("ep26-governanca-comparada", "CyberCast 26 — Comparativo: política, padrão e procedimento; auditorias e métricas"),
    transcript: [
      { speaker: "Ana", text: "Último comparativo, agora sobre governança. Primeiro duelo documental: política, padrão e procedimento." },
      { speaker: "Rafael", text: "Política diz o quê e por quê, com aprovação da liderança e baixa frequência de mudança. Padrão diz a especificação obrigatória, como criptografia mínima ou tamanho de senha. Procedimento diz o passo a passo da execução, com detalhes que mudam com a tecnologia." },
      { speaker: "Ana", text: "Segundo duelo: auditoria interna contra externa." },
      { speaker: "Rafael", text: "A interna é conduzida pela própria organização, com familiaridade do contexto e objetivo de melhoria contínua. A externa é conduzida por parte independente, com objetivo de comprovação para terceiros, clientes ou reguladores." },
      { speaker: "Ana", text: "E métricas: KPI contra KRI. Ambas medem, com propósitos diferentes." },
      { speaker: "Rafael", text: "KPI mostra desempenho do programa: tempo de patch, cobertura de treinamento, conclusão de auditorias. KRI antecipa risco: crescimento de alertas não tratados, aumento de sistemas fora do inventário. KPI mede o que se fez, KRI avisa do que pode acontecer." },
      { speaker: "Ana", text: "Última pegadinha: conformidade contra maturidade. Cumprir o regulamento é piso verificável; maturidade é o nível de evolução do programa além do piso. A prova valoriza a organização que usa a conformidade como ponto de partida, não de chegada." },
      { speaker: "Rafael", text: "Então o resumo do domínio é: documentos com graus de obrigatoriedade, auditorias com propósitos distintos e métricas com funções diferentes. Governar é saber qual nível estamos medindo." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep27-simulado-dom1-dom2_54b1b239.wav",
    id: "ep27-simulado-dom1-dom2",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 27,
    title: "Simulado comentado: conceitos gerais e ameaças",
    description: "Ana e Rafael resolvem questões de estilo Security+ dos domínios 1 e 2, explicando cada alternativa e a armadilha escondida em cada enunciado.",
    duration: "~7 min",

    topics: ["questões comentadas", "leitura de enunciado", "eliminação de alternativas", "CIA e controles", "vetores e mitigação"],
    examWeight: "34% do exame (DOM1 + DOM2)",
    provenance: fullSeriesProvenance("ep27-simulado-dom1-dom2", "CyberCast 27 — Simulado comentado: conceitos gerais e ameaças"),
    transcript: [
      { speaker: "Ana", text: "Modo simulado. Vou ler uma questão de estilo Security+ e você resolve como se estivesse na prova, explicando o raciocínio antes da resposta." },
      { speaker: "Rafael", text: "Perfeito, pode ler." },
      { speaker: "Ana", text: "Questão um: uma organização descobriu que credenciais de funcionários foram publicadas em um fórum público. Qual ação reduz primeiro o risco de acesso indevido imediato? Opções: treinar funcionários, redefinir senhas afetadas, bloquear o fórum ou contratar auditoria." },
      { speaker: "Rafael", text: "Resposta: redefinir as senhas afetadas. O risco imediato é o acesso indevido com a credencial já exposta; a redefinição neutraliza esse vetor de forma direta. Treinamento é preventivo para o futuro, bloquear o fórum não controla as cópias existentes e auditoria é análise posterior. Eliminei pela causa mais próxima." },
      { speaker: "Ana", text: "Método correto. Questão dois: um funcionário do financeiro pode aprovar e executar pagamentos, sem segunda aprovação. Qual princípio foi violado? Opções: menor privilégio, separação de funções, não repúdio ou defesa em profundidade." },
      { speaker: "Rafael", text: "Separação de funções. Uma mesma pessoa acumula duas etapas que, combinadas, permitem fraude completa. Menor privilégio trataria de conceder acesso excessivo, mas o problema central aqui é a ausência de contrapeso entre criar e executar." },
      { speaker: "Ana", text: "Questão três, vetores: funcionários recebem mensagens falsas do departamento de TI pedindo verificação de conta por um link. A campanha visa todos, sem personalização. Qual o tipo?" },
      { speaker: "Rafael", text: "Phishing em massa. Não há indicação de alvo específico, então não é spear. Se mirasse o CFO com temas de negócio, seria whaling. A pegadinha comum aqui é confundir a falsificação de identidade, que é spoofing, com o vetor em si, que é phishing." },
      { speaker: "Ana", text: "E a mitigação mais eficaz no mesmo cenário?" },
      { speaker: "Rafael", text: "Combinação: filtro de e-mail e marcação de mensagens externas reduzem a chegada, MFA resistente a phishing neutraliza a credencial capturada e treinamento contextual reduz a indução. Na prova, quando a alternativa única existe, priorizo o controle técnico que quebra o vetor principal." },
      { speaker: "Ana", text: "Última do bloco: uma questão sobre criptografia diz que o hash de um documento garante confidencialidade. Qual o erro?" },
      { speaker: "Rafael", text: "O erro é a função: hash prova integridade, não esconde o conteúdo. Para confidencialidade seria criptografia. Questões assim pedem atenção ao verbo da proteção, exatamente o padrão que praticamos no comparativo." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep28-simulado-dom3_357e3691.wav",
    id: "ep28-simulado-dom3",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 28,
    title: "Simulado comentado: arquitetura de segurança",
    description: "Questões comentadas de desenho de rede, identidade, nuvem e resiliência, com Rafael explicando a escolha e Ana revelando as armadilhas.",
    duration: "~7 min",

    topics: ["questões comentadas", "desenho de zonas", "identidade em nuvem", "resiliência", "leitura de enunciado"],
    examWeight: "18% do exame",
    provenance: fullSeriesProvenance("ep28-simulado-dom3", "CyberCast 28 — Simulado comentado: arquitetura de segurança"),
    transcript: [
      { speaker: "Ana", text: "Bloco de arquitetura. Questão um: uma empresa quer publicar um portal web sem expor a rede interna. Os servidores internos precisam acessar a base de dados, que não deve receber conexão direta da internet. Onde fica cada componente?" },
      { speaker: "Rafael", text: "O portal e seus servidores de aplicação ficam na DMZ. A base de dados fica na rede interna. O fluxo correto é internet, DMZ, interna, com regras que permitem tráfego de entrada restrito e bloqueiam conexão iniciada da DMZ para dentro, salvo o necessário da camada de aplicação." },
      { speaker: "Ana", text: "Questão dois: usuários de filiais acessam aplicações corporativas de suas cidades com alta frequência. A alternativa que reduz custo de tráfego e melhora experiência, mantendo inspeção?" },
      { speaker: "Rafael", text: "VPN site-to-site entre a filial e a matriz, com políticas de inspeção na borda. Evita enviar cada acesso individual por túnel de cliente e mantém o tráfego consolidado sob controle." },
      { speaker: "Ana", text: "Questão três, nuvem: a organização migra bancos de dados para um provedor gerenciado e assume que a segurança dos dados é responsabilidade exclusiva do provedor. Qual a falha de raciocínio?" },
      { speaker: "Rafael", text: "Viola o modelo de responsabilidade compartilhada. O provedor protege a plataforma, mas classificação, criptografia, controle de acesso e backups dos dados seguem sendo do cliente. A prova cobra exatamente essa fronteira." },
      { speaker: "Ana", text: "Questão quatro: um aplicativo precisa de acesso de leitura a registros de usuários e não deve nunca modificar permissões. Qual configuração aplica o princípio adequado?" },
      { speaker: "Rafael", text: "Conta de serviço com permissão mínima de somente leitura, usando autorização explícita para o escopo necessário. Menor privilégio aplicado a identidade não humana, que é um dos cenários mais testados." },
      { speaker: "Ana", text: "Última do bloco: qual métrica de arquitetura garante que o serviço volta rápido depois de falha regional?" },
      { speaker: "Rafael", text: "Resiliência projetada: replicação entre regiões com failover automatizado. A métrica associada é o RTO, e o desenho que o viabiliza é redundância ativa, não apenas backup frio." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep29-simulado-dom4-dom5_1f6d86b6.wav",
    id: "ep29-simulado-dom4-dom5",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 29,
    title: "Simulado comentado: operações e gestão de programa",
    description: "Questões comentadas dos domínios de monitoramento, resposta, forense, governança e risco, com a lógica de decisão explicada a cada passo.",
    duration: "~7 min",

    topics: ["questões comentadas", "ordem de resposta", "cadeia de custódia", "gestão de risco", "conformidade"],
    examWeight: "48% do exame (DOM4 + DOM5)",
    provenance: fullSeriesProvenance("ep29-simulado-dom4-dom5", "CyberCast 29 — Simulado comentado: operações e gestão de programa"),
    transcript: [
      { speaker: "Ana", text: "Bloco final de questões, cobrindo os domínios de maior peso. Questão um: um servidor crítico apresenta processo desconhecido consumindo recursos e conexões para domínio externo recém-criado. Qual a primeira ação recomendada?" },
      { speaker: "Rafael", text: "Preservar evidência volátil antes de qualquer desligamento: capturar memória e conexões ativas. Desligar o servidor de imediato destruiria memória, e a análise ficaria limitada. Depois, contenção isolada e investigação de escopo." },
      { speaker: "Ana", text: "Questão dois: durante a investigação, a equipe envia a imagem do disco para análise externa. O que garante a validade da evidência nessa transferência?" },
      { speaker: "Rafael", text: "Cadeia de custódia documentada e hash verificado da imagem antes e depois do transporte. Sem o registro de quem manuseou e a prova de integridade, a evidência perde valor técnico e legal." },
      { speaker: "Ana", text: "Questão três, gestão de risco: o conselho avalia um sistema legacado sem correções disponíveis. Aceitar o risco puro, substituir já ou adotar controles compensatórios com registro de aceitação?" },
      { speaker: "Rafael", text: "Controles compensatórios com aceitação formal de risco. Se a substituição não é imediata, a organização reduz exposição com camadas alternativas e documenta apetite, responsável e revisão. Aceitar sem mitigação adicional raramente é a resposta madura." },
      { speaker: "Ana", text: "Questão quatro: a auditoria externa encontrou desvios de um controle e a empresa corrigiu apenas os itens listados, sem revisar o processo de origem. Qual a crítica correta?" },
      { speaker: "Rafael", text: "Corrigir sintomas sem tratar a causa deixa o desvio reincidente. A resposta completa inclui análise de causa raiz, ajuste de processo e verificação de recorrência em outros controles." },
      { speaker: "Ana", text: "Última questão: qual ação demonstra que o programa de segurança evolui após incidentes?" },
      { speaker: "Rafael", text: "Lições aprendidas incorporadas às regras de detecção, playbooks e treinamentos. É o ciclo que fecha: incidente vira melhoria, e melhoria reduz o próximo incidente." },
    ],
  },
  {
    audioUrl: "/manus-storage/ep30-estrategia-final_892cb2b8.wav",
    id: "ep30-estrategia-final-prova",
    domainCode: "DOM5",
    domainTitle: "Program Management — Estratégia Final da Prova",
    episodeNumber: 30,
    title: "Estratégia final: o dia da prova",
    description: "Ana e Rafael fecham a série com a estratégia de exame: gestão de tempo, leitura de enunciado, eliminação de alternativas e revisão integrada dos cinco domínios.",
    duration: "~6 min",

    topics: ["gestão de tempo", "leitura de enunciado", "eliminação de alternativas", "revisão integrada", "mentalidade do examinando"],
    examWeight: "100% do exame",
    provenance: fullSeriesProvenance("ep30-estrategia-final-prova", "CyberCast 30 — Estratégia final: o dia da prova"),
    transcript: [
      { speaker: "Ana", text: "Último episódio da série. Hoje não é conteúdo novo: é estratégia. Como chegar ao dia da prova com método. Primeira regra: tempo é recurso, não inimigo. Alocamos minutos por questão, marcamos as difíceis e voltamos a elas ao final." },
      { speaker: "Rafael", text: "Na leitura, eu sublinho mentalmente três coisas: o papel do personagem, o problema central e o verbo da ação pedida. Enunciado de Security+ quase sempre tem um cenário antes da pergunta, e a resposta errada frequentemente responde outra pergunta." },
      { speaker: "Ana", text: "Técnica de eliminação: descarte primeiro o que contradiz o enunciado, depois o que responde problema diferente e por último os dois parecidos. Entre alternativas próximas, escolha a que resolve a causa mais próxima, não a mais famosa." },
      { speaker: "Rafael", text: "E nos temas, o mapa mental da série vale como revisão: conceitos gerais respondem controle certo para problema certo; ameaças pedem ator, vetor e mitigação; arquitetura exige desenho e camadas; operações priorizam preservar antes de agir; e gestão sempre quer direção, risco e evidência." },
      { speaker: "Ana", text: "No dia, confiança vem de repetição. Faça simulados cronometrados, revise os episódios que apontarem lacuna e descanse na véspera. A prova mede decisão, e decisão boa vem de método treinado." },
      { speaker: "Rafael", text: "Então o resumo da série inteira: aprender em diálogo, revisar por cenário, comparar o que é parecido e treinar em simulado. São os quatro movimentos que preparam de verdade." },
      { speaker: "Ana", text: "Foi um prazer conduzir essa jornada, Rafael. E foi um prazer para quem nos acompanhou em cada episódio. Lembre-se: segurança é aprendizado contínuo. A certificação é uma porta, não o destino." },
      { speaker: "Rafael", text: "Até a próxima missão de estudo, e bom exame para todos nós." },
    ],
  },
];
