import type { PodcastEpisode } from "./podcastEpisodes";
import type { ContentProvenanceItem } from "./contentProvenance";

const batchFourProvenance = (id: string, title: string): ContentProvenanceItem => ({
  id: `podcast-${id}`,
  origin: "proprio",
  category: "Podcast educacional próprio",
  title,
  source: "CyberDimension Academy",
  license: "Conteúdo autoral da CyberDimension Academy; uso de estudo dentro da plataforma.",
  usage: "Diálogo autoral em áudio e transcrição acessível de aprofundamento da CompTIA Security+ SY0-701.",
});

export interface PodcastTimestampedLine {
  speaker: "Ana" | "Rafael";
  text: string;
  /** Segundo de início estimado da fala no áudio final, usado pelos marcadores temporais. */
  timestampSeconds: number;
}

export const podcastBatchFourEpisodes: readonly PodcastEpisode[] = [
  {
    id: "ep31-devseguro-automacao",
    domainCode: "DOM2",
    domainTitle: "Threats, Vulnerabilities & Mitigations",
    episodeNumber: 31,
    title: "Aprofundamento: desenvolvimento seguro e automação de segurança",
    description: "Ana e Rafael conectam segurança de software, CI/CD e automação à prática de segurança operacional.",
    audioUrl: "/manus-storage/ep31-devseguro-automacao_d22e03c9.wav",
    duration: "1m30s",
    topics: ["ciclo de vida de desenvolvimento seguro", "CI/CD e pipeline de segurança", "automação de segurança", "devsecops", "pegadinhas"],
    examWeight: "22% do exame",
    provenance: batchFourProvenance("ep31-devseguro-automacao", "CyberCast 31 — Aprofundamento: desenvolvimento seguro e automação de segurança"),
    transcript: [
      { speaker: "Ana", text: "Hoje um tema que une desenvolvimento e segurança: construir software com segurança desde o início, e usar automação para escalar essa prática.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Então o caminho é o desenvolvimento seguro: integrar segurança em todo o ciclo de vida do software, exigências, arquitetura, codificação, teste e implantação, em vez de corrigir problemas só no final.", timestampSeconds: 9 },
      { speaker: "Ana", text: "Exato. E as práticas centrais: revisão de código por pares, análise estática de segurança no build, análise dinâmica em ambiente de execução e varredura de dependências.", timestampSeconds: 19 },
      { speaker: "Rafael", text: "E os dados sensíveis precisam de tratamento especial: nunca colocar credenciais em código fonte, usar cofre de segredos, validar e higienizar toda entrada do usuário, e sanitizar as saídas para evitar injeção.", timestampSeconds: 32 },
      { speaker: "Ana", text: "A automação entra com o pipeline de integração e entrega contínua. O que automatizamos: compilar, testar, varrer vulnerabilidades e implantar em ambientes controlados a cada mudança.", timestampSeconds: 44 },
      { speaker: "Rafael", text: "Mas com um cuidado: automação errada multiplica o erro. Por isso o pipeline precisa de portões de qualidade: a mudança só avança se passar nos testes de segurança, e o processo de implantação é rastreável.", timestampSeconds: 57 },
      { speaker: "Ana", text: "E a regra de ouro para a prova: a automação reduz erro humano e aumenta consistência, mas não substitui análise e julgamento em decisões críticas de risco.", timestampSeconds: 71 },
    ],
  },
  {
    id: "ep32-threat-intel-osint",
    domainCode: "DOM2",
    domainTitle: "Threats, Vulnerabilities & Mitigations",
    episodeNumber: 32,
    title: "Aprofundamento: inteligência de ameaças e fontes abertas",
    description: "Ana e Rafael explicam IOCs, TTPs, o framework MITRE ATT&CK e como usar fontes abertas de forma responsável.",
    audioUrl: "/manus-storage/ep32-threat-intel-osint_1549cfdc.wav",
    duration: "1m36s",
    topics: ["IOC vs TTP", "MITRE ATT&CK", "OSINT e fontes abertas", "inteligência de ameaças", "pegadinhas"],
    examWeight: "22% do exame",
    provenance: batchFourProvenance("ep32-threat-intel-osint", "CyberCast 32 — Aprofundamento: inteligência de ameaças e fontes abertas"),
    transcript: [
      { speaker: "Ana", text: "Inteligência de ameaças é o tema de hoje. É a prática de coletar, analisar e aplicar informação sobre adversários para tomar decisões defensivas melhores.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "A distinção mais cobrada da prova: indicador de comprometimento é a evidência observável, um hash de malware, um endereço malicioso, uma string de log. Tática, técnica e procedimento são o comportamento: como o atacante age, passo a passo.", timestampSeconds: 11 },
      { speaker: "Ana", text: "Por isso IOCs envelhecem rápido: o atacante muda o arquivo e o indicador morre. As TTPs envelhecem devagar: mudar de comportamento exige muito mais esforço. Defesa por TTP detecta famílias novas com padrões antigos.", timestampSeconds: 25 },
      { speaker: "Rafael", text: "E o framework MITRE ATT&CK organiza esse conhecimento: táticas são os objetivos do atacante, técnicas são os meios para alcançá-los. Um mapa da adversidade que usamos para medir cobertura de detecção.", timestampSeconds: 39 },
      { speaker: "Ana", text: "Fontes de inteligência: relatórios de fornecedores, compartilhamento setorial, feeds técnicos e OSINT, a inteligência de fontes abertas: sites públicos, fóruns, registros e notícias.", timestampSeconds: 52 },
      { speaker: "Rafael", text: "E a pegadinha da prova: OSINT legítimo coleta dados públicos. Se eu uso OSINT contra uma organização que não me autorizou, estou praticando reconhecimento, o primeiro passo de um ataque. O mesmo ato muda de natureza conforme a intenção.", timestampSeconds: 65 },
    ],
  },
  {
    id: "ep33-iam-avancado",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 33,
    title: "Aprofundamento: identidade avançada e privilégios sob controle",
    description: "Ana e Rafael aprofundam IAM, PAM, certificados e o controle fino de privilégios em arquiteturas modernas.",
    audioUrl: "/manus-storage/ep33-iam-avancado_bd62a8af.wav",
    duration: "1m28s",
    topics: ["IAM e PAM", "privilégio mínimo e revisão", "certificados na arquitetura", "gestão de credenciais", "pegadinhas"],
    examWeight: "18% do exame",
    provenance: batchFourProvenance("ep33-iam-avancado", "CyberCast 33 — Aprofundamento: identidade avançada e privilégios sob controle"),
    transcript: [
      { speaker: "Ana", text: "No terceiro domínio, hoje vamos além do básico de identidade: gestão avançada de acessos e de privilégios em arquiteturas reais.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "O princípio norteador continua sendo o menor privilégio: cada identidade recebe somente o acesso necessário, pelo tempo necessário, e nada mais. Na prática, isso significa revisar acessos periodicamente.", timestampSeconds: 11 },
      { speaker: "Ana", text: "E quando o privilégio é sensível, entra o PAM, a gestão de acessos privilegiados: contas de administrador não são usadas no dia a dia, sessões são gravadas, credenciais giram automaticamente e qualquer uso extraordinário é alertado.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "E os certificados também entram na arquitetura: autenticam servidores e dispositivos, criptografam tráfego e assinam código. A gestão inclui o inventário, a rotação antes do vencimento e a revogação imediata em caso de exposição.", timestampSeconds: 40 },
      { speaker: "Ana", text: "Identidade como perímetro: em ambientes modernos, o controle de acesso não protege só a rede, protege o dado onde ele estiver, com políticas dinâmicas baseadas em quem acessa, de onde e com qual dispositivo.", timestampSeconds: 55 },
      { speaker: "Rafael", text: "E a pegadinha: privilégio acumulado é o risco silencioso. Transferências de função sem remoção de acesso criam identidades com poder excessivo. A revisão periódica é o controle que expõe esse acúmulo.", timestampSeconds: 70 },
    ],
  },
  {
    id: "ep34-resiliencia-backup",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 34,
    title: "Aprofundamento: resiliência, backups e recuperação de desastres",
    description: "Ana e Rafael explicam alta disponibilidade, redundância, backups e os planos que mantêm a organização funcionando.",
    audioUrl: "/manus-storage/ep34-resiliencia-backup_05b96777.wav",
    duration: "1m34s",
    topics: ["alta disponibilidade e redundância", "tipos de backup e restauração", "RTO e RPO", "recuperação de desastres", "pegadinhas"],
    examWeight: "18% do exame",
    provenance: batchFourProvenance("ep34-resiliencia-backup", "CyberCast 34 — Aprofundamento: resiliência, backups e recuperação de desastres"),
    transcript: [
      { speaker: "Ana", text: "Resiliência é a capacidade de o negócio continuar funcionando diante de falhas e desastres. Vamos desmontar esse conceito nas peças que a prova cobra.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Alta disponibilidade é o desenho que evita a interrupção: redundância de componentes, balanceamento, clusters e failover automático. Se uma peça falha, outra assume sem o usuário perceber.", timestampSeconds: 12 },
      { speaker: "Ana", text: "E o backup é a rede de segurança quando a prevenção falha. Tipos clássicos: completo copia tudo, incremental copia só o que mudou desde o último backup, diferencial copia o que mudou desde o último completo.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "E o diferencial entre incremental e diferencial importa na restauração: o incremental exige toda a cadeia de backups, o diferencial só o completo mais o diferencial. Mais espaço no incremental, mais rapidez na restauração do diferencial.", timestampSeconds: 42 },
      { speaker: "Ana", text: "Duas métricas definem tudo: RPO, a perda máxima aceitável de dados, e RTO, o tempo máximo aceitável para restabelecer o serviço. RPO orienta frequência de backup, RTO orienta a arquitetura de recuperação.", timestampSeconds: 59 },
      { speaker: "Rafael", text: "E a pegadinha que ninguém esquece: backup que não foi testado é só esperança. A restauração periódica é que transforma backup em capacidade real de recuperação.", timestampSeconds: 74 },
    ],
  },
  {
    id: "ep35-triagem-alertas",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 35,
    title: "Aprofundamento: triagem, priorização e análise de alertas",
    description: "Ana e Rafael mostram o dia a dia da triagem de alertas: distinguir ruído de sinal e priorizar o que importa.",
    audioUrl: "/manus-storage/ep35-triagem-alertas_5f180524.wav",
    duration: "1m26s",
    topics: ["triagem de alertas", "falsos positivos", "contexto e priorização", "decisões de resposta", "pegadinhas"],
    examWeight: "28% do exame",
    provenance: batchFourProvenance("ep35-triagem-alertas", "CyberCast 35 — Aprofundamento: triagem, priorização e análise de alertas"),
    transcript: [
      { speaker: "Ana", text: "Operações de segurança vivem do que chamamos triagem: o primeiro filtro que separa ruído de sinal nos alertas.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "O primeiro movimento é validar: o alerta corresponde a um evento real? Falso positivo é gatilho que dispara sem ameaça real. Confirmar o evento com dados adicionais, logs de outras fontes, já é triagem.", timestampSeconds: 12 },
      { speaker: "Ana", text: "Depois, priorizar. Não é todo evento confirmado que vira incidente grave. Perguntamos: qual ativo está afetado, qual impacto teria a exploração, há sinais de movimento lateral ou exfiltração?", timestampSeconds: 26 },
      { speaker: "Rafael", text: "E contexto decide muito: um mesmo alerta em um servidor crítico exposto tem peso diferente do que em uma estação de teste. Inventário, criticidade do ativo e o papel do usuário enriquecem a decisão.", timestampSeconds: 41 },
      { speaker: "Ana", text: "A regra operacional que orienta tudo: preservar antes de agir. Em sistemas sensíveis, não reinicie, não apague, não corrija antes de garantir que evidências e logs de memória estão protegidos.", timestampSeconds: 56 },
      { speaker: "Rafael", text: "E a pegadinha da prova: urgência não substitui método. Responder rápido sem triagem correta gera resposta errada, e resposta errada pode apagar a evidência que sustentaria a investigação.", timestampSeconds: 71 },
    ],
  },
  {
    id: "ep36-soc-equipe",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 36,
    title: "Aprofundamento: papéis, playbooks e comunicação no SOC",
    description: "Ana e Rafael descrevem a organização de um SOC: quem faz o quê, como os playbooks orientam e como escalar corretamente.",
    audioUrl: "/manus-storage/ep36-soc-equipe_18a106c4.wav",
    duration: "1m26s",
    topics: ["papéis no SOC", "playbooks de resposta", "escalonamento", "comunicação de incidente", "pegadinhas"],
    examWeight: "28% do exame",
    provenance: batchFourProvenance("ep36-soc-equipe", "CyberCast 36 — Aprofundamento: papéis, playbooks e comunicação no SOC"),
    transcript: [
      { speaker: "Ana", text: "Um SOC eficiente é organizado em camadas humanas: analistas de primeiro nível triam, analistas de segundo nível investigam em profundidade e especialistas resolvem ameaças avançadas.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "O playbook é o guia de cada tipo de incidente: quais passos tomar, em qual ordem, quem acionar. Ele garante consistência quando o estresse é alto e a memória falha.", timestampSeconds: 13 },
      { speaker: "Ana", text: "E o escalonamento tem dois sentidos: horizontal, para colegas com outra especialidade, e vertical, para a liderança quando o impacto é crítico ou a decisão exige autoridade. Escalar cedo não é fraqueza, é disciplina.", timestampSeconds: 28 },
      { speaker: "Rafael", text: "A comunicação também é controle: comunicar com a linguagem certa, para o público certo, no momento certo. Técnica para a equipe, impacto e ação para a liderança, sem especulação para fora.", timestampSeconds: 43 },
      { speaker: "Ana", text: "E o aprendizado pós-incidente: a lição aprendida transforma cada ocorrência em melhoria de playbook, de detecção e de processo. O SOC que não revisa repete o mesmo erro na próxima crise.", timestampSeconds: 58 },
      { speaker: "Rafael", text: "Resumo do episódio: papéis definidos, playbooks seguidos, escalonamento consciente e comunicação controlada. É essa estrutura que transforma esforço individual em capacidade organizacional.", timestampSeconds: 72 },
    ],
  },
  {
    id: "ep37-risco-negocio",
    domainCode: "DOM5",
    domainTitle: "Program Management, Governance & Compliance",
    episodeNumber: 37,
    title: "Aprofundamento: análise quantitativa e qualitativa de risco",
    description: "Ana e Rafael detalham os cálculos de risco quantitativo e as abordagens qualitativas usadas para decidir investimento em segurança.",
    audioUrl: "/manus-storage/ep37-risco-negocio_9e369446.wav",
    duration: "1m33s",
    topics: ["ALE, SLE, ARO e EF", "análise quantitativa vs qualitativa", "apetite de risco", "decisões de investimento", "pegadinhas"],
    examWeight: "20% do exame",
    provenance: batchFourProvenance("ep37-risco-negocio", "CyberCast 37 — Aprofundamento: análise quantitativa e qualitativa de risco"),
    transcript: [
      { speaker: "Ana", text: "O cálculo de risco dá densidade de prova hoje. O caminho quantitativo usa números: perda de exposição, taxa de ocorrência e o custo anual esperado.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "A fórmula central: a perda de exposição única vezes a taxa anual de ocorrência resulta na perda anual esperada. Ou seja, SLE vezes ARO resulta em ALE. Esse número justifica investimento em controle.", timestampSeconds: 14 },
      { speaker: "Ana", text: "Exemplo rápido: um servidor cuja perda total custa dez mil reais, com evento esperado duas vezes ao ano, tem uma perda anual esperada de vinte mil reais. Um controle que custa menos e reduz o evento se paga sozinho.", timestampSeconds: 30 },
      { speaker: "Rafael", text: "A abordagem qualitativa não calcula em dinheiro: classifica risco como alto, médio ou baixo, combinando probabilidade e impacto em matrizes. É mais rápida, subjetiva e útil para priorizar quando os dados não existem.", timestampSeconds: 46 },
      { speaker: "Ana", text: "E o apetite de risco define o limite que a organização aceita. A resposta ao risco que passa do limite pode ser mitigar, transferir, evitar ou aceitar. Aceitar não é ignorar: é decisão documentada da liderança.", timestampSeconds: 62 },
      { speaker: "Rafael", text: "A pegadinha clássica: ALE não é o que o incidente custa, é o que ele custa em média por ano. Comparar controle com ALE só faz sentido quando as unidades de tempo batem.", timestampSeconds: 78 },
    ],
  },
  {
    id: "ep38-politicas-terceiros",
    domainCode: "DOM5",
    domainTitle: "Program Management, Governance & Compliance",
    episodeNumber: 38,
    title: "Aprofundamento: políticas, privacidade e proteção de dados",
    description: "Ana e Rafael mostram como políticas de privacidade, prevenção de perda de dados e gestão de terceiros protegem informações sensíveis.",
    audioUrl: "/manus-storage/ep38-politicas-terceiros_5a761eb3.wav",
    duration: "1m28s",
    topics: ["políticas de privacidade", "prevenção de perda de dados", "gestão de terceiros", "requisitos legais", "pegadinhas"],
    examWeight: "20% do exame",
    provenance: batchFourProvenance("ep38-politicas-terceiros", "CyberCast 38 — Aprofundamento: políticas, privacidade e proteção de dados"),
    transcript: [
      { speaker: "Ana", text: "Políticas de privacidade e proteção de dados fecham o quinto domínio. Começamos pela base: a política de privacidade define como a organização coleta, usa, compartilha e protege dados pessoais.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "A prevenção de perda de dados é o braço técnico: controlar cópia, transferência e envio de informação sensível, bloqueando e-mail com cartão de crédito, arquivo confidencial em USB e dados para fora do ambiente autorizado.", timestampSeconds: 15 },
      { speaker: "Ana", text: "E a gestão de terceiros é o flanco esquecido: fornecedores com acesso aos nossos sistemas, nuvem compartilhada, parceiros com dados. Cada um precisa de avaliação, contrato com requisitos de segurança e monitoramento contínuo.", timestampSeconds: 31 },
      { speaker: "Rafael", text: "O risco de terceiros não é opcional: a prova trata fornecedor inseguro como extensão da própria superfície de ataque. Due diligence antes do contrato, acordo de nível de serviço durante, auditoria quando necessário.", timestampSeconds: 47 },
      { speaker: "Ana", text: "Requisitos legais e regulatórios também entram aqui: a organização precisa identificar quais normas se aplicam, implementar os controles exigidos e manter evidências de conformidade.", timestampSeconds: 61 },
      { speaker: "Rafael", text: "E a pegadinha: privacidade não é só segurança da informação. Dados podem estar tecnicamente seguros e ainda violar privacidade se forem usados além do consentido. Escopos diferentes, controles diferentes.", timestampSeconds: 75 },
    ],
  },
  {
    id: "ep39-dia-a-dia-securityplus",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 39,
    title: "Aprofundamento: do certificado ao trabalho real",
    description: "Ana e Rafael conectam o conhecimento do Security+ às rotinas reais de segurança: SOC, administração e projetos.",
    audioUrl: "/manus-storage/ep39-dia-a-dia-securityplus_1094550e.wav",
    duration: "1m24s",
    topics: ["aplicação prática do conteúdo", "rotina de segurança", "documentação e evidência", "evolução contínua", "pegadinhas"],
    examWeight: "28% do exame",
    provenance: batchFourProvenance("ep39-dia-a-dia-securityplus", "CyberCast 39 — Aprofundamento: do certificado ao trabalho real"),
    transcript: [
      { speaker: "Ana", text: "Nosso penúltimo episódio conecta tudo o que estudamos ao trabalho real. A certificação abre a porta, mas é a aplicação diária que constrói a carreira.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "No dia a dia, o conteúdo vira rotina: revisar alertas com método, atualizar sistemas e corrigir vulnerabilidades por criticidade, checar backups e testes de restauração, e documentar tudo com evidência.", timestampSeconds: 13 },
      { speaker: "Ana", text: "Documentação é competência profissional, não burocracia. A evidência sustenta auditorias, transfere conhecimento, protege decisões e transforma aprendizado individual em capacidade de equipe.", timestampSeconds: 27 },
      { speaker: "Rafael", text: "E os processos que estudamos ganham vida: a mudança controlada vira janela de manutenção, o controle de acesso vira revisão de contas, e a resposta a incidente vira playbook testado.", timestampSeconds: 41 },
      { speaker: "Ana", text: "A mentalidade que diferencia profissionais: pensar em causa, não em sintoma. O alerta repetido aponta falha de processo, não apenas um evento a fechar.", timestampSeconds: 54 },
      { speaker: "Rafael", text: "E a evolução contínua: a área muda rápido, novas ameaças, novas ferramentas, novos frameworks. Estudar em ciclo, praticar em laboratório e aplicar no trabalho é o movimento que sustenta a carreira.", timestampSeconds: 66 },
    ],
  },
  {
    id: "ep40-revisao-final-serie",
    domainCode: "DOM5",
    domainTitle: "Program Management, Governance & Compliance",
    episodeNumber: 40,
    title: "Revisão final: os cinquenta pontos que sustentam a série",
    description: "Ana e Rafael fecham a série com uma revisão acelerada dos conceitos essenciais de todos os domínios.",
    audioUrl: "/manus-storage/ep40-revisao-final-serie_c95375d1.wav",
    duration: "1m32s",
    topics: ["revisão integrada", "mapa mental dos domínios", "conceitos-chave consolidados", "mentalidade profissional", "encerramento"],
    examWeight: "20% do exame",
    provenance: batchFourProvenance("ep40-revisao-final-serie", "CyberCast 40 — Revisão final: os cinquenta pontos que sustentam a série"),
    transcript: [
      { speaker: "Ana", text: "Última revisão da série. Vamos percorrer os conceitos que sustentam tudo, um domínio por vez, de forma acelerada.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Domínio um: controle certo para problema certo, com categorias e tipos; a tríade protege confidencialidade, integridade e disponibilidade; autenticação identifica, autorização decide, contabilidade registra; Zero Trust não confia em nada, verifica tudo; e criptografia, hash e assinatura têm papéis distintos.", timestampSeconds: 10 },
      { speaker: "Ana", text: "Domínio dois: conhecer o ator, o vetor e a tática; vulnerabilidade é a brecha, exploit é o meio, mitigação é a redução; e a prova cobra a resposta que trata a causa mais próxima, não a mais famosa.", timestampSeconds: 29 },
      { speaker: "Rafael", text: "Domínio três: arquitetura é desenho deliberado: segmentação, zonas de confiança, defesa em camadas; identidade é o novo perímetro; nuvem traz responsabilidade compartilhada; e resiliência se planeja com backup testado e métricas de recuperação.", timestampSeconds: 42 },
      { speaker: "Ana", text: "Domínio quatro, o mais pesado da prova: monitorar para detectar, detectar para triar, triar para priorizar, priorizar para preservar, e preservar antes de agir. A ordem importa, a evidência vale ouro.", timestampSeconds: 57 },
      { speaker: "Rafael", text: "Domínio cinco: governança dá direção, risco define limites, conformidade prova o piso. Políticas orientam, controles executam, auditoria verifica e métricas contam a história real do programa.", timestampSeconds: 70 },
      { speaker: "Ana", text: "A série inteira em uma frase: segurança é decisão treinada, construída em camadas, sustentada por evidência e evoluída em ciclo contínuo.", timestampSeconds: 84 },
      { speaker: "Rafael", text: "Obrigado, Ana, e obrigado a quem estudou com a gente até aqui. Que a preparação vire aprovação, e a aprovação vire prática.", timestampSeconds: 93 },
    ],
  },
];
