import type { PodcastEpisode } from "./podcastEpisodes";
import type { ContentProvenanceItem } from "./contentProvenance";
import type { PodcastTimestampedLine } from "./podcastBatchFourEpisodes";

type PodcastTimestamped = readonly PodcastTimestampedLine[];

const seasonTwoProvenance = (id: string, title: string): ContentProvenanceItem => ({
  id: `podcast-${id}`,
  origin: "proprio",
  category: "Podcast educacional próprio",
  title,
  source: "CyberDimension Academy",
  license: "Conteúdo autoral da CyberDimension Academy; uso de estudo dentro da plataforma.",
  usage: "Diálogo autoral em áudio e transcrição acessível da segunda temporada do CyberCast Security+.",
});

export const podcastSeasonTwoEpisodes: readonly PodcastEpisode[] = [
  {
    id: "ep41-ctf-hacking-etico-labs",
    domainCode: "DOM4",
    domainTitle: "Security Operations (Carreira)",
    episodeNumber: 41,
    title: "Carreira: laboratórios, CTFs e a porta do hacking ético",
    description: "Ana e Rafael mostram como começar com segurança ofensiva de forma responsável: plataformas de laboratório, competições e a mentalidade certa.",
    audioUrl: "/manus-storage/ep41-ctf-hacking-etico-labs_5d5bf3a3.wav",
    duration: "1m33s",
    topics: ["plataformas de laboratório", "CTFs e wargames", "hacking ético responsável", "primeiros passos ofensivos", "pegadinhas"],
    examWeight: "Extra Security+",
    provenance: seasonTwoProvenance("ep41-ctf-hacking-etico-labs", "CyberCast 41 — Carreira: laboratórios, CTFs e a porta do hacking ético"),
    transcript: [
      { speaker: "Ana", text: "Temporada dois, Rafael! Hoje a gente começa a abrir a porta da segurança ofensiva: laboratórios, CTFs e o caminho do hacking ético.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Sempre que vejo hacker em filme fico tentado a tentar. Por onde alguém começa sem derrubar o sistema da escola, por exemplo?", timestampSeconds: 11 },
      { speaker: "Ana", text: "Com ambientes isolados e autorizados: máquinas virtuais no seu próprio computador, plataformas como TryHackMe e HackTheBox Academy, e laboratórios próprios. Regra de ouro: jamais testar em sistemas sem autorização expressa.", timestampSeconds: 22 },
      { speaker: "Rafael", text: "E CTF é captura da bandeira, certo? Aqueles desafios onde você resolve problemas de criptografia, web e forense para achar uma string secreta.", timestampSeconds: 35 },
      { speaker: "Ana", text: "Isso. E CTFs têm categorias: jeopárdia, com desafios variados, e ataque e defesa, onde times se enfrentam em tempo real. São ótimas para aprender lendo o write-up de cada desafio resolvido.", timestampSeconds: 47 },
      { speaker: "Rafael", text: "Anotei: ambiente controlado, prática deliberada e aprendizado por explicação. O hacking ético precisa dessa estrutura toda para não virar dano real.", timestampSeconds: 59 },
      { speaker: "Ana", text: "E a prova valoriza esse pensamento: a ação responsável é autorizada, documentada e delimitada por escopo. Tudo o que não se encaixa nisso é crime, não carreira.", timestampSeconds: 71 },
      { speaker: "Rafael", text: "Então eu treino aqui dentro da caixinha de laboratório até estar pronto para o mundo real. Fechado, Ana!", timestampSeconds: 83 },
    ],
  },
  {
    id: "ep42-red-team-basics",
    domainCode: "DOM2",
    domainTitle: "Threats, Vulnerabilities & Mitigations (Carreira)",
    episodeNumber: 42,
    title: "Carreira: os primeiros passos do pentest responsável",
    description: "Ana e Rafael percorrem as fases de um teste de intrusão: reconhecimento, enumeração, exploração responsável e o relatório que transforma achado em correção.",
    audioUrl: "/manus-storage/ep42-red-team-basics_9e94f74d.wav",
    duration: "1m34s",
    topics: ["fases do pentest", "reconhecimento e enumeração", "exploração responsável", "relatório de pentest", "pegadinhas"],
    examWeight: "Extra Security+",
    provenance: seasonTwoProvenance("ep42-red-team-basics", "CyberCast 42 — Carreira: os primeiros passos do pentest responsável"),
    transcript: [
      { speaker: "Ana", text: "Hoje vamos simular o trabalho de quem testa defesas: o pentest estruturado, do primeiro contato até o relatório final.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Por onde começa um pentest? Imagino que não é chutando senhas na porta do cliente.", timestampSeconds: 11 },
      { speaker: "Ana", text: "Começa no escopo e na autorização por escrito. Depois vem o reconhecimento passivo: reunir informações públicas sem tocar no alvo. Em seguida a enumeração, que interage com o alvo para mapear portas, serviços e versões.", timestampSeconds: 21 },
      { speaker: "Rafael", text: "E aí vem a exploração: provar que a vulnerabilidade existe. Mas com cuidado, certo? O objetivo é demonstrar risco, não causar dano.", timestampSeconds: 35 },
      { speaker: "Ana", text: "Exato. Teste de exploração não deve derrubar serviços, vazar dados de terceiros ou ir além do escopo. E toda evidência precisa de registro: capturas, comandos e horários.", timestampSeconds: 45 },
      { speaker: "Rafael", text: "Porque o relatório é o produto final do pentest, não o exploit em si. Ele traduz achados técnicos em risco para o negócio, com severidade, evidência e recomendação de correção.", timestampSeconds: 58 },
      { speaker: "Ana", text: "Perfeito. E a pegadinha clássica: a diferença entre varredura e pentest. A varredura acha portas abertas; o pentest prova o impacto real. Ferramenta acha sintoma, o analista confirma a doença.", timestampSeconds: 70 },
      { speaker: "Rafael", text: "Mais uma razão para estudar com calma. Reconhecimento, enumeração, prova controlada e relatório que corrige.", timestampSeconds: 84 },
    ],
  },
  {
    id: "ep43-blue-team-analista",
    domainCode: "DOM4",
    domainTitle: "Security Operations (Carreira)",
    episodeNumber: 43,
    title: "Carreira: o dia a dia do analista de segurança júnior",
    description: "Ana e Rafael simulam um dia de triagem no SOC: da fila de alertas à decisão de escalonar, com casos práticos e o que realmente importa no início da carreira.",
    audioUrl: "/manus-storage/ep43-blue-team-analista_48b26984.wav",
    duration: "1m29s",
    topics: ["fila de alertas do SOC", "triagem prática", "quando escalonar", "casos reais de triagem", "pegadinhas"],
    examWeight: "Extra Security+",
    provenance: seasonTwoProvenance("ep43-blue-team-analista", "CyberCast 43 — Carreira: o dia a dia do analista de segurança júnior"),
    transcript: [
      { speaker: "Ana", text: "Vamos viver um dia de analista júnior de segurança. Imagine a fila de alertas do SOC e um plantão que está começando.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Primeira tarefa do dia: olhar a fila. Como decido o que ataco primeiro?", timestampSeconds: 11 },
      { speaker: "Ana", text: "Pela combinação de severidade e contexto: um alerta de credential stuffing contra uma conta de administrador vale mais que cinquenta alertas genéricos de port scan.", timestampSeconds: 19 },
      { speaker: "Rafael", text: "Recebi um alerta de login fora do horário em uma conta de diretoria. Primeiros passos: checar se é legítimo, procurar o contexto de geolocalização e dispositivo, e cruzar com o playbook.", timestampSeconds: 32 },
      { speaker: "Ana", text: "E se confirmar que é suspeito, não age sozinho: bloqueia a sessão conforme o playbook, preserva os logs e escala para o nível dois. O júnior classifica e contém; o senior confirma e investiga a fundo.", timestampSeconds: 46 },
      { speaker: "Rafael", text: "E um alerta que parece falso positivo? Não posso só ignorar, preciso documentar a justificativa para que a equipe possa ajustar o tuner da detecção.", timestampSeconds: 60 },
      { speaker: "Ana", text: "Isso. Falso positivo documentado melhora a qualidade do SOC inteiro. E a pegadinha de carreira: pressa não é produtividade em segurança. Um alert ignorado sem registro vale menos que um alert atendido com calma.", timestampSeconds: 73 },
      { speaker: "Rafael", text: "Anotado: classificar com contexto, conter com playbook, escalar com evidência e registrar tudo.", timestampSeconds: 87 },
    ],
  },
  {
    id: "ep44-cloud-praticas",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 44,
    title: "Aprofundamento: nuvem na prática, configurações e IaC seguros",
    description: "Ana e Rafael analisam os erros mais comuns de nuvem: buckets expostos, IAM generoso e infraestrutura como código sem segurança.",
    audioUrl: "/manus-storage/ep44-cloud-praticas_71096171.wav",
    duration: "1m23s",
    topics: ["misconfiguração de nuvem", "IAM e buckets", "CIS Benchmarks", "IaC escaneado", "pegadinhas"],
    examWeight: "18% do exame",
    provenance: seasonTwoProvenance("ep44-cloud-praticas", "CyberCast 44 — Aprofundamento: nuvem na prática, configurações e IaC seguros"),
    transcript: [
      { speaker: "Ana", text: "Nuvem é o terceiro domínio, e hoje vamos aos erros que mais aparecem em incidentes reais: configurações erradas, não falhas do provedor.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "O clássico: bucket de armazenamento público com dados sensíveis. O serviço funciona, mas a permissão está errada.", timestampSeconds: 12 },
      { speaker: "Ana", text: "Exato. O provedor dá a ferramenta, você define a política. Por isso a pegadinha: em modelo IaaS e PaaS, a segurança da configuração é sempre do cliente, mesmo que o disco físico seja do provedor.", timestampSeconds: 23 },
      { speaker: "Rafael", text: "E o segundo erro comum: IAM generoso. Conta de serviço com permissão de administrador para simplificar o deploy.", timestampSeconds: 37 },
      { speaker: "Ana", text: "Que vira a porta de entrada quando a chave vaza. A resposta correta é o menor privilégio com rotação de credenciais e auditoria de uso. E para prevenir: CIS Benchmarks e varreduras de configuração contínua, como CSPM.", timestampSeconds: 47 },
      { speaker: "Rafael", text: "E quando a infraestrutura é código, a segurança também entra no código: escanear templates de IaC no pipeline, igual varredura estática de aplicação.", timestampSeconds: 62 },
      { speaker: "Ana", text: "Feche a lógica: nuvem segura não é nuvem sem erro humano, é nuvem com verificação automática de cada mudança. A ferramenta muda, o princípio de verificação permanece.", timestampSeconds: 75 },
    ],
  },
  {
    id: "ep45-zero-trust-aplicado",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 45,
    title: "Aprofundamento: zero trust na prática, do conceito à microsegmentação",
    description: "Ana e Rafael traduzem zero trust para a arquitetura real: verificação contínua, microsegmentação, mTLS e a diferença entre ZTNA e VPN.",
    audioUrl: "/manus-storage/ep45-zero-trust-aplicado_56cecf9e.wav",
    duration: "1m28s",
    topics: ["verificação contínua", "microsegmentação", "mTLS", "ZTNA vs VPN", "pegadinhas"],
    examWeight: "18% do exame",
    provenance: seasonTwoProvenance("ep45-zero-trust-aplicado", "CyberCast 45 — Aprofundamento: zero trust na prática, do conceito à microsegmentação"),
    transcript: [
      { speaker: "Ana", text: "Zero trust virou palavra de ordem, Rafael. Vamos tirar do slogan e colocar na arquitetura: nunca confiar, sempre verificar.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Na prática, isso significa que o acesso não depende da rede, mas da identidade e do contexto: quem você é, de onde, com que dispositivo e por quê.", timestampSeconds: 12 },
      { speaker: "Ana", text: "E verificação contínua: a sessão autenticada às nove da manhã não continua confiável às três da tarde. Comportamento, geolocalização e risco reavaliam o acesso o tempo todo.", timestampSeconds: 25 },
      { speaker: "Rafael", text: "Dentro da rede, a técnica mais concreta é a microsegmentação: dividir a rede em zonas pequenas, cada serviço só fala com quem precisa, e a comunicação é cifrada de ponta a ponta com mTLS.", timestampSeconds: 39 },
      { speaker: "Ana", text: "E a pergunta de prova que aparece sempre: ZTNA não é VPN. VPN conecta você à rede inteira; ZTNA conecta você só ao recurso autorizado, sem expor a rede.", timestampSeconds: 53 },
      { speaker: "Rafael", text: "Então VPN dá acesso amplo por túnel, ZTNA dá acesso mínimo por política. Zero trust é a política; VPN ou ZTNA são apenas transportes.", timestampSeconds: 66 },
      { speaker: "Ana", text: "E a pegadinha final: zero trust não é um produto que se compra, é um modelo de arquitetura que se implementa em camadas, começando pela identidade.", timestampSeconds: 79 },
    ],
  },
  {
    id: "ep46-appsec-owasp",
    domainCode: "DOM2",
    domainTitle: "Threats, Vulnerabilities & Mitigations",
    episodeNumber: 46,
    title: "Aprofundamento: OWASP Top 10 na prática, as falhas que vivem em produção",
    description: "Ana e Rafael percorrem as falhas web mais exploradas: injeções, autenticação quebrada, SSRF, CSRF e como cada uma se fecha.",
    audioUrl: "/manus-storage/ep46-appsec-owasp_60042eb9.wav",
    duration: "1m44s",
    topics: ["OWASP Top 10", "injeção e validação", "autenticação quebrada", "SSRF e CSRF", "pegadinhas"],
    examWeight: "22% do exame",
    provenance: seasonTwoProvenance("ep46-appsec-owasp", "CyberCast 46 — Aprofundamento: OWASP Top 10 na prática, as falhas que vivem em produção"),
    transcript: [
      { speaker: "Ana", text: "Aplicações web são o alvo mais comum, e o OWASP Top 10 mapeia as falhas mais críticas. Vamos às que mais caem em prova e em incidente real.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "A rainha histórica: injeção. SQL injection quando a entrada do usuário vira parte do comando do banco sem sanitização.", timestampSeconds: 12 },
      { speaker: "Ana", text: "A resposta certa quase sempre é a mesma: query parametrizada e validação de entrada. Sanitizar ajuda, mas o parâmetro isolado é a defesa de raiz.", timestampSeconds: 24 },
      { speaker: "Rafael", text: "E autenticação quebrada: senhas fracas, sessão que não expira, ausência de MFA. O atacante não quebra a criptografia, quebra a rotina de acesso.", timestampSeconds: 36 },
      { speaker: "Ana", text: "SSRF é mais sutil: a aplicação é convencida a fazer requisição por você. O atacante não acessa o serviço interno, ele pede para a própria aplicação acessar. A defesa é lista permitida de destinos e não expor funções internas.", timestampSeconds: 49 },
      { speaker: "Rafael", text: "E CSRF engana o navegador autenticado: o site malicioso usa sua sessão ativa para fazer uma ação que você não pediu. A defesa clássica é o token anti-CSRF em cada formulário.", timestampSeconds: 63 },
      { speaker: "Ana", text: "A pegadinha da prova: XSS reflete código no navegador da vítima; CSRF usa a sessão dela sem tocar no código. São ataques primos, mas defesas diferentes: escape de saída para um, token para o outro.", timestampSeconds: 77 },
      { speaker: "Rafael", text: "Falhas web têm padrão: entrada sem validação, sessão sem controle, confiança indevida no navegador. Fechou o trio.", timestampSeconds: 91 },
    ],
  },
  {
    id: "ep47-ia-seguranca",
    domainCode: "DOM2",
    domainTitle: "Threats, Vulnerabilities & Mitigations (Avançado)",
    episodeNumber: 47,
    title: "Aprofundamento: quando a IA ataca e quando ela defende",
    description: "Ana e Rafael discutem os novos vetores da era da IA: deepfakes, injeção de prompt, e como as equipes usam IA para defender.",
    audioUrl: "/manus-storage/ep47-ia-seguranca_22f655d2.wav",
    duration: "1m27s",
    topics: ["deepfake e engenharia social", "prompt injection", "IA na defesa", "LLM guardrails", "pegadinhas"],
    examWeight: "Extra Security+",
    provenance: seasonTwoProvenance("ep47-ia-seguranca", "CyberCast 47 — Aprofundamento: quando a IA ataca e quando ela defende"),
    transcript: [
      { speaker: "Ana", text: "A prova ainda não cobra isso em profundidade, mas o mercado já vive: inteligência artificial mudou tanto o ataque quanto a defesa.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Pelo lado do ataque, o mais visível é o deepfake: voz e vídeo falsos usados para enganar. O caso clássico é o falso CEO pedindo transferência urgente.", timestampSeconds: 12 },
      { speaker: "Ana", text: "E a defesa é processo, não tecnologia: qualquer pedido sensível fora do canal formal precisa de verificação por segundo fator humano. Confirmação fora da banda.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "E o vetor novo dentro das próprias ferramentas: injeção de prompt, quando o atacante esconde instruções maliciosas dentro do dado que o modelo processa.", timestampSeconds: 39 },
      { speaker: "Ana", text: "Por isso os guardrails: camadas que validam a entrada e a saída do modelo, filtros de conteúdo, limites de acesso e monitoramento de abuso. O LLM é um sistema de software e precisa dos mesmos controles.", timestampSeconds: 52 },
      { speaker: "Rafael", text: "E do lado da defesa, a IA acelera a triagem: correlação de alertas, resumo de incidentes, busca de padrões. Mas ela também erra, então a decisão crítica continua humana.", timestampSeconds: 66 },
      { speaker: "Ana", text: "A pegadinha de hoje: a IA não criou ameaça nova em essência, ela aumentou escala, velocidade e convinção. O princípio de verificação independente permanece a melhor resposta.", timestampSeconds: 80 },
    ],
  },
  {
    id: "ep48-carreira-cyber",
    domainCode: "DOM5",
    domainTitle: "Security Program Management (Carreira)",
    episodeNumber: 48,
    title: "Carreira: o primeiro emprego em cibersegurança",
    description: "Ana e Rafael montam o kit de entrada no mercado: portfólio, certificações, comunidade e como se apresentar na entrevista.",
    audioUrl: "/manus-storage/ep48-carreira-cyber_bf9810f1.wav",
    duration: "1m29s",
    topics: ["portfólio e projetos", "certificações de entrada", "comunidade e networking", "entrevistas", "pegadinhas"],
    examWeight: "Extra Security+",
    provenance: seasonTwoProvenance("ep48-carreira-cyber", "CyberCast 48 — Carreira: o primeiro emprego em cibersegurança"),
    transcript: [
      { speaker: "Ana", text: "Últimos episódios da temporada, então hoje o tema que mais recebo: como entrar no mercado de cibersegurança sem experiência.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "A resposta curta que ninguém gosta: experiência vem de evidência. E evidência a gente constrói: laboratórios documentados, write-ups de CTF, projetos de portfólio.", timestampSeconds: 12 },
      { speaker: "Ana", text: "Exato. Um repositório com scripts seus, relatórios de laboratório e explicações claras vale mais que dez certificados no currículo. Certificado abre a porta; portfólio faz você entrar.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "E as certificações de entrada ainda importam? Security+ vale a pena como primeira?", timestampSeconds: 39 },
      { speaker: "Ana", text: "Vale. Ela organiza o vocabulário e é filtro comum em vagas júnior, inclusive governamentais nos Estados Unidos com a trilha DoD. Mas nunca substitui a prática.", timestampSeconds: 47 },
      { speaker: "Rafael", text: "Comunidade: meetups, grupos, eventos e redes profissionais. Quem participa aprende duas vezes: o conteúdo e o contexto de como as equipes trabalham.", timestampSeconds: 60 },
      { speaker: "Ana", text: "E na entrevista, a pegadinha de carreira: não finja saber tudo. O profissional júnior que admite o que não sabe e mostra como vai aprender é mais confiável que o que inventa resposta.", timestampSeconds: 73 },
      { speaker: "Rafael", text: "Portfólio com evidência, certificação como organizador, comunidade como acelerador e honestidade como credencial.", timestampSeconds: 87 },
    ],
  },
  {
    id: "ep49-tendencias-futuro",
    domainCode: "DOM5",
    domainTitle: "Security Program Management (Avançado)",
    episodeNumber: 49,
    title: "Aprofundamento: tendências, supply chain e o futuro da profissão",
    description: "Ana e Rafael olham para frente: segurança da cadeia de suprimentos, computação quântica, LGPD e como a profissão evolui.",
    audioUrl: "/manus-storage/ep49-tendencias-futuro_a1bef5fc.wav",
    duration: "1m20s",
    topics: ["supply chain security", "ameaça quântica", "LGPD e privacidade", "futuro da profissão", "pegadinhas"],
    examWeight: "14% do exame",
    provenance: seasonTwoProvenance("ep49-tendencias-futuro", "CyberCast 49 — Aprofundamento: tendências, supply chain e o futuro da profissão"),
    transcript: [
      { speaker: "Ana", text: "Para fechar a temporada com visão de futuro: três tendências que o profissional de hoje precisa acompanhar desde já.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Primeira: segurança da cadeia de suprimentos de software. O ataque à SolarWinds mostrou que o fornecedor confiável pode ser o vetor.", timestampSeconds: 11 },
      { speaker: "Ana", text: "E a resposta prática cresceu: SBOM, a lista de materiais de software, assinatura de artefatos e verificação da proveniência de cada dependência antes do deploy.", timestampSeconds: 23 },
      { speaker: "Rafael", text: "Segunda: a ameaça quântica. Computadores quânticos ainda não quebram criptografia em produção, mas dados cifrados hoje podem ser capturados e decifrados amanhã.", timestampSeconds: 36 },
      { speaker: "Ana", text: "Harvest now, decrypt later. Por isso existe a criptografia pós-quântica em padrão: algoritmos novos, como o ML-KEM do NIST, já recomendados para dados sensíveis de longa vida.", timestampSeconds: 49 },
      { speaker: "Rafael", text: "Terceira: privacidade virou requisito de segurança, não só jurídico. LGPD no Brasil impõe base legal, minimização de dados e notificação de incidentes. O profissional técnico precisa entender isso.", timestampSeconds: 62 },
      { speaker: "Ana", text: "E a conclusão de carreira: a profissão não vai substituir o humano, vai substituir quem não se atualiza. A base dos fundamentos que estudamos aqui permanece; as ferramentas em cima mudam rápido.", timestampSeconds: 78 },
    ],
  },
  {
    id: "ep50-encerramento-temporada",
    domainCode: "DOM5",
    domainTitle: "Security Program Management",
    episodeNumber: 50,
    title: "Encerramento: o mapa da segunda temporada e o que vem depois",
    description: "Ana e Rafael fecham a temporada 2: recapitulam laboratórios, ofensiva, defensiva, nuvem, zero trust, appsec, IA, carreira e futuro, e apontam os próximos estudos.",
    audioUrl: "/manus-storage/ep50-encerramento-temporada_2f58d2c6.wav",
    duration: "1m50s",
    topics: ["recapitulação da temporada 2", "mapa de estudos", "próximos passos", "encerramento", "pegadinhas"],
    examWeight: "Extra Security+",
    provenance: seasonTwoProvenance("ep50-encerramento-temporada", "CyberCast 50 — Encerramento: o mapa da segunda temporada e o que vem depois"),
    transcript: [
      { speaker: "Ana", text: "Episódio cinquenta, Rafael. Última conversa da temporada dois. Vamos costurar tudo que aprendemos aqui.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Começamos pela porta da ofensiva: laboratórios controlados, CTFs e o pentest com escopo, prova e relatório. Aprendemos que responsabilidade é o que separa o profissional do criminoso.", timestampSeconds: 12 },
      { speaker: "Ana", text: "Do outro lado, o dia a dia defensivo: triagem com contexto, contenção com playbook e escalonamento com evidência. A qualidade de um SOC se mede pela documentação.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "Arquitetura ganhou peso: nuvem com configuração verificada, IaC escaneado, zero trust com verificação contínua e ZTNA no lugar do acesso amplo.", timestampSeconds: 39 },
      { speaker: "Ana", text: "E o código que vive em produção: injeção fechada com parâmetro, sessão protegida, SSRF contido e CSRF com token. As defesas são específicas porque os ataques são específicos.", timestampSeconds: 51 },
      { speaker: "Rafael", text: "O futuro entrou na conversa: IA que escala ataque e defesa, cadeia de suprimentos com SBOM, criptografia pós-quântica e privacidade como requisito técnico.", timestampSeconds: 64 },
      { speaker: "Ana", text: "E o caminho de carreira: evidência antes de certificado, prática antes de teoria, honestidade antes de pose. O profissional se constrói em ciclos, como a segurança.", timestampSeconds: 77 },
      { speaker: "Rafael", text: "Fica o mapa para estudar depois: aprofundar em SIEM, cloud e appsec, entrar em laboratórios e comunidades, e transformar o que ouvimos aqui em prática real.", timestampSeconds: 89 },
      { speaker: "Ana", text: "Então é isso. Obrigado a cada ouvinte que chegou até aqui. Que a jornada continue, a cada episódio, mais perto da aprovação e da prática.", timestampSeconds: 99 },
    ],
  },
];
