import type { ContentProvenanceItem } from "./contentProvenance";
import type { PodcastEpisode } from "./podcastEpisodes";

const supplementalProvenance = (id: string, title: string): ContentProvenanceItem => ({
  id: `podcast-${id}`,
  origin: "proprio",
  category: "Podcast educacional próprio",
  title,
  source: "CyberDimension Academy",
  license: "Conteúdo autoral da CyberDimension Academy; uso de estudo dentro da plataforma.",
  usage: "Diálogo complementar em áudio e transcrição acessível para revisão por cenários da CompTIA Security+ SY0-701.",
});

export const podcastDeepDiveEpisodes: readonly PodcastEpisode[] = [
  {
    id: "ep06-general-security-scenarios",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 6,
    title: "Revisão por cenários: controles, identidade e confiança",
    description: "Ana e Rafael resolvem cenários curtos de controles, CIA, AAA, Zero Trust, mudanças e criptografia para transformar conceitos em decisão de prova.",
    duration: "~5 min",
    audioUrl: "/manus-storage/ep06-general-security-scenarios_50a74a80.wav",
    topics: ["controle compensatório", "CIA", "MFA e federação", "RBAC e ABAC", "PKI", "gestão de mudanças"],
    examWeight: "12% do exame",
    provenance: supplementalProvenance("ep06-general-security-scenarios", "CyberCast 06 — Revisão por cenários: controles, identidade e confiança"),
    transcript: [
      { speaker: "Ana", text: "Vamos treinar o raciocínio do primeiro domínio com cenários, Rafael. A regra é simples: antes de procurar uma sigla, diga qual problema a empresa precisa resolver. Isso evita escolher uma tecnologia famosa para uma necessidade errada." },
      { speaker: "Rafael", text: "Primeiro caso: um sistema antigo não suporta autenticação multifator. A empresa não pode substituí-lo neste trimestre, mas quer reduzir o risco de acesso indevido. As opções são abandonar o sistema, aceitar o risco ou restringir o acesso por VPN, exigir aprovação de gestor e monitorar cada login. Eu escolheria a última opção como controle compensatório." },
      { speaker: "Ana", text: "Certo. A multifator continua sendo desejável, porém controles alternativos reduzem a exposição enquanto a correção estrutural não chega. O ponto de prova é que compensar não significa esquecer: a exceção deve ter risco documentado, responsável definido e data de revisão. Defesa em profundidade é justamente combinar camadas que não dependem de uma única salvaguarda." },
      { speaker: "Rafael", text: "Segundo caso: um usuário alterou um arquivo financeiro sem autorização. A diretoria pergunta qual objetivo da tríade foi afetado. É integridade, porque a preocupação principal é que o dado permaneça correto e completo, não apenas secreto." },
      { speaker: "Ana", text: "Isso. Se o cenário enfatizasse alguém lendo o arquivo sem permissão, seria confidencialidade. Se o sistema ficasse indisponível no fechamento, disponibilidade. Observe o verbo: revelar, alterar ou interromper. Assinatura digital e hash ajudam a verificar integridade; backup e redundância apoiam disponibilidade; criptografia protege confidencialidade, quando bem aplicada." },
      { speaker: "Rafael", text: "E em AAA, se a investigação precisa saber quem apagou uma regra de firewall e quando, o termo é accounting. Autenticação prova a identidade, autorização define a permissão e accounting registra a ação." },
      { speaker: "Ana", text: "Perfeito. Agora uma pegadinha: duas perguntas secretas não são MFA, pois pertencem à mesma categoria, algo que a pessoa sabe. Para MFA, combine categorias, como senha e aplicativo autenticador. Se a questão descreve acesso único a vários sistemas, pense em SSO. Se descreve confiança entre organizações, com um provedor de identidade emitindo asserções, pense em federação." },
      { speaker: "Rafael", text: "E quando o enunciado diz que permissões dependem de cargo, eu marco RBAC. Se mudam conforme cargo, horário, localização, postura do dispositivo e classificação do dado, ABAC é mais preciso." },
      { speaker: "Ana", text: "Exato. Esse segundo caso é também um sinal de Zero Trust: acesso não nasce confiável porque veio da rede interna. O recurso avalia identidade, contexto e risco. Microsegmentação limita alcance; menor privilégio reduz abuso; reavaliação contínua evita confiança permanente." },
      { speaker: "Rafael", text: "Último cenário: uma atualização crítica precisa ir para produção em uma madrugada. A alternativa segura não é instalar imediatamente. Eu procuraria teste, aprovação, janela de mudança, comunicação, monitoramento e plano de reversão." },
      { speaker: "Ana", text: "Muito bem. E se a pergunta trouxer certificado, lembre: a chave privada assina e deve ficar protegida; a chave pública permite verificar a assinatura. A CA vincula identidade a chave pública e o cliente valida cadeia, nome, validade e revogação. Use a técnica de fechar cada questão com uma frase: necessidade, princípio, controle e evidência. É assim que conceitos gerais viram decisão confiável." },
    ],
  },
  {
    id: "ep07-threats-vulnerabilities-scenarios",
    domainCode: "DOM2",
    domainTitle: "Threats & Vulnerabilities",
    episodeNumber: 7,
    title: "Revisão por cenários: da ameaça ao indicador",
    description: "Um exercício dialogado para separar ator, vetor, vulnerabilidade, indicador e resposta proporcional em situações típicas da prova.",
    duration: "~5 min",
    audioUrl: "/manus-storage/ep07-threats-vulnerabilities-scenarios_a7f0fad9.wav",
    topics: ["atores de ameaça", "engenharia social", "exposição e vulnerabilidade", "IOCs e TTPs", "priorização de correção", "segurança de aplicações"],
    examWeight: "22% do exame",
    provenance: supplementalProvenance("ep07-threats-vulnerabilities-scenarios", "CyberCast 07 — Revisão por cenários: da ameaça ao indicador"),
    transcript: [
      { speaker: "Ana", text: "No segundo domínio, a prova mistura palavras próximas. Vamos desmontar um cenário: uma pessoa recebe uma mensagem que imita o portal de RH, informa uma senha e, horas depois, há login de uma origem incomum. Quem é ator, qual é o vetor e o que é indicador?" },
      { speaker: "Rafael", text: "O ator é quem conduziu a campanha, possivelmente um criminoso externo. O vetor é phishing, porque a mensagem induziu a vítima ao portal falso. O login incomum é um indicador de possível atividade maliciosa. A senha exposta cria risco, mas não é o indicador em si." },
      { speaker: "Ana", text: "Excelente separação. Uma resposta madura combina contenção, como invalidar sessão e redefinir credenciais, investigação de escopo e prevenção, como MFA resistente a phishing, filtro de e-mail e treinamento contextual. Mas cuidado: treinamento não substitui controles técnicos; ele é uma camada da defesa." },
      { speaker: "Rafael", text: "Se um analista encontra um executável desconhecido fazendo conexões periódicas para um domínio recém-criado, isso pode ser um IOC. Já o padrão de persistência e comunicação recorrente descreve mais o comportamento, ou TTP." },
      { speaker: "Ana", text: "Perfeito. IOCs costumam ser artefatos observáveis, como hash, domínio, endereço ou nome de arquivo. TTPs descrevem como o adversário opera e tendem a durar mais que um IOC isolado. Inteligência de ameaças serve para enriquecer decisões: ela não é uma lista para bloquear cegamente, pois exige contexto e validação." },
      { speaker: "Rafael", text: "Outro caso: um scanner mostra uma vulnerabilidade crítica em um servidor exposto, mas o serviço afetado está desativado. Não posso tratar severidade como risco final. Preciso analisar exposição, explorabilidade, impacto e controles existentes." },
      { speaker: "Ana", text: "Exatamente. Priorizar vulnerabilidades envolve criticidade técnica, ativo afetado, acessibilidade, evidência de exploração e valor de negócio. Patch é importante, porém o processo também inclui inventário, validação, mudança controlada e verificação posterior. Uma correção sem teste pode criar nova indisponibilidade." },
      { speaker: "Rafael", text: "E no desenvolvimento seguro, se a aplicação monta consulta concatenando entrada do usuário, a defesa primária é parametrizar consultas e validar entrada no servidor. Um WAF pode ajudar, mas não corrige a causa no código." },
      { speaker: "Ana", text: "Essa é uma ótima lógica de prova: prefira resolver a causa mais próxima. Mesma ideia para segredo exposto em repositório: revogue ou rotacione a credencial, investigue uso, remova o segredo e adote gestão segura de chaves. Apagar o arquivo sem trocar a credencial deixa a exposição ativa." },
      { speaker: "Rafael", text: "Então eu devo narrar mentalmente a cadeia: ator usa um vetor, explora uma vulnerabilidade ou falha humana, deixa indicadores e exige uma mitigação que reduza a probabilidade ou o impacto." },
      { speaker: "Ana", text: "Exato. Ao ver uma questão, classifique o que já aconteceu, o que é apenas possibilidade e qual controle é mais apropriado agora. Essa ordem transforma um enunciado cheio de termos em uma investigação organizada." },
    ],
  },
  {
    id: "ep08-security-architecture-scenarios",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 8,
    title: "Revisão por cenários: desenhando defesa em camadas",
    description: "Ana e Rafael conectam segmentação, identidade, nuvem, dispositivos e resiliência em decisões arquiteturais de Security+.",
    duration: "~5 min",
    audioUrl: "/manus-storage/ep08-security-architecture-scenarios_1f5873ce.wav",
    topics: ["segmentação", "DMZ", "NAC", "IAM em nuvem", "resiliência", "dispositivos e IoT"],
    examWeight: "18% do exame",
    provenance: supplementalProvenance("ep08-security-architecture-scenarios", "CyberCast 08 — Revisão por cenários: desenhando defesa em camadas"),
    transcript: [
      { speaker: "Ana", text: "Arquitetura de segurança cobra desenho, não só produto. Imagine um portal público que precisa acessar uma API interna, enquanto a base de dados não deve receber conexões da internet. Onde cada componente fica?" },
      { speaker: "Rafael", text: "O portal exposto pode ficar em uma zona controlada, como uma DMZ, e falar apenas com a API pelas portas necessárias. A API fica em segmento interno e a base de dados em uma camada ainda mais restrita. Nenhum fluxo deve existir apenas por conveniência." },
      { speaker: "Ana", text: "Certo. Segmentação reduz movimento lateral e facilita aplicar regras com menor privilégio. Não é uma parede mágica: precisa de ACLs, firewall, registros e revisão. Se a questão pede isolamento de uma área específica sem trocar toda a rede, VLAN, sub-rede ou microsegmentação podem aparecer, dependendo da granularidade do cenário." },
      { speaker: "Rafael", text: "E se um notebook pessoal tenta entrar na rede corporativa, uma solução de NAC pode avaliar identidade, certificado e postura antes de liberar a conexão. A resposta não é apenas dar senha de Wi-Fi." },
      { speaker: "Ana", text: "Isso. Arquitetura moderna conecta identidade ao dispositivo. MDM ou UEM ajuda a aplicar configuração, criptografia e atualização em endpoints gerenciados. Para IoT, em geral buscamos inventário, segmentação, firmware confiável, mudança de senha padrão e comunicação mínima necessária." },
      { speaker: "Rafael", text: "Na nuvem, o enunciado pode dizer que um bucket ficou público por engano. A medida correta inclui remover exposição, revisar política de acesso, registrar eventos e aplicar guardrails. A responsabilidade compartilhada não transfere toda a configuração para o provedor." },
      { speaker: "Ana", text: "Exatamente. O provedor protege componentes do serviço conforme o modelo, mas a organização continua responsável por identidades, dados, configurações e escolhas de uso. IAM com papéis, chave temporária e menor privilégio é melhor do que credenciais permanentes distribuídas. Logs de auditoria permitem verificar mudanças e acesso." },
      { speaker: "Rafael", text: "Para disponibilidade, penso em redundância e recuperação testada. Se o requisito é continuar operando após falha de um nó, alta disponibilidade e balanceamento podem resolver. Se o requisito é voltar depois de um desastre regional, entram backups, replicação e plano de recuperação." },
      { speaker: "Ana", text: "Boa distinção. RTO pergunta quanto tempo a operação pode ficar indisponível; RPO pergunta quanta perda de dados é aceitável. A arquitetura precisa traduzir essas metas em controles reais e exercícios. Um backup sem teste é uma hipótese, não uma garantia." },
      { speaker: "Rafael", text: "Minha frase de revisão fica: exponho só o necessário, separo funções e zonas, verifico identidade e postura, protejo configurações na nuvem e projeto a recuperação antes da crise." },
      { speaker: "Ana", text: "Perfeito. Quando duas alternativas parecem válidas, escolha a que atende ao requisito com escopo mínimo, reduz superfície de ataque e preserva capacidade de operação." },
    ],
  },
  {
    id: "ep09-security-operations-scenarios",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 9,
    title: "Revisão por cenários: detectar, responder e recuperar",
    description: "O episódio de maior peso revisa monitoramento, triagem, resposta a incidentes, forense, correção e continuidade operacional.",
    duration: "~5 min",
    audioUrl: "/manus-storage/ep09-security-operations-scenarios_634eb5c3.wav",
    topics: ["SIEM e logs", "triagem", "resposta a incidentes", "cadeia de custódia", "patching", "recuperação"],
    examWeight: "28% do exame",
    provenance: supplementalProvenance("ep09-security-operations-scenarios", "CyberCast 09 — Revisão por cenários: detectar, responder e recuperar"),
    transcript: [
      { speaker: "Ana", text: "Security Operations é o domínio mais pesado. Aqui, o método salva mais do que a pressa. Primeiro cenário: o SIEM alerta centenas de falhas de login e uma autenticação bem-sucedida logo depois, para uma conta privilegiada. Qual é a primeira atitude?" },
      { speaker: "Rafael", text: "Eu faria triagem: confirmaria se o alerta é real, verificaria origem, horário, conta, dispositivo e ações posteriores. Como há privilégio envolvido e possível comprometimento, escalo conforme o playbook e preservo evidências antes de destruir rastros." },
      { speaker: "Ana", text: "Ótimo. Monitoramento não é reagir a cada alerta com o mesmo botão. Contexto ajuda a diferenciar falso positivo de incidente. Se houver risco atual, contenção proporcional pode incluir desabilitar a conta, revogar sessão ou isolar endpoint. Mas a sequência precisa seguir a autoridade e o plano de resposta." },
      { speaker: "Rafael", text: "O ciclo é preparação, identificação, contenção, erradicação, recuperação e lições aprendidas. A ordem pode ter detalhes diferentes em frameworks, mas a ideia é estabilizar, remover a causa, restaurar de forma segura e melhorar depois." },
      { speaker: "Ana", text: "Certo. Agora imagine um endpoint suspeito que pode virar evidência disciplinar ou legal. Não é o momento de explorar arquivos sem cuidado. Devemos preservar estado conforme procedimento, registrar quem coletou o quê, quando e como, proteger cópias e manter cadeia de custódia." },
      { speaker: "Rafael", text: "E uma imagem forense é preferível a trabalhar diretamente no original, quando o processo permitir. Hashes ajudam a demonstrar que a cópia permaneceu íntegra." },
      { speaker: "Ana", text: "Isso. Em outro cenário, uma vulnerabilidade crítica tem correção disponível. O caminho operacional inclui verificar inventário afetado, priorizar por exposição e impacto, testar em ambiente adequado, aprovar mudança, implantar e confirmar resultado. Scanner após correção e registros de mudança fecham o ciclo." },
      { speaker: "Rafael", text: "Se não houver patch imediato, posso reduzir risco com controle temporário: desabilitar serviço, restringir acesso, aumentar monitoramento ou aplicar configuração recomendada. Isso é mitigação, não correção definitiva." },
      { speaker: "Ana", text: "Perfeito. Para recuperação, não basta restaurar rapidamente: valide a origem do backup, se ele está íntegro e livre da causa do incidente, monitore o ambiente retornado e comunique conforme plano. A organização aprende com métricas e lições, não com culpa." },
      { speaker: "Rafael", text: "Então quando a questão pede o 'melhor próximo passo', eu observo a fase. Não tento erradicar antes de confirmar e conter, nem fecho incidente sem verificar recuperação e documentar aprendizado." },
      { speaker: "Ana", text: "Essa leitura de fase é decisiva. Logs confiáveis, relógios sincronizados, playbooks praticados e responsabilidades claras fazem operações de segurança deixarem de ser improviso." },
    ],
  },
  {
    id: "ep10-program-management-scenarios",
    domainCode: "DOM5",
    domainTitle: "Program Management",
    episodeNumber: 10,
    title: "Revisão por cenários: risco, governança e decisão",
    description: "Ana e Rafael aplicam risco, políticas, BIA, fornecedores, auditoria e cultura de segurança a decisões organizacionais da prova.",
    duration: "~5 min",
    audioUrl: "/manus-storage/ep10-program-management-scenarios_48741d47.wav",
    topics: ["registro de risco", "tratamento de risco", "BIA", "políticas e padrões", "terceiros", "auditoria e métricas"],
    examWeight: "20% do exame",
    provenance: supplementalProvenance("ep10-program-management-scenarios", "CyberCast 10 — Revisão por cenários: risco, governança e decisão"),
    transcript: [
      { speaker: "Ana", text: "No último domínio complementar, vamos revisar decisões que tornam segurança sustentável. Imagine que uma organização identificou risco alto de indisponibilidade em um sistema essencial. O que vem antes de escolher uma ferramenta?" },
      { speaker: "Rafael", text: "Entender o risco e o impacto. Eu registraria ativo, ameaça, vulnerabilidade, probabilidade, impacto, dono e tratamento proposto. Uma BIA ajuda a medir consequências para processos e a definir prioridades de continuidade." },
      { speaker: "Ana", text: "Muito bem. Risco pode ser evitado, mitigado, transferido ou aceito formalmente. Aceitação não é ignorar. Exige autoridade adequada, justificativa, risco residual entendido e revisão. Transferir por contrato ou seguro também não remove a responsabilidade de acompanhar a exposição." },
      { speaker: "Rafael", text: "Se a diretoria pergunta quais sistemas devem voltar primeiro após desastre, não basta olhar valor financeiro do servidor. A BIA revela dependências, processos críticos, RTO e RPO esperados." },
      { speaker: "Ana", text: "Exato. Agora um cenário documental: a empresa quer que todas as equipes usem um método específico de criptografia para dados sensíveis. Uma política declara a direção, um padrão define o mínimo obrigatório e um procedimento explica como executar. A questão costuma cobrar essa diferença." },
      { speaker: "Rafael", text: "E uma diretriz oferece recomendação, não a mesma obrigatoriedade de um padrão. Então, se o enunciado pede consistência técnica mensurável, padrão é uma resposta forte." },
      { speaker: "Ana", text: "Certo. Para fornecedores, comece antes da contratação: avaliação de risco, requisitos de segurança, privacidade e notificação de incidentes no contrato. Depois, acompanhe evidências, nível de serviço e mudanças. Um relatório de auditoria pode informar decisão, mas não substitui gestão contínua de terceiros." },
      { speaker: "Rafael", text: "E em uma auditoria, o auditor busca evidência de que o controle existe e funciona. Log, amostra de revisão de acesso, registro de treinamento e aprovação de mudança são exemplos. Uma política bonita sem execução não demonstra eficácia." },
      { speaker: "Ana", text: "Isso leva às métricas. KPI mede desempenho, como percentual de revisões de acesso concluídas no prazo. KRI sinaliza aumento de exposição, como quantidade de contas privilegiadas sem MFA. A liderança precisa de informação clara para decidir, não de uma lista infinita de alertas técnicos." },
      { speaker: "Rafael", text: "E pessoas fazem parte do programa: onboarding, mudança de função, desligamento e conscientização. Se o ambiente pune quem reporta uma mensagem suspeita, os incidentes ficam ocultos. Uma boa cultura facilita relatar cedo." },
      { speaker: "Ana", text: "Perfeito. Feche a prova com esta integração: governança define responsabilidade; risco define prioridade; política orienta; padrão uniformiza; procedimento operacionaliza; auditoria verifica; métricas comunicam; continuidade prepara; e pessoas sustentam o comportamento seguro. Segurança madura é uma decisão repetível, não um projeto isolado." },
    ],
  },
];
