import type { PodcastEpisode } from "./podcastEpisodes";
import type { ContentProvenanceItem } from "./contentProvenance";
import type { PodcastTimestampedLine } from "./podcastBatchFourEpisodes";

type PodcastTimestamped = readonly PodcastTimestampedLine[];

const raioXProvenance = (id: string, title: string): ContentProvenanceItem => ({
  id: `podcast-${id}`,
  origin: "proprio",
  category: "Podcast educacional próprio",
  title,
  source: "CyberDimension Academy",
  license: "Conteúdo autoral da CyberDimension Academy; uso de estudo dentro da plataforma.",
  usage: "Episódio Raio-X da Questão: dissecção narrada de questões estilo simulado Security+, analisando cada alternativa.",
});

/**
 * Minissérie "Raio-X da Questão": Ana e Rafael abrem questões no estilo do
 * simulado oficial e passam cada alternativa pelo raio-X — por que a resposta
 * certa é a certa, e por que cada alternativa errada está errada. O objetivo é
 * treinar o raciocínio de prova, não apenas a memorização.
 */
export const podcastRaioxEpisodes: readonly PodcastEpisode[] = [
  {
    id: "ep63-raio-x-dom1-conceitos",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 63,
    title: "RAIO-X: questão de conceitos gerais e controles",
    description: "Raio-X da Questão dedicado ao Domínio 1: três questões no estilo da prova dissecadas alternativa por alternativa — tripé CIA, funções de controle, AAA e o raciocínio que separa quem chuta de quem sabe.",
    audioUrl: "/manus-storage/ep63-raio-x-dom1-conceitos_bfe045ad.wav",
    duration: "4min46s",
    topics: ["raio-x da questão", "conceitos gerais", "controles de segurança", "CIA", "AAA"],
    examWeight: "12% do exame",
    provenance: raioXProvenance("ep63-raio-x-dom1-conceitos", "CyberCast 63 — Raio-X da Questão: conceitos gerais e controles"),
    transcript: [
      { speaker: "Ana", text: "Bem-vindos ao Raio-X da Questão, o quadro do CyberCast em que Ana e Rafael passam as questões pelo raio-X! Aqui a gente não dá só a resposta: a gente abre cada alternativa e mostra por que ela está certa ou errada. Rafael, hoje é Domínio 1, conceitos gerais, doze por cento da prova. Por onde começa?", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Começa pela questão clássica do tripé CIA, Ana. Todo mundo decora a sigla, mas a prova cobra a aplicação. Anota a questão: uma empresa detectou que registros de auditoria foram alterados após um incidente. Qual princípio do tripé CIA foi violado?", timestampSeconds: 14 },
      { speaker: "Ana", text: "Vamos ao raio-X. Alternativa A, confidencialidade: errada, porque confidencialidade trata de quem pode ver a informação, e o enunciado não menciona exposição de dados a pessoas não autorizadas. Alternativa B, integridade: correta. Os registros foram alterados indevidamente, ou seja, a informação deixou de ser confiável e exata. Alteração não autorizada é a assinatura da integridade.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "Alternativa C, disponibilidade: errada, porque disponibilidade é sobre o serviço estar acessível quando necessário; o incidente não derrubou nada. Alternativa D, responsabilidade: é um princípio complementar ao tripé, mas a alteração de registros é violação de integridade; accountability entra na parte de saber quem alterou. Resposta: integridade.", timestampSeconds: 42 },
      { speaker: "Ana", text: "Repara no padrão, ouvinte: a prova coloca sempre uma alternativa do mesmo grupo semântico. A pegadinha não é entre CIA e uma opção absurda; é entre integridade e responsabilidade. A chave está na palavra-chave do enunciado: alterado significa integridade; exposto significa confidencialidade; indisponível significa disponibilidade.", timestampSeconds: 58 },
      { speaker: "Rafael", text: "Questão dois, Ana. Um gerente de TI decide implementar um novo antivírus para reduzir a probabilidade de infecção por malware. Qual categoria de controle, quanto à função, ele está implantando?", timestampSeconds: 74 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, corretivo: errada. Corretivo age depois do evento, como restaurar um backup após um ataque. Alternativa B, preventivo: correta. O antivírus age antes, reduzindo a probabilidade de o evento ocorrer. Alternativa C, dissuasivo: errada; dissuasivo inibe pela ameaça visível, como uma placa ou uma câmera aparente; antivírus não inibe, ele bloqueia.", timestampSeconds: 86 },
      { speaker: "Rafael", text: "Alternativa D, compensatório: errada também. Compensatório substitui outro controle que não pôde ser implementado, e o enunciado não menciona nenhuma limitação. Detalhe que eu adoro, Ana: o enunciado diz reduzir a probabilidade; isso é vocabulário direto de prevenção.", timestampSeconds: 104 },
      { speaker: "Ana", text: "Exato, Rafael! Quando o enunciado usar reduzir probabilidade ou impedir, pense preventivo. Quando usar identificar, detectar ou registrar, pense detectivo. Quando usar restaurar ou corrigir, corretivo. Questão três, a mais traiçoeira do bloco: qual controle implementa o princípio do menor privilégio em uma organização?", timestampSeconds: 118 },
      { speaker: "Rafael", text: "Analisando: alternativa A, câmera de vigilância: errada; controle físico, nada a ver com privilégio. Alternativa B, segmentação de rede: reduz o movimento lateral, mas não é a implementação direta do menor privilégio. Alternativa C, controle de acesso baseado em função, o RBAC: correta. O RBAC atribui permissões ao papel, e o papel recebe apenas o acesso necessário à função; é a materialização do princípio.", timestampSeconds: 130 },
      { speaker: "Ana", text: "Alternativa D, honeypot: errada; honeypot atrai atacantes para estudos de ameaça, é engenharia de defesa, não gestão de privilégio. E o lembrete de ouro, Rafael: o menor privilégio é sobre conceder o mínimo necessário, no momento necessário, pelo tempo necessário. É por isso que o RBAC bate com a questão e a segmentação, apesar de parecida, não é a resposta.", timestampSeconds: 146 },
      { speaker: "Rafael", text: "Resumo do Raio-X de hoje: integridade é alteração indevida; preventivo reduz probabilidade; menor privilégio materializa-se em RBAC. Refaz o quiz deste episódio, revisita as razões de cada alternativa e o seu cérebro vai começar a enxergar as pegadinhas sozinho. CyberCast, Raio-X, a gente vê na próxima questão!", timestampSeconds: 162 },
    ],
  },
  {
    id: "ep64-raio-x-dom2-ameacas",
    domainCode: "DOM2",
    domainTitle: "Threats, Vulnerabilities and Mitigations",
    episodeNumber: 64,
    title: "RAIO-X: questão de ameaças e vetores de ataque",
    description: "Raio-X da Questão dedicado ao Domínio 2: três questões dissecadas sobre famílias de malware, engenharia social e indicadores de comprometimento — com o raciocínio exato para diferenciar alternativas quase idênticas.",
    audioUrl: "/manus-storage/ep64-raio-x-dom2-ameacas_d9a73732.wav",
    duration: "4min11s",
    topics: ["raio-x da questão", "malware", "engenharia social", "indicadores de comprometimento", "vetores de ataque"],
    examWeight: "22% do exame",
    provenance: raioXProvenance("ep64-raio-x-dom2-ameacas", "CyberCast 64 — Raio-X da Questão: ameaças e vetores de ataque"),
    transcript: [
      { speaker: "Ana", text: "De volta ao Raio-X da Questão! Hoje o Raio-X passa pelo Domínio 2, ameaças, vulnerabilidades e mitigação, o maior peso da prova, vinte e dois por cento. Rafael, a primeira questão sai do laboratório de classificação de malware.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Vamos lá. Questão: um analista investiga um incidente e descobre que um programa malicioso se instala em computadores da rede ao abrir documentos, anexa-se a arquivos legítimos e só executa quando o arquivo hospedeiro é aberto. Qual família de malware é essa?", timestampSeconds: 12 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, worm: errada. Worm se replica de forma autônoma pela rede, sem precisar de hospedeiro nem de ação do usuário; o enunciado descreve o contrário. Alternativa B, trojan: errada também. Trojan se disfarça de software legítimo, mas não se anexa a arquivos hospedeiros. Alternativa C, vírus: correta. Vírus precisa de um hospedeiro, anexa-se a arquivos e depende da execução do arquivo para ativar. As três palavras do enunciado, hospedeiro, anexa-se e execução, são a identidade do vírus.", timestampSeconds: 24 },
      { speaker: "Rafael", text: "Alternativa D, rootkit: errada; rootkit oculta processos e concede persistência privilegiada, e nada no enunciado fala em ocultação. E a técnica para o ouvinte: mapeie as três ações do enunciado com as três famílias. Se propaga sozinho, worm. Se se disfarça, trojan. Se precisa de hospedeiro, vírus. Se se esconde, rootkit.", timestampSeconds: 44 },
      { speaker: "Ana", text: "Questão dois, Engenharia social: um funcionário recebe um telefonema de alguém que se apresenta como técnico do suporte interno e pede a senha para resolver um problema urgente de acesso. Qual é o nome da técnica?", timestampSeconds: 60 },
      { speaker: "Rafael", text: "Raio-X. Alternativa A, baiting: errada; baiting usa uma isca física ou digital, como um pendrive abandonado no estacionamento, para despertar a curiosidade. Alternativa B, pretexting: correta. O atacante cria um pretexto, uma história falsa com personagem e urgência, para ganhar a confiança da vítima e extrair a informação. Alternativa C, tailgating: errada; tailgating é o acesso físico seguindo alguém pela porta, piggybacking quando autorizado.", timestampSeconds: 72 },
      { speaker: "Ana", text: "Alternativa D, whaling: errada, porque whaling é phishing direcionado a executivos de alto nível, geralmente por e-mail, não por telefonema. Detalhe fino, Rafael: o que separa pharasing de pretexting? Nada; pharasing é o vishing direcionado, phishing por voz. O elemento decisivo da questão é a história fabricada, o pretexto. Resposta: pretexting.", timestampSeconds: 90 },
      { speaker: "Rafael", text: "Questão três, a favorita da banca: qual indicador sugere que uma conta corporativa foi comprometida?", timestampSeconds: 106 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, login bem-sucedido fora do horário comercial: não é definitivo; muitas empresas têm turnos e trabalho remoto. Não é a resposta. Alternativa B, senha alterada há noventa dias: isso é higiene normal, inclusive recomendação de gestão de identidade. Alternativa C, dois logins bem-sucedidos de países distantes em intervalo de minutos: correta. É a viagem impossível, um padrão que nenhuma pessoa física consegue realizar; quase sempre significa credenciais em uso por terceiros.", timestampSeconds: 116 },
      { speaker: "Rafael", text: "Alternativa D, MFA habilitado na conta: isso é controle de segurança, reduz o risco, não indica comprometimento. E a técnica final do Raio-X: quando a questão pedir o melhor indicador, elimine primeiro as opções que descrevem controles ou práticas saudáveis. Comprometimento se indica por anomalia comportamental: lugar impossível, horário impossível, volume impossível.", timestampSeconds: 134 },
      { speaker: "Ana", text: "Resumindo o bloco de hoje: hospedeiro significa vírus, história fabricada por telefone é pretexting, e viagem impossível é o indicador clássico de conta comprometida. Refaz o quiz, releia os porquês e o seu raciocínio fica afiado. CyberCast, Raio-X da Questão, até a próxima!", timestampSeconds: 150 },
    ],
  },
  {
    id: "ep65-raio-x-dom3-arquitetura",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 65,
    title: "RAIO-X: questão de arquitetura de segurança",
    description: "Raio-X da Questão dedicado ao Domínio 3: três questões dissecadas sobre criptografia, PKI e resiliência — mostrando como a prova usa cenários curtos para cobrar os conceitos que os alunos mais confundem.",
    audioUrl: "/manus-storage/ep65-raio-x-dom3-arquitetura_a60cb15e.wav",
    duration: "4min20s",
    topics: ["raio-x da questão", "criptografia", "PKI", "resiliência", "arquitetura de segurança"],
    examWeight: "25% do exame",
    provenance: raioXProvenance("ep65-raio-x-dom3-arquitetura", "CyberCast 65 — Raio-X da Questão: arquitetura de segurança"),
    transcript: [
      { speaker: "Ana", text: "Raio-X da Questão no ar de novo! Hoje é a vez do Domínio 3, arquitetura de segurança, com o maior peso individual da prova, vinte e cinco por cento. Rafael, abre com a clássica das chaves.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Questão: uma empresa precisa cifrar arquivos enormes que serão transferidos entre dois data centers em alta velocidade, mas o canal para trocar a chave secreta é considerado seguro. Qual solução a empresa deve adotar?", timestampSeconds: 12 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, criptografia assimétrica: errada para este caso. Assimétrica é ideal para trocar chaves e assinar, mas é computacionalmente pesada; cifrar volumes enormes com ela seria lento. Alternativa B, criptografia simétrica: correta. Mesma chave para cifrar e decifrar, altíssima velocidade, e o enunciado dá a condição que a torna viável: um canal seguro para a troca da chave. É exatamente o padrão usado por protocolos como TLS na fase de dados, com AES.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "Alternativa C, hashing: errada, porque hash é irreversível; não serve para cifrar e recuperar o conteúdo. Alternativa D, esteganografia: errada; esconder dados dentro de outros arquivos não é cifragem e não garante confidencialidade em escala de data center. A chave da questão, Ana, foi o canal seguro mencionado: sem ele, simétrica seria arriscada, mas com ele, a velocidade manda.", timestampSeconds: 46 },
      { speaker: "Ana", text: "Questão dois, PKI: um administrador precisa revogar imediatamente um certificado digital cujo servidor foi comprometido, e quer validação em tempo real, certificado por certificado. Qual mecanismo atende?", timestampSeconds: 62 },
      { speaker: "Rafael", text: "Raio-X. Alternativa A, CSR: errada; certificate signing request é o pedido inicial de emissão, não tem nada a ver com revogação. Alternativa B, CRL: parcial, mas errada neste cenário. A certificate revocation list é uma lista periódica, distribuída em intervalos; entre uma publicação e outra, um certificado recém-revogado pode ainda aparecer como válido. Alternativa C, OCSP: correta. Online Certificate Status Protocol consulta a autoridade em tempo real, um certificado por vez, e responde se está válido, revogado ou desconhecido.", timestampSeconds: 76 },
      { speaker: "Ana", text: "Alternativa D, PKCS#12: errada; é o formato de arquivo que empacota certificado com chave privada, usado para importação e exportação, não para consulta de status. A armadilha clássica da prova é CRL contra OCSP, e a palavra de decisão é a frequência: lista periódica, CRL; tempo real, OCSP. Questão três, resiliência.", timestampSeconds: 96 },
      { speaker: "Rafael", text: "Questão: o negócio define que a organização pode perder no máximo duas horas de dados em um desastre. Qual métrica de resiliência está sendo definida, e que prática operacional ela impõe?", timestampSeconds: 110 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, RTO com restauração em duas horas: errada; recovery time objective mede o tempo máximo que o serviço pode ficar indisponível, não a perda de dados. Alternativa B, RPO de duas horas com backups no mínimo a cada duas horas: correta. Recovery point objective define a perda máxima aceitável de dados, e a frequência dos backups deve caber dentro dessa janela. Alternativa C, MTTR de duas horas: errada; mean time to repair é estatística de manutenção de componentes.", timestampSeconds: 122 },
      { speaker: "Rafael", text: "Alternativa D, MTBF de duas horas: errada; mean time between failures mede confiabilidade entre falhas, o oposto do que o negócio quer. E a técnica de ouro, Ana: RPO é sobre dados, quanto se perde; RTO é sobre tempo, quanto se fica parado. Backup responde a RPO; infraestrutura redundante e plano de recuperação respondem a RTO. Resposta: RPO de duas horas com backups a cada duas horas.", timestampSeconds: 140 },
      { speaker: "Ana", text: "Fechando o Raio-X: volume grande com canal seguro é simétrica; validação em tempo real de certificado é OCSP; perda máxima de dados é RPO. Refaz o quiz deste episódio e você fixa os três padrões. CyberCast, Raio-X da Questão, na próxima questão!", timestampSeconds: 156 },
    ],
  },
  {
    id: "ep66-raio-x-dom4-operacoes",
    domainCode: "DOM4",
    domainTitle: "Security Operations",
    episodeNumber: 66,
    title: "RAIO-X: questão de operações de segurança",
    description: "Raio-X da Questão dedicado ao Domínio 4: três questões dissecadas sobre resposta a incidentes, forense e monitoramento — revelando o vocabulário exato que a banca usa para identificar a fase correta do ciclo de resposta.",
    audioUrl: "/manus-storage/ep66-raio-x-dom4-operacoes_8c6ee529.wav",
    duration: "4min06s",
    topics: ["raio-x da questão", "resposta a incidentes", "forense digital", "monitoramento", "operações de segurança"],
    examWeight: "28% do exame",
    provenance: raioXProvenance("ep66-raio-x-dom4-operacoes", "CyberCast 66 — Raio-X da Questão: operações de segurança"),
    transcript: [
      { speaker: "Ana", text: "Raio-X da Questão de volta com o Domínio 4, operações de segurança, o maior peso da prova inteira, vinte e oito por cento. Rafael, a primeira questão é sobre o ciclo de resposta a incidentes.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Questão: durante um incidente de ransomware, a equipe de segurança isola os servidores afetados da rede, mantém os sistemas ligados para preservar a memória volátil e inicia a cópia forense dos discos. Em qual fase do ciclo de resposta a incidentes a equipe está?", timestampSeconds: 12 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, identificação: errada; identificação é a triagem e a confirmação do incidente, que já aconteceu. Alternativa B, contenção: correta. Isolar os sistemas afetados limita a expansão do dano, e a preservação da memória e dos discos em modo forense faz parte da contenção controlada. O ciclo padrão é preparação, identificação, contenção, erradicação, recuperação e lições aprendidas.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "Alternativa C, erradicação: errada; erradicação é remover a causa, como apagar o malware e aplicar patches, o que ainda não ocorreu. Alternativa D, recuperação: errada; recuperação é restaurar serviços à operação normal com validação, depois de conter e erradicar. A pegadinha aqui é o isolamento com preservação: contenção sem preservação de evidências estraga a investigação, e contenção com preservação é a resposta madura.", timestampSeconds: 44 },
      { speaker: "Ana", text: "Questão dois, ordem de volatilidade: um analista chega a um servidor comprometido e precisa coletar evidências. Qual alternativa apresenta a ordem correta, da mais volátil para a menos volátil?", timestampSeconds: 60 },
      { speaker: "Rafael", text: "Raio-X. Alternativa A, disco, memória RAM, tráfego de rede: errada; é exatamente o contrário da realidade. Alternativa B, tráfego de rede, memória RAM, disco: correta. Tráfego de rede é efêmero, desaparece em segundos; a memória RAM se perde com o desligamento; o disco é persistente. Alternativa C, memória RAM, disco, tráfego: errada por inverter rede e disco.", timestampSeconds: 72 },
      { speaker: "Ana", text: "Alternativa D, logs de aplicação, memória RAM, tráfego: errada; logs gravados em disco são menos voláteis que a memória, e o tráfego não é o item menos volátil da lista. Mnemônico, Rafael: primeiro o que some ao piscar, depois o que some ao desligar, por fim o que fica gravado. Rede, RAM, disco, logs. Quem domina a ordem de volatilidade nunca perde os pontos de forense.", timestampSeconds: 90 },
      { speaker: "Rafael", text: "Questão três: o SIEM dispara um alerta de múltiplas tentativas de login falhas seguidas de um login bem-sucedido em horário incomum. O analista confirma que é um acesso legítimo de um executivo em viagem. Como classificar o alerta?", timestampSeconds: 108 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, incidente confirmado: errada; não houve ação maliciosa. Alternativa B, falso positivo: correta. O alerta disparou corretamente diante do padrão, mas a investigação revelou comportamento legítimo; o evento não é um incidente. Alternativa C, falso negativo: errada; falso negativo é quando o sistema falha em detectar uma ameaça real, o cenário oposto.", timestampSeconds: 120 },
      { speaker: "Rafael", text: "Alternativa D, verdadeiro positivo: errada; verdadeiro positivo exigiria uma ameaça real confirmada. E o fechamento profissional, Ana: um falso positivo confirmado merece ajuste de calibração no SIEM, como contexto de viagem do executivo, para que o próximo alerta igual não desperdice horas da equipe. Classificação correta é a base de métricas corretas. Resposta: falso positivo.", timestampSeconds: 136 },
      { speaker: "Ana", text: "Recapitulando o bloco: isolar e preservar é contenção; volatilidade na ordem rede, RAM, disco; e alerta com causa legítima é falso positivo. Refaz o quiz e o seu triage fica cirúrgico. CyberCast, Raio-X da Questão, até a próxima!", timestampSeconds: 152 },
    ],
  },
  {
    id: "ep67-raio-x-dom5-governanca",
    domainCode: "DOM5",
    domainTitle: "Security Program Management and Oversight",
    episodeNumber: 67,
    title: "RAIO-X: questão de gestão de segurança e governança",
    description: "Raio-X da Questão dedicado ao Domínio 5: três questões dissecadas sobre governança, risco, compliance e conscientização — o território onde a prova separa o técnico do gestor de segurança.",
    audioUrl: "/manus-storage/ep67-raio-x-dom5-governanca_c72638e7.wav",
    duration: "4min20s",
    topics: ["raio-x da questão", "governança", "gestão de risco", "compliance", "conscientização"],
    examWeight: "13% do exame",
    provenance: raioXProvenance("ep67-raio-x-dom5-governanca", "CyberCast 67 — Raio-X da Questão: gestão de segurança e governança"),
    transcript: [
      { speaker: "Ana", text: "Último Raio-X da série! Hoje é Domínio 5, gestão de programa de segurança e supervisão, treze por cento da prova, e o território favorito para cobrar visão de gestor. Rafael, a primeira é cálculo de risco.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Questão: uma falha em um sistema de banco de dados pode gerar perda de duzentos mil reais por incidente, e o histórico indica que o evento ocorre uma vez a cada dois anos. Qual é a perda anual esperada, a ALE?", timestampSeconds: 12 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, duzentos mil reais: errada; esse é o SLE, a perda única esperada. Alternativa B, cem mil reais: correta. ALE é SLE vezes ARO: duzentos mil multiplicados por zero vírgula cinco ocorrência ao ano, que é uma vez a cada dois anos. Alternativa C, quatrocentos mil reais: errada; esse seria o resultado se a ARO fosse dois eventos por ano, o dobro do histórico.", timestampSeconds: 26 },
      { speaker: "Rafael", text: "Alternativa D, mil reais: errada; não corresponde a nenhum cálculo padrão. E a aplicação prática, Ana: se a mitigação proposta custa trinta mil reais por ano e a ALE é de cem mil, a mitigação reduz a perda anual em setenta mil; o investimento se justifica. Se a ALE fosse menor que o custo da mitigação, o risco aceito seria a decisão correta. Números mandam na governança.", timestampSeconds: 44 },
      { speaker: "Ana", text: "Questão dois: após um treinamento obrigatório de segurança, os colaboradores continuam clicando em e-mails de phishing simulados. Qual é a ação de gestão mais adequada?", timestampSeconds: 60 },
      { speaker: "Rafael", text: "Raio-X. Alternativa A, punir os colaboradores reincidentes: errada; punição gera medo e subnotificação, e não muda comportamento. Alternativa B, reenviar o mesmo treinamento anual: errada; repetir o mesmo conteúdo que falhou não ataca a causa. Alternativa C, implementar treinamentos práticos frequentes, com simulações de phishing e feedback imediato: correta. Conscientização eficaz é contínua, prática e mensurável; o comportamento muda com repetição e contexto, não com palestra anual.", timestampSeconds: 74 },
      { speaker: "Ana", text: "Alternativa D, desativar o e-mail corporativo externo: errada; medida draconiana que inviabiliza o negócio para reduzir um risco gerenciável. A lição do gestor: quando o controle educacional falha, a resposta é melhorar o controle, medir o comportamento e reforçar com prática, não punir. Questão três, compliance.", timestampSeconds: 94 },
      { speaker: "Rafael", text: "Questão: uma empresa de saúde dos Estados Unidos precisa provar que protege dados de pacientes, e uma empresa europeia precisa respeitar regras de privacidade de cidadãos da UE. Quais frameworks regulatórios se aplicam, respectivamente?", timestampSeconds: 108 },
      { speaker: "Ana", text: "Raio-X. Alternativa A, PCI DSS e ISO 27001: errada; PCI trata de cartões de pagamento e ISO é um padrão de gestão, não uma lei. Alternativa B, HIPAA e GDPR: correta. HIPAA rege dados de saúde nos Estados Unidos; GDPR rege dados pessoais de cidadãos da União Europeia, com alcance extraterritorial para empresas que processam esses dados. Alternativa C, FISMA e SOX: errada; FISMA é para agências federais americanas e SOX para relatórios financeiros de empresas listadas.", timestampSeconds: 122 },
      { speaker: "Rafael", text: "Alternativa D, NIST CSF e CIS Controls: errada; ambos são frameworks técnicos voluntários, não regulamentação com força de lei. O mapeamento rápido, Ana: saúde nos EUA, HIPAA; pagamentos, PCI DSS; Europa, GDPR; finanças listadas, SOX; governo americano, FISMA. E encerramos a série com a mensagem central: saber por que cada alternativa está errada vale tanto quanto saber qual está certa.", timestampSeconds: 140 },
      { speaker: "Ana", text: "Fechamento da série Raio-X da Questão: ALE é SLE vezes ARO; conscientização que não funciona pede prática contínua, não punição; e o mapa regulatório é HIPAA, GDPR, PCI DSS, SOX e FISMA. Refaz os quizzes dos cinco episódios, revisa os porquês e entra na prova com o raciocínio calibrado. CyberCast, Raio-X da Questão, boa prova!", timestampSeconds: 156 },
    ],
  },
];
