import type { PodcastEpisode } from "./podcastEpisodes";
import type { ContentProvenanceItem } from "./contentProvenance";
import type { PodcastTimestampedLine } from "./podcastBatchFourEpisodes";

type PodcastTimestamped = readonly PodcastTimestampedLine[];

const seasonThreeProvenance = (id: string, title: string): ContentProvenanceItem => ({
  id: `podcast-${id}`,
  origin: "proprio",
  category: "Podcast educacional próprio",
  title,
  source: "CyberDimension Academy",
  license: "Conteúdo autoral da CyberDimension Academy; uso de estudo dentro da plataforma.",
  usage: "Diálogo autoral em áudio e transcrição acessível da terceira temporada do CyberCast Security+.",
});

export const podcastSeasonThreeEpisodes: readonly PodcastEpisode[] = [
  {
    id: "ep51-forense-custodia-evidencia",
    domainCode: "DOM4",
    domainTitle: "Security Operations (Forense)",
    episodeNumber: 51,
    title: "Aprofundamento: cadeia de custódia e a integridade da evidência",
    description: "Ana e Rafael explicam como a evidência digital é tratada da coleta ao tribunal: hash, lacres, registros e a cadeia de custódia que decide o caso.",
    audioUrl: "/manus-storage/ep51-forense-custodia-evidencia_8343c145.wav",
    duration: "1m29s",
    topics: ["coleta de evidência", "hash de integridade", "lacres e mídia original", "cadeia de custódia", "pegadinhas"],
    examWeight: "16% do exame",
    provenance: seasonThreeProvenance("ep51-forense-custodia-evidencia", "CyberCast 51 — Aprofundamento: cadeia de custódia e a integridade da evidência"),
    transcript: [
      { speaker: "Ana", text: "Temporada três abrindo com forense, Rafael! O tema de hoje decide processos inteiros: a cadeia de custódia da evidência digital.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Acho que entendo a ideia: provar que a evidência não foi alterada desde a coleta. Mas na prática, o que garante isso?", timestampSeconds: 11 },
      { speaker: "Ana", text: "Três pilares: integridade medida com hash criptográfico no momento da coleta, mídia de trabalho separada da original e registro contínuo de quem tocou no quê, quando e por quê.", timestampSeconds: 22 },
      { speaker: "Rafael", text: "Então o hash, tipo SHA-256, é calculado logo na cena, e depois recalculado em cada transferência. Se os hashes casarem, a evidência é a mesma.", timestampSeconds: 34 },
      { speaker: "Ana", text: "Exato. E o trabalho nunca é feito sobre a mídia original: cria-se uma imagem bit a bit, lacrada e documentada. O original fica guardado como estava.", timestampSeconds: 46 },
      { speaker: "Rafael", text: "E se alguém quebrar a cadeia de custódia?", timestampSeconds: 56 },
      { speaker: "Ana", text: "A evidência perde valor probatório: se não dá para provar que não foi alterada, ela vira papel molhado no tribunal. Por isso o formulário de custódia registra cada transferência.", timestampSeconds: 62 },
      { speaker: "Rafael", text: "Na prova, o erro clássico é mexer no sistema vivo antes de coletar a memória. A RAM se perde no desligamento, então vem primeiro.", timestampSeconds: 75 },
      { speaker: "Ana", text: "Perfeito, essa é a ordem de volatilidade: captura primeiro o que some mais rápido. Ordem, documentação e hash fecham o ciclo forense.", timestampSeconds: 87 },
    ],
  },
  {
    id: "ep52-forense-disco-memoria",
    domainCode: "DOM4",
    domainTitle: "Security Operations (Forense)",
    episodeNumber: 52,
    title: "Aprofundamento: análise de disco, memória e linha do tempo",
    description: "Ana e Rafael mergulham nas análises forenses: artefatos de disco, conteúdo volátil da RAM e a construção da linha do tempo do incidente.",
    audioUrl: "/manus-storage/ep52-forense-disco-memoria_d0b86134.wav",
    duration: "1m30s",
    topics: ["artefatos de disco", "análise de memória", "arquivos apagados", "linha do tempo", "pegadinhas"],
    examWeight: "16% do exame",
    provenance: seasonThreeProvenance("ep52-forense-disco-memoria", "CyberCast 52 — Aprofundamento: análise de disco, memória e linha do tempo"),
    transcript: [
      { speaker: "Ana", text: "Seguindo a trilha forense, Rafael: hoje falamos do que o disco e a memória escondem sobre um incidente.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Por onde começa? Sempre vejo ferramentas mencionando artefatos, mas não sei o que procurar.", timestampSeconds: 11 },
      { speaker: "Ana", text: "Começa pelo disco: a imagem forense é analisada procurando registros do sistema de arquivos, arquivos apagados que ainda estão no cluster, prefetch, logs do Windows e metadados de acesso. Cada pedaço conta uma parte da história.", timestampSeconds: 21 },
      { speaker: "Rafael", text: "E a memória? O que ela revela que o disco não revela?", timestampSeconds: 34 },
      { speaker: "Ana", text: "A RAM mostra o presente do sistema: processos maliciosos que nunca gravaram em disco, senhas e chaves na memória, conexões ativas e código injetado. Malware fileless só aparece ali.", timestampSeconds: 42 },
      { speaker: "Rafael", text: "E se o invasor apagou arquivos de propósito?", timestampSeconds: 54 },
      { speaker: "Ana", text: "Apagar não é apagar de verdade: até sobrescrever, os dados ficam nos clusters marcados como livres, e a ferramenta de recovery recupera. A timeline de eventos junta acesso, modificação e criação em uma linha do tempo da ação do invasor.", timestampSeconds: 60 },
      { speaker: "Rafael", text: "Então a linha do tempo transforma dezenas de logs soltos em uma narrativa: quando ele entrou, o que tocou e como saiu.", timestampSeconds: 74 },
      { speaker: "Ana", text: "É isso. Forense é reconstrução paciente: disco, memória e linha do tempo convergem para um relato que resiste a perguntas difíceis.", timestampSeconds: 86 },
    ],
  },
  {
    id: "ep53-malware-familias-analise",
    domainCode: "DOM2",
    domainTitle: "Threats, Vulnerabilities & Mitigations (Malware)",
    episodeNumber: 53,
    title: "Aprofundamento: famílias de malware, comportamento e sandbox",
    description: "Ana e Rafael classificam famílias de malware, comparam análise estática e dinâmica, e mostram como o sandbox revela o comportamento do código.",
    audioUrl: "/manus-storage/ep53-malware-familias-analise_503d1ef3.wav",
    duration: "1m33s",
    topics: ["famílias de malware", "análise estática", "análise dinâmica", "sandbox", "pegadinhas"],
    examWeight: "12% do exame",
    provenance: seasonThreeProvenance("ep53-malware-familias-analise", "CyberCast 53 — Aprofundamento: famílias de malware, comportamento e sandbox"),
    transcript: [
      { speaker: "Ana", text: "Aprofundamento de hoje é ameaça pura, Rafael: famílias de malware e como descobrir o que uma amostra faz sem explodir a rede.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Ransomware, trojan, worm, spyware... para a prova eu decorei os nomes. Mas o que diferencia uma família de outra na prática?", timestampSeconds: 12 },
      { speaker: "Ana", text: "O comportamento. O worm se espalha sozinho pela rede, o trojan se disfarça de software legítimo, o ransomware cifra e cobra, e o spyware observa em silêncio. Mesmo código assinado pode esconder várias intenções.", timestampSeconds: 23 },
      { speaker: "Rafael", text: "E como se analisa um arquivo suspeito sem abrir Pandora?", timestampSeconds: 36 },
      { speaker: "Ana", text: "Em duas camadas: estática, olhando código e strings sem executar, e dinâmica, rodando em um sandbox isolado e observando chamadas de API, registros que toca e conexões que abre.", timestampSeconds: 44 },
      { speaker: "Rafael", text: "O sandbox engana o malware também, né? Alguns só detonam em máquina de usuário real.", timestampSeconds: 57 },
      { speaker: "Ana", text: "Sim, malware moderno detecta ambiente de análise e fica dormindo. Por isso o sandbox simula atividade humana e o analista complementa com análise de rede e comparação de assinaturas de família.", timestampSeconds: 65 },
      { speaker: "Rafael", text: "Pegadinha da prova: análise estática primeiro, dinâmica depois. Nunca executar amostra em máquina de trabalho.", timestampSeconds: 79 },
      { speaker: "Ana", text: "Memoriza isso, Rafael. Amostra só toca hardware de análise, rede controlada e snapshot por tentativa.", timestampSeconds: 90 },
    ],
  },
  {
    id: "ep54-analise-trafego-pcap",
    domainCode: "DOM4",
    domainTitle: "Security Operations (Redes)",
    episodeNumber: 54,
    title: "Aprofundamento: análise de tráfego e caça em PCAP",
    description: "Ana e Rafael aprendem a ler capturas de pacotes: protocolos, portas, beacons de C2 e os sinais de exfiltração escondidos no tráfego.",
    audioUrl: "/manus-storage/ep54-analise-trafego-pcap_5369ec0b.wav",
    duration: "1m24s",
    topics: ["captura de pacotes", "protocolos e portas", "beacons de C2", "exfiltração de dados", "pegadinhas"],
    examWeight: "16% do exame",
    provenance: seasonThreeProvenance("ep54-analise-trafego-pcap", "CyberCast 54 — Aprofundamento: análise de tráfego e caça em PCAP"),
    transcript: [
      { speaker: "Ana", text: "Mudando de evidência para tráfego, Rafael: a análise de PCAP transforma bytes em história de ataque.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Já abri um PCAP e fiquei perdido entre milhares de linhas. Como começar sem se afogar?", timestampSeconds: 10 },
      { speaker: "Ana", text: "Por estatística: tops de conversação, portas mais usadas, protocolos raros para aquele ambiente. O incomum grita primeiro; depois você abre os pacotes suspeitos.", timestampSeconds: 21 },
      { speaker: "Rafael", text: "E um beacon de C2, como aparece no PCAP?", timestampSeconds: 32 },
      { speaker: "Ana", text: "Conexões periódicas para o mesmo destino externo, quase no mesmo intervalo e com payloads pequenos e parecidos. Beacon é o malware reportando casa. DNS tunneling esconde isso em consultas aparentemente inocentes.", timestampSeconds: 40 },
      { speaker: "Rafael", text: "E a exfiltração? Como se vê o vazamento de dados?", timestampSeconds: 53 },
      { speaker: "Ana", text: "Grandes fluxos de saída para IP pouco comum, especialmente fora do horário comercial, com volume desproporcional ao serviço. Somar isso com o beacon e você tem o ciclo completo da invasão.", timestampSeconds: 61 },
      { speaker: "Rafael", text: "A prova costuma cobrar a ferramenta: Wireshark para inspeção e tcpdump para coleta, certo?", timestampSeconds: 74 },
      { speaker: "Ana", text: "Correto. E a regra de ouro: capture com filtro de captura, não espere analisar tudo. O filtro protege o tempo do analista.", timestampSeconds: 85 },
    ],
  },
  {
    id: "ep55-deteccao-sigma-regras",
    domainCode: "DOM4",
    domainTitle: "Security Operations (Detecção)",
    episodeNumber: 55,
    title: "Aprofundamento: regras Sigma, detecção genérica e tuning",
    description: "Ana e Rafael mostram como regras de detecção genéricas funcionam em qualquer SIEM, com tuning fino e as armadilhas dos falsos positivos.",
    audioUrl: "/manus-storage/ep55-deteccao-sigma-regras_0401cbe3.wav",
    duration: "1m19s",
    topics: ["regras Sigma", "detecção genérica", "falsos positivos", "tuning de regras", "pegadinhas"],
    examWeight: "16% do exame",
    provenance: seasonThreeProvenance("ep55-deteccao-sigma-regras", "CyberCast 55 — Aprofundamento: regras Sigma, detecção genérica e tuning"),
    transcript: [
      { speaker: "Ana", text: "Detecção em profundidade hoje, Rafael: regras Sigma e a arte de escrever alertas que pegam invasor sem afogar a equipe em ruído.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Sigma é aquela linguagem genérica que converte para cada SIEM, né? Qual a vantagem real?", timestampSeconds: 11 },
      { speaker: "Ana", text: "Independência: você escreve a regra uma vez e converte para Splunk, Elastic, Defender. A comunidade compartilha regras atualizadas contra táticas do MITRE ATT&CK em formato único.", timestampSeconds: 22 },
      { speaker: "Rafael", text: "E por que as equipes sofrem tanto com alertas?", timestampSeconds: 34 },
      { speaker: "Ana", text: "Regra sem tuning vira torneira aberta: cada login novo do CEO gera alarme. O tuning adiciona contexto de ambiente: exclui IPs internos de administração, janelas de backup e contas de serviço legítimas.", timestampSeconds: 42 },
      { speaker: "Rafael", text: "Então falso positivo não é defeito da ferramenta, é regra imatura.", timestampSeconds: 56 },
      { speaker: "Ana", text: "Exato. Métrica de maturidade: precisão da regra medida pela proporção de alertas que viram incidente real. Regra sem dono vira ruído; regra com dono vira detecção.", timestampSeconds: 64 },
      { speaker: "Rafael", text: "Na prova, se a questão fala de escrever detecção independente de SIEM, a resposta é Sigma.", timestampSeconds: 77 },
      { speaker: "Ana", text: "Bateu certo. Genérico para escrever, específico para executar: esse é o truque.", timestampSeconds: 88 },
    ],
  },
  {
    id: "ep56-cloud-k8s-containers",
    domainCode: "DOM5",
    domainTitle: "Security Program Management (Cloud)",
    episodeNumber: 56,
    title: "Aprofundamento: containers, Kubernetes e pipelines seguros",
    description: "Ana e Rafael exploram a segurança de containers e Kubernetes: imagens, runtime, segredos e o pipeline CI/CD como linha de defesa.",
    audioUrl: "/manus-storage/ep56-cloud-k8s-containers_c76657ed.wav",
    duration: "1m36s",
    topics: ["segurança de containers", "Kubernetes", "registros de imagens", "segredos", "CI/CD seguro"],
    examWeight: "Extra Security+",
    provenance: seasonThreeProvenance("ep56-cloud-k8s-containers", "CyberCast 56 — Aprofundamento: containers, Kubernetes e pipelines seguros"),
    transcript: [
      { speaker: "Ana", text: "Aprofundamento de infraestrutura moderna, Rafael: containers, Kubernetes e como não virar manchete de vazamento.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Container é isolado, certo? Então já nasce seguro.", timestampSeconds: 10 },
      { speaker: "Ana", text: "Não exatamente: container compartilha o kernel do host. Se a imagem tem vulnerabilidade ou root desnecessário, o isolamento ajuda, mas não salva. Começa na base: imagens oficiais, mínimas e escaneadas.", timestampSeconds: 19 },
      { speaker: "Rafael", text: "E o registro de imagens, tipo um ECR ou ACR? Qual o papel dele?", timestampSeconds: 31 },
      { speaker: "Ana", text: "Ele guarda versões assinadas. O cluster só deve aceitar imagens do registro privado, com verificação de assinatura: nada de executar código que ninguém revisou.", timestampSeconds: 40 },
      { speaker: "Rafael", text: "E Kubernetes? Onde mora o perigo?", timestampSeconds: 50 },
      { speaker: "Ana", text: "Na configuração: API exposta, RBAC permissivo, pods rodando como root. O mínimo é: rede segregada por namespace, políticas de pod, segredos fora do manifesto e auditoria ligada.", timestampSeconds: 58 },
      { speaker: "Rafael", text: "E o pipeline CI/CD vira fronteira de ataque também?", timestampSeconds: 70 },
      { speaker: "Ana", text: "Totalmente. Código no pipeline com credenciais vale mais que qualquer firewall. Segredo em cofre, acesso com identidade, build imutável e assinatura no artefato fecham a corrente.", timestampSeconds: 79 },
      { speaker: "Rafael", text: "Resumindo: imagem limpa, registro assinado, cluster travado e pipeline sem segredo exposto.", timestampSeconds: 90 },
    ],
  },
  {
    id: "ep57-identidade-pam-privilegios",
    domainCode: "DOM3",
    domainTitle: "Security Architecture (Identidade)",
    episodeNumber: 57,
    title: "Aprofundamento: PAM, jaulas de privilégio e sessões administrativas",
    description: "Ana e Rafael destrincham gestão de privilégios: cofres de senha, sessões gravadas, just-in-time e o princípio do menor privilégio além do papel.",
    audioUrl: "/manus-storage/ep57-identidade-pam-privilegios_80b3a112.wav",
    duration: "1m14s",
    topics: ["gestão de privilégios", "cofre de senhas", "sessões gravadas", "privilégio just-in-time", "pegadinhas"],
    examWeight: "15% do exame",
    provenance: seasonThreeProvenance("ep57-identidade-pam-privilegios", "CyberCast 57 — Aprofundamento: PAM, jaulas de privilégio e sessões administrativas"),
    transcript: [
      { speaker: "Ana", text: "Identidade em profundidade hoje, Rafael: PAM e o controle real das contas que abrem tudo.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "O menor privilégio eu já entendo no papel. Por que ainda vaza tanto por conta administrativa?", timestampSeconds: 10 },
      { speaker: "Ana", text: "Porque o papel é permanente e o acesso é pontual. O PAM resolve isso: a senha do admin nunca é conhecida, fica no cofre e é liberada só na sessão aprovada.", timestampSeconds: 21 },
      { speaker: "Rafael", text: "Just-in-time: o privilégio nasce quando preciso e morre quando termino.", timestampSeconds: 32 },
      { speaker: "Ana", text: "Isso. E a sessão toda fica gravada, com aprovação de workflow antes de abrir. Se algo der errado, a gravação vira evidência forense.", timestampSeconds: 41 },
      { speaker: "Rafael", text: "E as contas de serviço, aquelas que rodam processos?", timestampSeconds: 51 },
      { speaker: "Ana", text: "O erro clássico: senha de serviço fixa em script. O certo é identidade gerenciada ou rotação automática pelo cofre, com acesso apenas ao recurso necessário.", timestampSeconds: 59 },
      { speaker: "Rafael", text: "A pegadinha da prova que sempre cai: privilégio concedido em excesso é falha mesmo que ninguém explore.", timestampSeconds: 72 },
      { speaker: "Ana", text: "Verdade: privilégio não usado é risco carregado. Auditoria de acesso descobre o excesso; o PAM impede que ele vire dano.", timestampSeconds: 83 },
    ],
  },
  {
    id: "ep58-incidentes-reais-casos",
    domainCode: "DOM4",
    domainTitle: "Security Operations (Incidentes)",
    episodeNumber: 58,
    title: "Aprofundamento: casos reais que ensinam resposta a incidentes",
    description: "Ana e Rafael revisitam padrões de incidentes reais — do ataque de supply chain ao vazamento por configuração — e o que cada caso ensina sobre defesa.",
    audioUrl: "/manus-storage/ep58-incidentes-reais-casos_dce487c2.wav",
    duration: "1m26s",
    topics: ["supply chain attack", "configuração exposta", "padrões de ataque", "lições aprendidas", "pegadinhas"],
    examWeight: "16% do exame",
    provenance: seasonThreeProvenance("ep58-incidentes-reais-casos", "CyberCast 58 — Aprofundamento: casos reais que ensinam resposta a incidentes"),
    transcript: [
      { speaker: "Ana", text: "Hora de estudar com casos, Rafael: padrões reais de incidente e a lição que cada um deixou para a defesa.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Os casos de supply chain me assustam: o ataque vem de dentro do fornecedor que a gente confia.", timestampSeconds: 10 },
      { speaker: "Ana", text: "E é por isso que a lição é dupla: auditar a cadeia de suprimentos de software e validar a integridade dos artefatos que entram no seu ambiente. Assinatura, hash e origem conhecida.", timestampSeconds: 21 },
      { speaker: "Rafael", text: "E o vazamento por configuração? Aquela conta de nuvem sem autenticação?", timestampSeconds: 33 },
      { speaker: "Ana", text: "O padrão é sempre o mesmo: recurso criado rápido, autenticação desligada por conveniência e dado exposto por meses. A correção é automática: políticas que impedem armazenamento público e varredura contínua de configuração.", timestampSeconds: 43 },
      { speaker: "Rafael", text: "O que esses casos têm em comum, além do dano?", timestampSeconds: 55 },
      { speaker: "Ana", text: "O tempo de detecção. Quase todos ficaram meses no ambiente. A defesa que encurta esse tempo é a que ganha: telemetria, regras calibradas e prática de resposta.", timestampSeconds: 62 },
      { speaker: "Rafael", text: "E a lição aprendida, que todo relatório de incidente cobra?", timestampSeconds: 73 },
      { speaker: "Ana", text: "É o que transforma custo em inteligência: o que falhou, o que funcionou e o que muda no processo. Caso sem lição aprendida é só acidente repetido.", timestampSeconds: 81 },
      { speaker: "Rafael", text: "Cada incidente bem documentado vira vacina para o próximo.", timestampSeconds: 92 },
    ],
  },
  {
    id: "ep59-bug-bounty-disclosure",
    domainCode: "DOM2",
    domainTitle: "Threats, Vulnerabilities & Mitigations (Prática)",
    episodeNumber: 59,
    title: "Aprofundamento: bug bounty e responsible disclosure na prática",
    description: "Ana e Rafael mostram o caminho do pesquisador de segurança: programas de bug bounty, escopo, responsabilidade e a comunicação correta com a organização.",
    audioUrl: "/manus-storage/ep59-bug-bounty-disclosure_d690d991.wav",
    duration: "1m17s",
    topics: ["bug bounty", "responsible disclosure", "escopo e regras", "comunicação com a organização", "pegadinhas"],
    examWeight: "12% do exame",
    provenance: seasonThreeProvenance("ep59-bug-bounty-disclosure", "CyberCast 59 — Aprofundamento: bug bounty e responsible disclosure na prática"),
    transcript: [
      { speaker: "Ana", text: "Fechando os aprofundamentos técnicos com prática real, Rafael: bug bounty e responsible disclosure.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Encontrei uma falha num site de um cliente de serviço. Posso explorar para mostrar o risco?", timestampSeconds: 10 },
      { speaker: "Ana", text: "Nunca sem autorização. O responsible disclosure começa com a notificação privada à organização, dando prazo para correção antes de qualquer divulgação pública.", timestampSeconds: 21 },
      { speaker: "Rafael", text: "E bug bounty muda isso?", timestampSeconds: 31 },
      { speaker: "Ana", text: "Muda a moldura, não a ética: o programa define escopo, regras e recompensa. Testar dentro do escopo é autorizado; fora dele é exploração criminosa, mesmo com boa intenção.", timestampSeconds: 39 },
      { speaker: "Rafael", text: "Então primeiro lê-se o programa: o que pode testar, o que é proibido e como reportar.", timestampSeconds: 51 },
      { speaker: "Ana", text: "Isso. E o relatório importa tanto quanto o achado: passos para reproduzir, impacto honesto e sem dano a dados de terceiros. Pesquisa que gera dano perde credibilidade e pode responder legalmente.", timestampSeconds: 60 },
      { speaker: "Rafael", text: "Na prova: disclosure sempre primeiro à organização, divulgação pública só depois de corrigida ou do prazo esgotado.", timestampSeconds: 74 },
      { speaker: "Ana", text: "Perfeito. O pesquisador responsável transforma vulnerabilidade em correção, não em manchete.", timestampSeconds: 85 },
    ],
  },
  {
    id: "ep60-retrospectiva-jornada",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts (Retrospectiva)",
    episodeNumber: 60,
    title: "Retrospectiva da temporada 3: a jornada além da prova",
    description: "Ana e Rafael fecham a temporada revisitando os aprofundamentos e mapeando a jornada do aluno de Security+ para a prática profissional.",
    audioUrl: "/manus-storage/ep60-retrospectiva-jornada_840fd24d.wav",
    duration: "1m22s",
    topics: ["retrospectiva da temporada", "jornada profissional", "próximos passos", "comunidade e prática", "pegadinhas"],
    examWeight: "Revisão geral",
    provenance: seasonThreeProvenance("ep60-retrospectiva-jornada", "CyberCast 60 — Retrospectiva da temporada 3: a jornada além da prova"),
    transcript: [
      { speaker: "Ana", text: "Temporada três chegando ao fim, Rafael! Hora de amarrar tudo que a gente mergulhou nos aprofundamentos.", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Foram dez temas densos: forense, malware, tráfego, detecção, cloud, identidade e casos reais. O que ficou?", timestampSeconds: 11 },
      { speaker: "Ana", text: "O fio comum: defesa é um ciclo. Coleta com integridade, análise com método, detecção calibrada e resposta com aprendizado. Cada episódio foi uma engrenagem desse ciclo.", timestampSeconds: 23 },
      { speaker: "Rafael", text: "E para quem quer seguir além da prova, por onde ir?", timestampSeconds: 35 },
      { speaker: "Ana", text: "Três trilhas: prática contínua em laboratórios e CTFs, especialização em uma área como SOC ou forense, e comunidade para trocar conhecimento. Certificação abre porta; prática constrói a carreira.", timestampSeconds: 44 },
      { speaker: "Rafael", text: "Vale a pena refazer os episódios da temporada 3 com os quizzes?", timestampSeconds: 56 },
      { speaker: "Ana", text: "Sempre vale: repetição espaçada fixa o conteúdo. E o quiz com 100 por cento te aproxima do badge de ouvinte veterano da série.", timestampSeconds: 64 },
      { speaker: "Rafael", text: "Ana, obrigado pela jornada. Do zero à prova, e agora rumo à prática profissional.", timestampSeconds: 75 },
      { speaker: "Ana", text: "Obrigada por estudar junto, Rafael. A CyberDimension segue evoluindo: nos vemos no próximo CyberCast!", timestampSeconds: 88 },
    ],
  },
];
