import type { PodcastEpisode } from "./podcastEpisodes";
import type { ContentProvenanceItem } from "./contentProvenance";
import type { PodcastTimestampedLine } from "./podcastBatchFourEpisodes";
type PodcastTimestamped = readonly PodcastTimestampedLine[];
const bonusProvenance = (id: string, title: string): ContentProvenanceItem => ({
  id: `podcast-${id}`,
  origin: "proprio",
  category: "Podcast educacional próprio",
  title,
  source: "CyberDimension Academy",
  license: "Conteúdo autoral da CyberDimension Academy; uso de estudo dentro da plataforma.",
  usage: "Episódio especial autoral em áudio e transcrição acessível de revisão relâmpago pré-prova do CyberCast Security+.",
});
/**
 * Especiais "Ao vivo com Ana e Rafael": revisão relâmpago pré-prova que condensa
 * a série inteira. O ritmo é propositalmente rápido, com perguntas cruzadas e
 * gatilhos de memorização para as últimas horas de estudo.
 */
export const podcastBonusEpisodes: readonly PodcastEpisode[] = [
  {
    id: "ep61-ao-vivo-revisao-dom1-e-dom2",
    domainCode: "DOM1",
    domainTitle: "General Security Concepts",
    episodeNumber: 61,
    title: "AO VIVO: revisão relâmpago de domínios 1 e 2 — conceitos gerais e ameaças",
    description: "Edição ao vivo especial: Ana e Rafael revisitam, em ritmo acelerado, os conceitos gerais de segurança e o universo de ameaças e vulnerabilidades, com gatilhos de memorização para a véspera da prova.",
    audioUrl: "/manus-storage/ep61-ao-vivo-revisao-dom1-e-dom2_dfc1fcbb.wav",
    duration: "5m24s",
    topics: ["revisão relâmpago", "conceitos gerais", "CIA e controles", "ataques e vetores", "gatilhos de memória"],
    examWeight: "12% + 22% do exame",
    provenance: bonusProvenance("ep61-ao-vivo-revisao-dom1-e-dom2", "CyberCast 61 — Ao vivo: revisão relâmpago de domínios 1 e 2"),
    transcript: [
      { speaker: "Ana", text: "Bem-vindos ao Ao vivo com Ana e Rafael, o especial de revisão relâmpago pré-prova do CyberCast! Ana ao vivo, Rafael ao vivo, e o Security+ inteiro condensado em poucos minutos. Rafael, energia no máximo: prova amanhã, o que a gente revisa primeiro?", timestampSeconds: 0 },
      { speaker: "Rafael", text: "Energia lá em cima, Ana! Começa pelo Domínio 1, que vale doze por cento mas é a fundação de tudo. Me dá a manha em trinta segundos.", timestampSeconds: 12 },
      { speaker: "Ana", text: "Trinta segundos? Anota aí: segurança existe para proteger a CIA. Confidencialidade é só quem deve ver. Integridade é nada ser alterado. Disponibilidade é estar lá quando precisar. Qualquer questão começa nesses três pilares.", timestampSeconds: 20 },
      { speaker: "Rafael", text: "Ana, a pegadinha clássica: o que diferencia autenticidade de não repúdio? Eu sempre travo aqui.", timestampSeconds: 32 },
      { speaker: "Ana", text: "Pergunta de ouro! Autenticidade prova quem gerou ou enviou a informação, normalmente com assinatura digital e certificado. Não repúdio impede que a pessoa negue a autoria, usando carimbo de tempo e registros auditáveis. Um é sobre origem, o outro é sobre negação.", timestampSeconds: 38 },
      { speaker: "Rafael", text: "E controles: físico, técnico e gerencial, cada um com sua função. Me recorda rápido.", timestampSeconds: 50 },
      { speaker: "Ana", text: "Funções de controle: preventivo evita, detectivo identifica, corretivo corrige, compensatório substitui o ausente e dissuasivo inibe. Lembrete: placa de vigilância é dissuasivo; câmera gravando é detectivo. A prova adora inverter esses dois.", timestampSeconds: 55 },
      { speaker: "Rafael", text: "Gatilho anotado: placa não grava, só assusta! Agora o AAA: autenticação, autorização e accountability.", timestampSeconds: 67 },
      { speaker: "Ana", text: "Autenticação prova quem você é: biometria, token, senha forte. Autorização define o que você pode fazer, com o privilégio mínimo dando só o necessário. Accountability é a trilha de auditoria: registro de tudo que aconteceu. Nunca confunda: autenticação é identidade, autorização é permissão.", timestampSeconds: 72 },
      { speaker: "Rafael", text: "Zero Trust: aquela frase que resolve a questão. Diz aí.", timestampSeconds: 84 },
      { speaker: "Ana", text: "Nunca confie, sempre verifique. Verificação contínua de identidade, dispositivo e contexto, em cada acesso, dentro e fora da rede. E defense in depth são camadas: firewall, endpoint, criptografia, treinamento, para que a falha de uma camada não derrube tudo.", timestampSeconds: 88 },
      { speaker: "Rafael", text: "Domínio 1 fechado! Agora o Domínio 2, que pesa vinte e dois por cento. Ameaças, vulnerabilidades e mitigações. Rafael no comando: phishing.", timestampSeconds: 100 },
      { speaker: "Ana", text: "Engenharia social é exploração humana, não tecnológica. Phishing chega por e-mail, spear phishing mira alvo específico, vishing é por voz, smishing por SMS, e watering hole infecta sites que a vítima já visita. O treinamento de conscientização é o controle preventivo principal.", timestampSeconds: 108 },
      { speaker: "Rafael", text: "Malware: dá o resumo relâmpago das famílias.", timestampSeconds: 120 },
      { speaker: "Ana", text: "Ransomware sequestra dados por criptografia e cobra resgate. Trojan se disfarça de software legítimo. Worm se replica sozinho pela rede. Spyware espia. Adware empurra anúncios. Keylogger grava teclas. Rootkit se esconde no nível mais profundo. Dica: se a questão fala em propagação automática pela rede, é worm, não vírus.", timestampSeconds: 124 },
      { speaker: "Rafael", text: "E os ataques de injeção? SQL injection e XSS confundem muita gente.", timestampSeconds: 138 },
      { speaker: "Ana", text: "SQL injection ataca o banco de dados com comandos embutidos na entrada; a defesa é consulta parametrizada. XSS injeta script malicioso no navegador da vítima; a defesa é validação e sanitização da saída. Regra de bolso: injection é contra o servidor, XSS é contra o cliente.", timestampSeconds: 143 },
      { speaker: "Rafael", text: "Ana, e a família dos ataques de rede: DDoS, ARP poisoning, on-path?", timestampSeconds: 156 },
      { speaker: "Ana", text: "DDoS sobrecarrega o alvo com tráfego em massa de fontes distribuídas. ARP poisoning corrompe a tabela de tradução de endereço para mac para interceptar tráfego local. On-path, antes chamado de man-in-the-middle, intercepta e pode alterar a comunicação em trânsito. Mitigação trio: criptografia forte, segmentação de rede e monitoramento contínuo.", timestampSeconds: 161 },
      { speaker: "Rafael", text: "Vulnerabilidades e exposição: o que diferencia vulnerabilidade de ameaça e de risco?", timestampSeconds: 176 },
      { speaker: "Ana", text: "Vulnerabilidade é a fraqueza existente, ameaça é quem pode explorar, e risco é a probabilidade vezes o impacto. Exploit é a ferramenta que usa a vulnerabilidade, e zero-day é a falha sem patch disponível. Patch management é o processo que fecha essa porta.", timestampSeconds: 181 },
      { speaker: "Rafael", text: "CVSS: o que o aluno precisa decorar?", timestampSeconds: 193 },
      { speaker: "Ana", text: "CVSS mede a severidade técnica da vulnerabilidade, de zero a dez. Base, temporal e ambiental são os três grupos de métricas. Zero a três e nove é baixa, quatro a seis e nove é média, sete a oito e nove é alta, e nove a dez é crítica. Prova do Security+ pergunta isso de forma direta.", timestampSeconds: 197 },
      { speaker: "Rafael", text: "Controles técnicos na prática: firewall, IDS e IPS. Me dá a diferença em dez segundos.", timestampSeconds: 210 },
      { speaker: "Ana", text: "Firewall filtra tráfego por regras. IDS detecta e alerta, mas não bloqueia. IPS detecta e bloqueia em linha. Lembrete de ouro: IDS é passivo, IPS é ativo. E o honeypot atrai atacantes para estudo, enquanto o honeynet é uma rede inteira de iscas.", timestampSeconds: 215 },
      { speaker: "Rafael", text: "Gatilho final do episódio, Ana: as três frases que salvam na prova amanhã.", timestampSeconds: 228 },
      { speaker: "Ana", text: "CIA: confidencialidade, integridade, disponibilidade. Mínimo privilégio: só o necessário. Defense in depth: camadas que se protegem. Com esses três na cabeça, o Domínio 1 e a maior parte do Domínio 2 já estão garantidos. Agora o episódio seguinte: domínios três, quatro e cinco!", timestampSeconds: 233 },
      { speaker: "Rafael", text: "Nos vemos no próximo Ao vivo! Revisa, refaz o quiz, e boa prova, estudantes!", timestampSeconds: 248 },
    ],
  },
  {
    id: "ep62-ao-vivo-revisao-dom3-a-dom5",
    domainCode: "DOM3",
    domainTitle: "Security Architecture",
    episodeNumber: 62,
    title: "AO VIVO: revisão relâmpago de domínios 3, 4 e 5 — arquitetura, operações e gestão",
    description: "Edição ao vivo especial: Ana e Rafael fecham a série revisitando arquitetura de segurança, operações de segurança e gestão de riscos com os gatilhos finais para o dia da prova.",
    audioUrl: "/manus-storage/ep62-ao-vivo-revisao-dom3-a-dom5_199a549f.wav",
    duration: "4m42s",
    topics: ["revisão relâmpago", "arquitetura e identidade", "operações e forense", "governança e risco", "gatilhos de memória"],
    examWeight: "18% + 16% + 12% do exame",
    provenance: bonusProvenance("ep62-ao-vivo-revisao-dom3-a-dom5", "CyberCast 62 — Ao vivo: revisão relâmpago de domínios 3, 4 e 5"),
    transcript: [
      { speaker: "Rafael", text: "E aí, Ana! Sessenta episódios no ar e a revisão relâmpago continua. Domínios três, quatro e cinco fecham a prova. Domínio três é o maior peso: dezoito por cento. Arquitetura e operação segura, de onde a gente começa?", timestampSeconds: 0 },
      { speaker: "Ana", text: "Da criptografia, Rafael, porque ela responde a quase tudo. Criptografia simétrica usa a mesma chave para cifrar e decifrar, é rápida, mas precisa de canal seguro para a chave. Assimétrica usa par de chaves: pública cifra, privada decifra. TLS junta as duas na prática.", timestampSeconds: 12 },
      { speaker: "Rafael", text: "E hash? É criptografia?", timestampSeconds: 24 },
      { speaker: "Ana", text: "Não é reversível, por isso não é cifra, é assinatura de integridade. SHA dois e SHA três são as famílias atuais; MD cinco é obsoleto. E a chave do HMAC é o hash com segredo: sem a chave, ninguém consegue recomputar. Salting adiciona aleatoriedade ao hash de senha para derrotar o rainbow table.", timestampSeconds: 28 },
      { speaker: "Rafael", text: "PKI e certificados em uma frase, Ana!", timestampSeconds: 41 },
      { speaker: "Ana", text: "Autoridade certificadora emite o certificado, registra a identidade e o par de chaves, e a cadeia de confiança vai da raiz até o dispositivo. CRL lista certificados revogados; OCSP consulta um por vez, em tempo real. Certificado expirado ou revogado é alerta vermelho na prova.", timestampSeconds: 46 },
      { speaker: "Rafael", text: "Identidade e acesso: multifator resolve a questão. Me lembra os fatores.", timestampSeconds: 59 },
      { speaker: "Ana", text: "Três fatores: algo que você sabe, senha; algo que você tem, token ou smartphone; algo que você é, biometria. E o SSO dá acesso único com credencial única, enquanto o IdP centraliza a gestão das identidades. Lembrete: SSO sozinho não é multifator; combine os dois.", timestampSeconds: 64 },
      { speaker: "Rafael", text: "Arquitetura de rede: segmentação e zonas de confiança.", timestampSeconds: 77 },
      { speaker: "Ana", text: "Segmentação separa o tráfego por função: VLANs, sub-redes e microssegmentação. A DMZ expõe serviços públicos sem entregar a rede interna. Air gap isola fisicamente o ambiente mais crítico, e honeynet engana atacantes para estudo. Menos confiança entre zonas, menos caminho para o atacante.", timestampSeconds: 81 },
      { speaker: "Rafael", text: "Segurança em cloud: responsabilidade compartilhada.", timestampSeconds: 94 },
      { speaker: "Ana", text: "O provedor responde pela segurança da nuvem, a infraestrutura; você responde pela segurança na nuvem, seus dados, identidades e configurações. Em IaaS você controla quase tudo; em SaaS, quase nada da infraestrutura. E o CASB fiscaliza o uso de aplicações em nuvem entre você e o provedor.", timestampSeconds: 98 },
      { speaker: "Rafael", text: "Domínio três fechado! Domínio quatro, operações de segurança: monitoramento, resposta a incidente e forense.", timestampSeconds: 111 },
      { speaker: "Ana", text: "Alerta, triagem, análise, contenção e recuperação. O SIEM centraliza e correlaciona os logs; o SOAR automatiza os playbooks. E a ordem de resposta não é opcional: contenção primeiro para limitar o dano, erradicação em seguida, recuperação por último, e lições aprendidas sempre.", timestampSeconds: 117 },
      { speaker: "Rafael", text: "Forense: cadeia de custódia em dez segundos.", timestampSeconds: 130 },
      { speaker: "Ana", text: "Preservar, documentar, coletar com integridade, analisar em ambiente isolado e reportar. Hash da evidência na coleta, registro de quem manipulou cada item. Sem cadeia de custódia, a evidência vira papel inútil no tribunal.", timestampSeconds: 134 },
      { speaker: "Rafael", text: "Backup e resiliência: RPO e RTO confundem todo mundo.", timestampSeconds: 146 },
      { speaker: "Ana", text: "RPO é quanto dado você pode perder, define a frequência do backup. RTO é quanto tempo você pode ficar fora do ar, define a velocidade da recuperação. Backup completo captura tudo; incremental grava só o que mudou; diferencial grava desde o último completo. Três cópias, dois locais, uma fora é a regra três dois um.", timestampSeconds: 150 },
      { speaker: "Rafael", text: "E o Domínio 5, governança de risco e compliance, que fecha os doze por cento finais.", timestampSeconds: 164 },
      { speaker: "Ana", text: "Governança define quem decide; risco quantifica; compliance garante que as regras são seguidas. ALE é perda anual esperada: SLE vezes ARO. Se a mitigação custa menos que a ALE, vale a pena. Transferir é o seguro; aceitar é documentado; evitar é descontinuar a atividade.", timestampSeconds: 170 },
      { speaker: "Rafael", text: "Políticas, padrões e procedimentos: qual é a hierarquia?", timestampSeconds: 183 },
      { speaker: "Ana", text: "Política é a direção, o porquê, aprovada pela alta gestão. Padrão é a medida técnica obrigatória, o como. Procedimento é o passo a passo, e guideline é a recomendação flexível. BCP mantém o negócio rodando; DRP restaura a tecnologia; tabletop exercise testa tudo isso sem causar dano real.", timestampSeconds: 187 },
      { speaker: "Rafael", text: "Gatilho final da série, Ana: o que você diria para quem fecha o caderno agora?", timestampSeconds: 201 },
      { speaker: "Ana", text: "Leia a questão duas vezes, desconfie do absoluto, e lembre: a prova cobra o profissional que pensa em defesa em camadas, privilégio mínimo e melhoria contínua. Você não decorou sessenta episódios à toa. Confia no estudo.", timestampSeconds: 206 },
      { speaker: "Rafael", text: "Isso é tudo no Ao vivo com Ana e Rafael, o especial de revisão relâmpago do CyberCast! Revisa os dois episódios, refaz os quizzes, respira fundo e vai buscar a sua Security+. Até a próxima aventura!", timestampSeconds: 220 },
    ],
  },
];
